label a1s7:
scene bg throneroom with fade
"Je suis Neferu jusqu'à la salle du trône, la pièce caverneuse est aussi vide qu'elle l'était lors de la première Épreuve."
"Comme lors de la première Épréuve, quelques-uns des habitués du palais sont assis sur les bancs; Virginia sur le côté gauche de la pièce, tandis qu'Alex est assis sur la droite."
"Le chat est assis seul, il a l'air minuscule par rapport au reste de la pièce, sa queue parfaitement enroulée sous ses pattes sur ses genoux."
"Il sourit quand il me voit, et je m'apprête à le rejoindre ... mais c'est là que le chacal me prend la main."
"Je m'arrête et je vois le regard curieux d'Alex avant de me tourner vers Neferu."
m "\"Quoi?\""
show nef sidetalk f with dissolve
n "\"Pourquoi ne donnons-nous pas un peu de compagnie à Virginia?\""
show nef sidesmile f with dis
"Le chacal me sourit doucement, une de ses oreilles bougeant en direction de la louve."
m "\"Euh, tu peux. Je vais m'asseoir avec Alex.\""
"L'expression de Neferu ne change pas, mais il ne me lâche pas non plus, et sa voix prend un ton doux mais inquiétant, me mettant un peu mal à l'aise."
show nef sidetalk f with dis
n "\"En fonction du déroulement de cette épréuve, il se peut que nous ayons des affaires à régler avant qu'elle ne se termine officiellement. Il vaudrait mieux que tu restes proche de moi.\""
"Je comprend où il veut en venir."
"Bien que je ne connaisse pas quel est le processus pour devenir \"l'animal de compagnie\"de Neferu, j'imagine que cela implique une sorte de procédure officielle, comme signer quelque chose."
hide nef with dissolve
"Alors, je fronce les sourcils à Alex et hausse les épaules, faisant un geste vers le chacal."
"Le chat continue d'avoir l'air confus alors que je me détourne et suis Neferu jusqu'aux bancs de l'autre côté de la pièce."
play background "music/memories.ogg" fadein 5.0
show vir at left with dissolve
v "\"Neferu.\""
"Virginia s'assoit délicatement sur le banc, une jambe élégamment croisée sur l'autre alors qu'elle tend une patte, que le chacal embrasse."
show nef a at right with dissolve
n "\"Bonne journée à toi, Virginia.\""
"Même si j'essaye de rester derrière Neferu, Virginia regarde par delà la côte musclée du chacal pour me regarder directement."
show vir tilt with dis
v "\"Je vois que tu as amené un invité.\""
"Elle tend à nouveau sa patte, et il me faut un moment pour réaliser que je devrais l'embrasser."
"J'ai commencé cette tendance après tout."
show nef with dis
n "\"En effet. Amicus a demandé que je lui tienne compagnie pendant l'Épreuve.\""
"En sortant du baiser de la patte, je vois Virginia froncer les sourcils."
show vir serious with dis
v "\"Mon frère ne devrait pas t'accabler d'une corvée idiote comme celle-là. L'animal est capable de rester dans sa chambre, j'imagine.\""
show nef a with dis
n "\"C'était un accord mutuel. De plus, il est plutôt de bonne compagnie une fois que l'on apprend à le connaître.\""
v "\"Oh vraiment? Il semble que notre petit simien soit plein de surprises.\""
"La louve me regarde ostensiblement, et je n'ai pas beaucoup de temps pour me demander de quoi elle parle avant que Neferu ne s'assoie à côté d'elle, me tirant à ses côtés pour m'asseoir à côté de lui."
show nef f with dis
n "\"C'est le cas en effet.\""
"Il y a une pause momentanée avant que je ne vois du coin de l'oeil Virginia se pencher."
"Quand elle parle à nouveau, sa voix est basse."
show vir sad p with dis
v "\"Les rumeurs sont donc vraies?\""
"Il y a une autre pause, cette fois de Neferu."
show nef serious with dis
n "\"Je ne crois pas être en mesure de spéculer là-dessus. Ce n'est pas à moi de m'impliquer dans la politique des loups.\""
show vir smile p
"Virginia rit doucement, un qui semble complètement faux."
v "\"Je ne suis pas une imbécile, Neferu. J'apprécie peut-être tes tactiques suaves, mais je préfère que tu ne les utilises pas contre moi.\""
show nef sad with dis
n "\"Je ne rêverais pas d'une telle chose, Virginia.\""
show vir tilt with dis
v "\"Évidemment.\""
"Virginia change de nouveau de position et maintenant je sais avec certitude qu'elle me regarde directement."
v "\"Alors ... je suppose qu'il comprend ce que nous disons?\""
show nef f with dis
n "\"Eh bien, il est intelligent, et il possède un lingua.\""
show vir serious with dis
v "\"Je veux dire, il {i} nous comprend {/ i}.\""
"Virginia met encore plus l'accent sur le mot."
"Je vois Neferu regardant le sol, toujours souriant, bien que ses pattes semblent se serrer un peu plus que d'habitude."
show nef a with dis
n "\"Tu le saurais mieux que moi, étant un loup. Nos enfants sont aussi intelligents que nous, alors je suis habitué à une telle idée.\""
show vir smile with dis
v "\"Ne feint pas l'ignorance, Neferu. Tu as été beaucoup plus près de lui que moi. C'est une question simple, à laquelle tu devrais répondre honnêtement, sinon dois-je supposer que tu as amené un petit espion à notre conversation?\""
"Bien que les mots semblent durs et dangereux, le ton de Virginia est léger et Neferu rit."
show nef smile with dis
n "\"tu m'accuses de tromperie, mais nous savons tous les deux que tu as déjà trouvé la réponse. Pourquoi {i} tu {/ i} feignes l'ignorance?\""
"Le loup s'évente avec un air de nonchalance."
show vir serious with dis
v "\"C'est la meilleure arme dans les conversations ... et il est facile de feindre la stupidité, du moins pour moi. C'est ce qu'on attend de ma part.\""
show nef sad with dis
n "\"Et pourquoi dis-tu une telle chose?\""
show vir talking p with dis
v "\"J'ai un vagin, Neferu.\""
show nef smile eyes a with dis
"Il me faut un moment pour absorber ce que Virginia vient de dire, mais Neferu rit déjà avec ce qui est probablement le premier vrai rire de la conversation."
"Je vois Alex nous regarder à nouveau, et cette fois, il semble que ses yeux se sont un peu plissés."
"Il faut quelques secondes au chacal pour reprendre le contrôle alors que Virginia continue d'agiter son éventail, l'air plutôt contente d'elle-même."
show nef smile eyes with dis
n "\"Désolé, je ne suis pas habitué à la franchise ici.\""
show vir with dis
v "\"Il n'est pas impossible pour nous d'être franc sur cette lune, Neferu, surtout entre amis.\""
"Je remarque que le loup me regarde à nouveau, et encore une fois, je baisse les yeux."
v "\"Quoi qu'il en soit, il semble que nous ayons fait une erreur en oubliant Simia. Je devrai peut-être faire mes propres recherches dans les archives. Amicus savait clairement quelque chose que nous ne savions pas.\""
"Des recherches?"
"Je sens mon estomac tomber."
"Bien qu'Amicus m'ait assuré que ce serait une bonne couverture, je ne sais même pas si je ressemble vraiment à un Simien."
"Tout ce qu'il faudrait, c'est une photo pour savoir que je ne suis pas vraiment de Simia."
hide vir
hide nef
with dissolve
play sound "sfx/dooropen.ogg"
stop background fadeout 10.0
"J'essaye de chasser cette pensée de mon esprit pour l'instant alors que les portes s'ouvrent soudainement et que Cato entre, se dirigeant rapidement vers le trône."
"Virginia me quitte enfin des yeux, et je ne peux qu'espérer qu'elle ne suivra pas ses plans de recherche."
"La salle du trône est si silencieuse que j'entends le vieux loup grogner alors qu'il monte les escaliers avant de se tourner vers nous."
"Après quelques secondes, il s'assied, son corps lourd et musclé un peu affalé sur son siège, nous regardant à travers sa visière."
"Quelques instants de plus passent en silence, et juste au moment où je me demande si l'Épreuve va commencer, j'entends un léger vrombissement mécanique tandis que le panneau du plafond s'ouvre."
"Une douzaine de drones caméra flottent paresseusement, se déployant dans les airs pour se positionner à divers endroits dans la pièce."
"L'un d'eux flotte vers nous et plane juste au-dessus de nos têtes, l'objectif semblant se concentrer sur mon visage."
"Je baisse encore la tête, l'action étant devenue une seconde nature depuis que j'ai atterri sur cette lune."
"Neferu me donne un coup de coude cependant."
n "\"Allons allons. Amicus t'a amené ici pour être vu.\""
"Son ton est léger comme toujours, mais je sens qu'il ne dit pas ça juste pour me taquiner."
"Nous jouons tous un rôle ici, et mon rôle est de donner une belle image à Amicus, de montrer aux triumvirats qu'il s'est donné beaucoup de mal pour obtenir un animal exotique, fascinant et extraterrestre."
"Je n'aime peut-être pas ça, mais ça n'a pas d'importance pour le moment, alors je lève la tête."
"Au lieu du regard muet et vide que j'utilisais ce mois-ci, je pars avec un visage complètement impassible."
n "\"Regarde la lumière rouge sur le dessus du drone. Lorsqu'elle devient verte, c'est que nous sommes en cours de diffusion.\""
com "\"La deuxième épréuve commencera dans dix secondes.\""
scene bg throneroomdark with dissolve
"Avec ça, les lumières s'assombrissent lentement et tout devient complètement silencieux."
"Je suis juste assis là, regardant vers le trône, Caton assis aussi immobile qu'une ancienne sculpture romaine."
play sound "sfx/dooropen.ogg"
"Ensuite, les portes s'ouvrent et nous regardons tous dans leur direction, y compris les caméras."
show ami at left
show cas at right
with dissolve
"Amicus et Cassius s'avancent, côte à côte."
"Ils ont dû attendre l'un à côté de l'autre, tout comme Alex et moi l'avons fait avant la première épreuve."
"Je me demande ce que ça a dû être."
"Sans un mot, ils marchent tous les deux dans l'allée large et moquettée, synchronisés l'un avec l'autre."
"Je regarde attentivement Amicus alors qu'il passe, juste au cas où il me regarderait et je pourrais lui faire un sourire encourageant."
"Il regarde droit devant lui cependant, une expression plus sérieuse sur son visage que je n'ai jamais vu."
"Tout reste silencieux, le seul son étant le battement étouffé de leurs pieds rembourrés et de leurs griffes sur le tapis."
"Une fois qu'ils ont atteint le pied des escaliers, ils s'arrêtent avant de s'incliner tous les deux devant Caton."
"Cela dure quelques secondes avant que Cato ne change finalement de position, brisant l'illusion qu'il était fait de pierre."
ca "\" Très bien. Vous pouvez commencer.\""
hide smie
hide cas
hide ami
with dissolve
"Sur ce, les deux frères se redressent avant de monter les marches, se séparant pour se mettre de chaque côté de l'empereur par intérim."
"Ils se retournent et nous font face, tous deux au garde-à-vous, les bras tendus le long du corps."
"Un drone lévite du plafond et s'arrête doucement en l'air devant Cato."
"Je remarque que la minuscule lumière rouge sur le dessus du drone devient verte, et le vieux loup fixe ses yeux sur la caméra."
ca "\"Bienvenue à l'Épreuve de rhétorique.\""
ca "\"La rhétorique a longtemps été un aliment de base de la civilisation des Loups et l'un de nos plus grands atouts.\""
ca "\"Bien que connus pour notre force et notre ténacité, nous le sommes aussi pour notre utilisation des mots dans les négociations.\""
"Neferu étouffa un gloussement à côté de moi, assez fort pour que je me demande si Cato a pu l'entendre."
"J'espère que non."
ca "\"C'est pourquoi il est non seulement important d'honorer l'art et l'histoire du débat d'aujourd'hui, mais aussi de prouver notre capacité à bien l'utiliser.\""
ca "\"Être un rhéteur compétent est essentiel pour être un empereur compétent.\""
ca "\"Souvenez-vous des règles; vous aurez la parole pendant vingt minutes. Ne faites pas référence à votre challenger. Maintenant, Amicus—\""
"Je vois la moindre contraction dans le cadre d'Amicus alors qu'il continue de regarder devant lui."
a "\"Oui, empereur?\""
ca "\"S'il te plaît, honore Adastra et commence l'Épreuve. Fais part de ta politique à travers l'art de la parole.\""
"Il y a une légère pause, puis Amicus descend les escaliers."
"S'il est nerveux, ce que je sais qu'il est, il ne le montre pas du tout, ses mouvements sont calmes et réservés."
"Il fait plusieurs pas en avant, s'éloigne des escaliers pour se tenir au milieu de l'allée, juste légèrement devant moi."
show ami serious with dissolve
"Il est si proche, et j'aurais aimé pouvoir juste dire quelque chose, me lever et lui faire un câlin et lui dire qu'il va être génial."
"Mais je sais que l'heure n'est plus aux étreintes. Le moment pour lequel Amices s'est préparé toute sa vie est arrivé."
"C'est une sensation étrange que de regarder quelque chose qui va avoir un impact énorme sur votre vie, mais de ne pas pouvoir participer du tout."
"Je ne peux qu'espérer qu'Amicus est prêt."
play music "music/reveal2.ogg"
show ami talking with dis
"Il commence à parler, et quand il le fait, ce n'est pas comme sa voix habituelle."
"Au lieu de cela, c'est plus profond, plus sonore."
"En fait, c'est plus proche du chant humain."
a "\"Il y a vingt millénaires, nous avons été choisis par les Romanus.\""
a "\"Sur mille espèces, ils nous ont choisis, et n'était-ce pas pour une raison?\""
"Il bouge beaucoup ses bras et ses pattes aussi, en larges mouvements de balayage."
"Ce n'est pas différent de la danse, bien qu'il reste la plupart du temps au même endroit."
a "\"Il y a quinze millénaires, nous les avons rejetés, nous sommes devenus les premiers frères abandonnés, et notre empire est entré dans un déclin comme nous n'avions jamais vu auparavant; coupant nos relations avec les autres frères et sœurs, perdant des enfants, perdant des ressources—\""
"Un drone flotte autour de son corps, et je peux dire qu'il est en train de tout donner, faisant des gestes dramatiques avec des expressions très exagérées."
"Je me rends compte que c'est comme si je regardais ces dramas que j'ai vus à la télévision Adastrane."
a "\"- Nous sommes tombés longtemps et durement, comme si notre lune même était aspirée dans un puit. Cinq mille ans de misère et de désolation, cinq mille ans jusqu'à ce que Drusus nous sauve tous.\""
"Amicus poursuit en décrivant l'histoire dont j'avais une vague connaissance, comment Drusus a rétabli le contact avec les parents, a réuni l'empire des loups et a renommé le monde Adastra, un nom qui représentait tout ce que l'empire représentait."
a "\"Depuis lors, nous nous sommes répandus dans toute la galaxie, avons retrouvé des enfants perdus, établi des routes vers les ressources dont notre lune avait désespérément besoin ...\""
a "\"Mais qu'est-ce que nous avons trouvé le plus précieux? Relancer les relations diplomatiques avec les autres frères et sœurs.\""
a "\"Avec eux, nous avons partagé nos connaissances et nos richesses, nous établissant à nouveau comme de véritables frères et sœurs ... jusqu'à la guerre.\""
a "\"Alors que nos raisons étaient solides pour déclencher le conflit, l'attaque soudaine et inattendue a effrayé les autres frères et sœurs, les laissant une fois de plus nous abandonner.\""
a "\"Nous avons défendu nos droits et notre dignité contre les Khemians—\""
n "\"Oh, Ahhotep ...\""
"Neferu marmonne ça dans sa barbe, heureusement."
a "\"Mais à un prix très élevé. Notre empire a souffert pour notre victoire ... mais il existe un moyen de renverser la situation.\""
"Je ne sais pas si le loup fait du bon travail puisque je n'ai aucun point de référence, mais pour autant que je sache, il semble bien se débrouiller."
"Pas de bégaiement, ni de trébuchement, son jeu est plutôt bon, surtout si je le compare aux acteurs dramatiques que j'ai vus sur les écrans."
"Ses mouvements sont puissants, mais élégants, tout comme sa voix, et je me retrouve rayonnant d'un sentiment de fierté que je n'ai jamais eu pour quelqu'un d'autre auparavant."
"Il poursuit en décrivant les politiques dont il m'avait déjà parlé: rétablir les relations avec les frères et sœurs, élever pleinement les enfants, remodeler leur rôle dans l'empire."
a "\"Et la première étape?\""
"Amicus se tourne soudainement pour nous faire face, bien que son regard soit sur Neferu."
a "\"Une alliance, une qui a été proposée par les Khemians.\""
a "\"Cela peut vous sembler une perspective inquiétante; cela n'a jamais été fait dans l'histoire des {i} Galaxias {/ i}, mais je peux vous promettre qu'en tant qu'empereur, j'exigerai le respect et l'égalité de traitement de la part des Khemians.\""
show ami motivated with dis
a "\"Leur arrogance sera apprivoisée et la dignité des loups sera restaurée.\""
"La lumière sur le drone caméra devant nous est verte, diffusant notre image à l'ensemble d'Adastra."
"Je suis au moins content que Neferu soit capable de contrôler son roulement des yeux en ce moment."
show ami talking with dis
a "\"Dans le cadre de mon règne, je placerai Adastra sur le même piédestal que tous les autres frères et sœurs, sinon plus haut. Nous ne serons plus le demi-frère des {i} Galaxias {/ i}.\""
a "\"Non, nous nous étendrons encore une fois au-delà de notre système, au-delà de notre quadrant, et oui, éventuellement au-delà de la galaxie.\""
"Amicus montre le plafond."
show ami motivated with dis
stop music fadeout 10.0
a "\" Comme Drusus l'a proclamé il y a dix millénaires; 'aux étoiles'.\""
a "\"Alors je dis maintenant; vers les étoiles et au-delà.\""
"Amicus fait une pause dramatique dans cette pose, puis s'incline avant de se retourner et de retourner sur le trône."
hide ami with dissolve
ca "\"Merci, Amicus. Cassius?\""
"J'ai laissé échapper un souffle, regardant Amicus monter les marches, dépassant Cassius alors que son frère se dirigeait vers le même endroit sur le sol."
"Alors c'est tout."
"La partie d'Amicus est terminée."
"Maintenant c'est au tour de Cassius, et je le regarde se diriger vers le même endroit, un air renfrogné de colère sur le visage."
show cas annoyed with dissolve
"C'est plus en colère que d'habitude, presque furieux, et je me demande s'il est bouleversé par les bons résultats d'Amicus."
"Mais ensuite il commence à parler, et je réalise que cela fait partie de sa présentation."
play music "music/tension.ogg" fadein 3.0
show cas angry with dis
c "\"Depuis trois cents ans, notre empire est en ruine!\""
"Je sursaute, et je sens même Neferu se crisper à côté de moi alors que le loup blanc hurle pratiquement."
c "\"Pas à cause de la guerre, pas parce que nous avons choisi une voie différente. Non, c'est {i} à cause {/ i} de Drusus et de sa vision imparfaite des {i} Galaxias {/ i} dans leur ensemble!\""
c "\"Mon frère avait raison à propos d'UNE chose ... Adastra est la dernière des dernières parmi les frères et sœurs, la risée de toute la galaxie!\""
ca "\"Aucune référence à Amicus, Cassius!\""
"Cato aboie de l'autre côté de la salle du trône, mais l'autre loup l'ignore, passant sa patte dans les airs, ses mouvements agressifs et violents."
show cas furious with dis
c "\"ASSEZ d'être la cible de plaisanteries, d'être craché dessus, d'être considéré au niveau de simples enfants!\""
c "\"Il est temps qu'Adastra soit à nouveau respecté, vénéré ... et craint, comme avant Drusus.\""
"Le discours de Cassius continue comme ça, décrivant Adastra en des termes qui la font sonner comme le pire endroit de la galaxie."
"Je ne sais pas si c'est bon ou pas."
"Il est définitivement beaucoup plus intense qu'Amicus, et si c'est le but, alors je suis inquiet."
"Je jette un coup d'œil à Neferu et Virginia, et les regards troublés sur leurs visages me disent que je devrais être encore plus inquiet."
"Je lève les yeux vers le trône, mais Amicus est toujours aussi immobile et impassible."
"Je me sens commencer à transpirer, me demandant si c'est le début de la fin."
show cas angry with dis
c "\"Mon frère a déclaré que la guerre était responsable de notre déclin soudain, un déclin pas si soudain alors qu'il se produit depuis des milliers d'années!\""
c "\"Non, cette guerre était la meilleure chose qui aurait pu arriver à cet empire. Cela montrait que nous n'avions pas peur, que la force la plus puissante de la galaxie ne nous intimidait pas!\""
c "\"On s'est moqué et on a rit de nous avant la guerre! Maintenant, ces rires sont plus calmes, alors que nos frères et sœurs réalisent à quel point nous pouvons être dangereux. Ils nous prennent au sérieux maintenant ...\""
"Cassius tourne son regard furieux sur nous."
c "\"... mais pas assez sérieusement. Regardez qui ils ont envoyé pour proposer ceci ... cette {i}alliance{/ i} dont mon frère a parlé.\""
ca "\"Aucune référence à Amicus, Cassius.\""
"Mais Cato est plus calme maintenant, comme s'il savait qu'il ne pouvait pas arrêter le jeune loup."
"Le voyant de notre caméra devient vert, et j'ai à nouveau l'impression que l'émission affiche Neferu."
c "\"La seule et unique fleur de Khemia. Le fils pédé du pharaon avec ses huiles et ses parfums, puant dans les couloirs de notre palais!\""
"Je regarde Neferu, mais son expression n'a guère changé, même si je vois un soupçon de sourire narquois sur ses lèvres."
"Pendant ce temps, Virginia cache un regard de choc, ou d'horreur ... ou les deux, derrière son éventail."
c "\"Cette alliance est hautement suspecte, et je dois me demander ce qui se passe réellement pendant ces ... négociations. En fait, laissez-moi vous donner une idée.\""
"Cassius fait une sorte de signal avec sa patte, puis fait une pause."
"Tout est silencieux pendant un moment, et en regardant les caméras ... aucune d'elles n'est verte."
"Je regarde les autres et je peux voir qu'ils sont également confus."
ca "\"Qu'est ce que tu diffuses, Cassius?\""
"Cassius ne se retourne même pas pour répondre à Cato."
show cas right with dis
c "\"Je montre juste un petit clip vidéo.\""
ca "\"De quoi?\""
"Je vois Amicus se hérisser à côté de Cato, et je sens les cheveux se dresser sur mon propre cou."
c "\"D'un acte traître entre mon frère et la fleur de Khemia.\""
a "\"Quoi!?\""
"La fourrure d'Amicus est tellement hérissée qu'il a presque deux fois sa taille naturelle."
a "\"Qu'est ce que tu fais!?\""
ca "\"Oui Cassius, que {i}fais{/ i}tu?\""
a "\"Cato, il a mis ma chambre sur écoute!\""
"Amicus commence à bouger, mais Cato sort de son trône pour le retenir."
show cas smile with dis
c "\"Reste là, mon frère, c'est presque fini. Et ne t'inquiètes pas; c'est censuré.\""
"Cassius ricane à Amicus avant que la lumière rouge de son drone ne redevienne soudainement verte."
show cas annoyed with dis
"Cassius fixe l'objectif pendant un moment, laissant le silence s'étirer pour un effet dramatique."
c "\"Choquant, n'est-ce pas? J'ai déjà décris la Fleur de Khemia ... voulons-nous aussi que la Fleur d'Adastra soit notre empereur?\""
ca "\"Le temps, Cassius.\""
"La voix de Cato est douce, presque étonnée."
"Amicus a clairement beaucoup plus de mal à contrôler ses émotions maintenant."
"Même de cette distance, je peux le voir travailler sa mâchoire."
"Mais Cassius ne semble pas avoir fini."
c "\"Et laissez-moi vous laisser avec ceci—\""
ca "\"Le temps, Cassius. Céde la parole!\""
show cas furious with dis
c "\"Non, je ne céderai pas! Adastra est celle hors du temps! Cet empire est surexploité, et ce {i}leveur de queue{/ i} nous propose de nous étirer encore plus! Quand casserons nous!?\""
"Cassius se retourne et pointe du doigt Amicus."
c "\"Il regarde vers les enfants et les frères et sœurs tout en nous ignorant complètement!\""
stop music fadeout 10.0
"La fourrure hérissée de Cassius recommence lentement à se recoucher, le loup essayant de reprendre le contrôle de lui-même."
show cas right with dis
c "\"Alors ... laissez-moi vous laisser avec ceci; en faisant campagne dans la périphérie de la ville d'Adastra, des zones complètement négligées par mon frère, je suis tombé sur une jeune enfant atteinte de la même maladie qui m'afflige.\""
"La voix de Cassius devient beaucoup plus calme, douce, abaissant un peu son museau pour fixer le sol."
show cas disappointed with dis
c "\"Contrairement à moi, elle n'avait aucun médicament à proprement parler parce que sa pauvre famille d'agriculteurs n'en avait pas les moyens. Elle était attachée à un fauteuil roulant, ses os si fragiles que quelque chose d'aussi simple qu'un bain les fait se disloquer et se briser.\""
"La voix de Cassius tremble et, à ma grande surprise, je vois une larme couler sur sa joue."
show cas sad with dis
c "\"Comment cet empire a osé laisser notre peuple tomber dans un état tel que nous ne pouvons même pas nous soucier de notre propre peuple. J'entends que même maintenant, nous ne pouvons même pas nous permettre de vacciner ceux qui sont au-delà de notre ville étincelante.\""
"Cassius regarde la caméra."
show cas paw with dis
c "\"Il peut sembler que nous ne pouvons pas vous entendre au-delà des murs de ce palais, mais je vous entends. Je promets de toujours vous entendre. Je ne répondrai pas aux besoins et aux désirs des frères et sœurs ou des enfants, des élites ou des fonctionnaires d'Adastra City.\""
"Cassius balaie dramatiquement une patte contre sa poitrine."
show cas paw talking with dis
c "\"Pas 'aux étoiles', mais à VOUS, les gens de l'empire ... Merci.\""
"Cassius s'incline devant la caméra avant de se retourner pour retourner sur le trône."
hide cas with dissolve
"Il y a un long moment de silence alors que nous regardons tous le loup blanc, puis la voix de Com crépite au-dessus de nos têtes."
com "\"Triumvirats, prenez votre décisions.\""
"Soudain, je sens quelque chose me saisir autour du poignet et je regarde en bas pour voir la patte noire et velue de Neferu se tenant à moi."
show nef serious with dissolve
n "\"[mc], très tranquillement, nous allons nous lever et nous diriger vers ma chambre. Nous allons nous déplacer à l'arrière pour que la caméra ne voie pas.\""
m "\"Pourquoi?\""
show nef angry with dis
n "\"Parce que ce qu'Amicus avait craint est sur le point de -\""
com "\"Les triumvirats ont pris leurs décisions.\""
"Je vois les yeux de Neferu s'écarquiller de surprise."
show nef unsure f with dis
n "\"Déjà?\""
"Il semble se le dire, mais il se lève et je dois me lever avec lui alors qu'il commence à marcher dans l'allée, vers le fond de la pièce, me tirant avec lui."
hide nef with dissolve
"Je regarde Amicus et je vois le loup me regarder, enfin."
"Ses yeux sont pleins d'inquiétude et de regret, et je peux dire que tout le monde sait que Cassius a gagné."
"Mon estomac tombe et je me rends compte que ce qui me terrifie depuis un mois est en train de se produire."
"Nous avons perdu."
"Je ne peux que fixer le bras musclé de Neferu alors qu'il me tire vers les portes, vers un avenir inconnu et indésirable ..."
com "\"Lupas—\""
"Après tout ce temps, après tout ce que nous avions fait ... nous avons perdu."
com "\"Amicus.\""
"Neferu fait une pause."
"Je lève les yeux vers le plafond, vers l'endroit où j'imagine toujours Com s'il était réel, puis je regarde le trône."
com "\"Ad Rotae: Amicus.\""
"Amicus a l'air aussi choqué que moi."
"Cassius, quant à lui, a la mâchoire serrée."
"Comme toujours, je ne peux pas lire les pensées de Cato."
com "\"Lux: Amicus.\""
com "\"Gebii: Amicus.\""
"Qu'est ce qu'il se passe?"
"Tout le monde semblait penser que Cassius allait gagner, et si tout était basé sur la performance ... alors il devrait gagner."
com "\"Tricelli: Amicus.\""
"Il y a une pause, une qui me fait réaliser que nous venons de ... gagner?"
"Avons-nous vraiment gagné?"
com "\"Adastra?\""
"Cato regarde droit devant lui avec sa visière, et maintenant je peux voir ses pattes s'agripper aux accoudoirs de son trône."
"Le silence dure si longtemps que Com demande à nouveau."
com "\"Adastra?\""
"Cato laisse le silence continuer pendant plusieurs secondes de plus avant d'ouvrir enfin son museau."
ca "\"Cassius.\""
"Je ne sais pas quoi penser, mais Com répond immédiatement."
com "\"L'Épreuve a été décidée. Amicus est le vainqueur.\""
"Le silence qui suit cette fois est assourdissant."
"Personne ne se réjouit, personne ne bouge."
"Même l'éventail de Virginia est figé, comme si nous étions tous coincés dans une image."
"Pendant tout ce temps, les caméras continuent de planer au-dessus de nos têtes, chacune d'entre elles clignotant en vert pendant un moment."
"Enfin, Com est à nouveau celui qui brise le silence."
com "\" Ceci conclut la deuxième Épréuve. Merci.\""
"Avec cela, les lumières de la caméra s'éteignent complètement et les drones planent vers le compartiment au plafond."
scene bg throneroom with dissolve
"Les lumières se rallument."
"Neferu me tire une fois de plus vers les portes."
"Je veux me libérer et regarder, mais le chacal insiste, et la prochaine chose que je sais, les portes s'ouvrent tranquillement, et nous entrons dans l'atmosphère tout aussi silencieuse, bien que beaucoup moins tendue, des salles de marbre."
scene bg palace1 with dissolve
play sound "sfx/dooropen.ogg"
play loop "sfx/birds.ogg" fadein 3.0
m "\"Où allons-nous? Nous venons de gagner.\""
"En disant cela, je sens que l'excitation remplace enfin le choc."
"Nous avons gagné!"
m "\"Neferu, nous avons ga-\""
show nef serious with dissolve
n "\"Clairement, mais cela ne signifie pas que tu es encore en sécurité.\""
m "\"Quoi?\""
"Neferu est silencieux pendant un moment, à ce stade le chacal a lâché ma main, me permettant de le suivre."
m "\"Qu'est ce que tu veux dire?\""
show nef skeptic f with dis
n "\"Selon toi, qui aurait dû gagner, [mc]?\""
"Je fronce les sourcils."
m "\"Est-ce que c'est important? Les triumvirats ont décidé. Amicus a gagné.\""
n "\"C'est vrai, mais les triumvirats n'étaient pas les seuls à regarder. Nous savons tous qui aurait dû gagner.\""
"Je me sens sur la défensive."
m "\"Cassius était un connard total, et en plus, il a triché. Il a dépassé le temps imparti ET a fait référence à Amicus et à ses points.\""
"Neferu rit sans joie."
show nef with dis
n "\"Les règles n'ont pas d'importance. Je suis sûr que tu t'en es probablement rendu compte maintenant. Cassius a fait exactement ce qu'il aurait dû ... mais il a perdu à cause de toi.\""
m "\"Quoi?\""
show nef serious a with dis
n "\"Les triumvirats ont clairement pris leurs décisions bien avant l'Épreuve. Nous espérions qu'ils n'iraient pas contre la volonté du peuple, mais la performance de Cassius les a forcés à le faire.\""
m "\"Tu parles de la rumeur selon laquelle Cassius était sur le point de se débarrassé d'eux?\""
n "\"Cette rumeur là en effet. J'avais pensé qu'une victoire aussi déséquilibrée de la part de Cassius aurait dissuadé au moins la plupart d'entre eux. Leur soif de pouvoir est insatiable, semble-t-il.\""
"Encore une fois, je me sens sur la défensive, mais il y a aussi un sentiment d'inquiétude qui s'installe."
m "\"Eh bien ... je ne sais pas, je pense qu'Amicus a fait du bon travail. En plus, c'est LEUR rôle de garder le pouvoir de l'empereur sous contrôle de toute façon, n'est-ce pas?\""
n "\"Oui, mais ce n'est pas le but des épréuves, et les gens le savent. Adastra ne sera pas contente de ça.\""
m "\"Eh bien ... qu'est-ce que cela signifie, alors?\""
"Nous nous arrêtons devant la chambre d'Amicus, et finalement, le chacal se retourne pour me faire face."
show nef with dis
n "\"Ça je ne peux pas te le dire. Je ne suis pas un expert de la politique d'Adastra, je suis simplement un étudiant ici. Amicus a peut-être gagné cette bataille, mais je peux garantir que la lutte pour le pouvoir est loin d'être terminée.\""
n "\"Amicus pourra t'en expliquer davantage à son arrivée. Pour l'instant, attend le dans sa chambre.\""
"Le chacal commence à se retourner pour partir, mais semble remarquer l'expression confuse et probablement inquiète sur mon visage."
"Il fait une pause, puis pose une patte sur mon épaule."
show nef sidesmile f with dis
n "\"Ne t'inquiétes pas trop à ce sujet. C'est normal pour le cours de la politique lupienne, ça je le sais. Le drama est leur identité, et nous ne pouvons qu'être happé par ces intrigues.\""
"Neferu me sourit."
show nef wink f with dis
n "\"Amicus te gardera en sécurité, et si tu as un besoin qu'il ne peut pas satisfaire, je suis également là.\""
"Je sais que Neferu le dit sur un ton lubrique pour que cela paraisse salace, mais je sais aussi qu'il est sincère...et s'inquiète pour moi."
"Je mets ma main sur sa patte."
m "\"Merci.\""
show nef with dis
"Le chacal me fait un signe de la tête avant de se détourner pour remonter le couloir, probablement vers sa propre chambre."
hide nef with dissolve
stop loop fadeout 5.0
"Une fois qu'il est hors de vue, j'appuie ma main sur le panneau et entre dans la chambre d'Amicus, et je m'assois sur le canapé pour attendre."

scene bg amicusroom with fade
"C'est étrange ... Amicus a gagné, mais ce n'est pas l'impression que j'ai après ce que Neferu vient de me dire."
"Amicus n'a pas vraiment gagné ... nous avions gagné à cause d'une rumeur, ce qui rendait tout l'Épreuve inutile."
"Pourtant, je ne peux pas vraiment me sentir mal à ce sujet."
"Cassius a mis sur écoute cette même pièce pour montrer des images d'Amicus en train de baiser Neferu."
"Je ferme les yeux, les frottant avec une main alors que je réalise à quel point cela a pu nuire à la réputation d'Amicus."
"Non seulement les gens se rendent compte que cette épreuve a été décidé dès le début par des triumvirats corrompus, mais aussi que leur futur empereur a eu des relations sexuelles avec un homme ... un homme khémien en plus."
"Mais encore une fois, Cassius qui perd à cause de son intention de se débarrasser des seules rares personnes qui contrôlent son pouvoir me semble juste être du karma."
"N'ont-ils pas gardé le pouvoir de l'empereur sous contrôle en prenant la décision qu'ils ont prise?"
"Techniquement, Amicus deviendra empereur maintenant, bien que je suppose que ce ne sera pas officiel tant que Cassius n'aura pas concédé la troisième Épréuve."
"Je retourne ces pensées encore et encore dans ma tête pendant les 20 minutes suivantes, un peu ennuyé par le fait que même si j'ai eu exactement ce que je voulais, plusieurs problèmes étaient venus avec."
play sound "sfx/dooropen.ogg"
"Soudainement, la porte s'ouvre et j'oublie mon inquiétude pendant un instant alors que je vois Amicus debout là."
"Il ne fait que quelques pas dans la pièce avant que je sois déjà là, enroulant mes bras autour de son corps pendant que je l'étreins'."
show ami with dissolve
play music "music/starship.ogg" fadein 3.0
a "\" Whoa! Hé, [mc]. Tout va bien?\""
"Le loup pose une lourde patte sur ma tête, frottant doucement les coussinets contre mon cuir chevelu."
m "\"Et toi?\""
show ami happy eyes with dis
a "\"Bien sûr.\""
"Amicus me sourit chaleureusement, mais l'ayant connu depuis si longtemps, je sais que ce n'est pas tout à fait vrai."
m "\"Eh bien ... nous avons gagné.\""
show ami with dis
a "\"Nous l'avons fait.\""
"Il est silencieux pendant un moment, continuant à me frotter la tête."
m "\"Ce n'est pas vraiment ce que j'imaginais.\""
"Amicus rit doucement."
show ami happy eyes with dis
a "\"Hahaha ... moi non plus, mais nous avons gagné, et c'est la partie la plus importante.\""
"Amicus me serre à nouveau dans ses bras."
m "\"Est-ce que Cassius a fait, ce qu'il a montré ... à quel point c'était mauvais?\""
show ami serious with dis
"Amicus grimace."
a "\"Mauvais, mais je trouverai un moyen de m'en sortir. Il semble que mon premier travail en tant qu'empereur sera de reconstruire mon image.\""
m "\"Quand est ce que tu deviens empereur?\""
show ami crossed with dis
a "\"Dès que Cassius abandonne. Je ne pense pas qu'il soit encore d'humeur à faire ça, cependant.\""
"Nous restons là pendant un moment, Amicus continuant de me caresser la tête alors que je l'appuis contre sa poitrine, écoutant le doux battement de son cœur."
m "\"Je suis juste content que ce soit fini.\""
a "\"Je ressens la même chose.\""
m "\"Et ensuite?\""
a "\"Eh bien ... pour l'instant, je dois aller en ville. Les triumvirats ont demandé à la famille impériale d'être vue immédiatement.\""
m "\"Oh, pourquoi?\""
a "\"Eh bien, tout le monde suppose que les épreuves sont terminées. Ils aimeraient discuter de choses avec la famille avant de quitter Adastra pour leurs propres villes.\""
m "\"Je vois.\""
a "\"Ils ont également demandé à ce que tu viennes.\""
"Je me penche en arrière pour regarder le loup."
m "\"Vraiment?\""
a "\"Oui, mais je leur ai dit de ne pas s'y attendre. Je sais que tu voulais voir la ville, mais c'est à toi de décider ... et puis, ce ne sera pas vraiment la ville, juste le quartier où vivent les délégués. Les choses sont un peu ... chaotiques dans le centre-ville en ce moment.\""
m "\"Chaotique?\""
show ami serious crossed with dis
a "\"Les citoyens sont ... excités après l'Épreuve.\""
m "\"Ah.\""
"J'imagine qu'excité signifie en colère."
m "\"Je pourrais ... mais faire des trucs officiels semble un peu effrayant.\""
show ami crossed with dis
a "\"Tu n'aurais rien à faire, juste avoir l'air heureux d'être là, mais c'est à toi de décider.\""
m "\"Cela t'aiderait-il?\""
a "\"Peut-être, je serais certainement heureux de t'avoir là-bas.\""
m "\"Alors bien sûr.\""
show ami surprised with dis
"Les sourcils du loup se haussent de surprise."
a "\" Oh, vraiment? Très bien alors. Allons-y.\""
m "\"Maintenant?\""
show ami crossed with dis
a "\" Oui, je crois que les autres sont déjà dans le char. Tu es prêt?\""
m "\"Je ... pense que oui, sauf si j'ai besoin d'apporter quoi que ce soit.\""
a "\"Pas du tout. Et désolé, je sais que les choses évoluent rapidement en ce moment. C'est normal après l'Épreuve, mais nous pourrons parler en privé à notre retour, d'accord?\""
m "\"D'accord.\""
stop music fadeout 10.0
hide ami with dissolve
"Amicus se tourne déjà pour me tirer, mais je l'arrête."
"Quand il se retourne, je fais ce que je voulais faire depuis juste avant le début de l'Épreuve, et je l'embrasse sur les lèvres."

scene bg garden2 with transition_fade
"Le char n'est en réalité qu'un grand chariot métallique."
"Il a des bancs à l'intérieur avec un toit ouvert."
"Il n'y a pas de chevaux, bien sûr, et il semble se déplacer tout seul."
"C'est la première fois que je vois des roues utilisées pour le transport ici, cependant."
"Alors que nous nous approchons, je remarque que Virginia et Neferu sont déjà assis à l'avant ... et Cassius est à l'arrière avec Alex."
"Il détourne délibérément le regard de nous."
"Je chuchote à Amicus alors que nous nous rapprochons du char."
m "\"Cassius vient?\""
a "\"Oui ... Je pense que Cato l'a obligé'.\""
"Malgré tout ce que le loup blanc a fait, en particulier lors de l'Épreuve, je ne peux m'empêcher de me sentir un peu désolé pour lui."
"Je ne peux pas imaginer devoir sortir en public juste après la défaite de votre campagne de plusieurs années."
"Amicus saute en premier, assis à côté de Virginia avant de se pencher vers moi pour me tirer à côté de lui."
m "\"Je pensais que nous volerions là-bas.\""
show ami embarrassed at twelve with dissolve
a "\" Nous le faisons habituellement, mais comme le vaisseau que nous avions l'habitude de transporter en ville, euh, s'est écrasé il y a quelques mois, nous avons décidé que le char était plus sûr et plus discret.\""
show vir at center with dissolve
v "\"Oui, quelque chose qui sera utile compte tenu de l'état de la ville en ce moment.\""
show ami serious crossed with dis
a "\"Oui.\""
m "\"Quel est l'état de la ville?\""
"Virginia fixe ses yeux sur moi, me regardant vraiment pour la première fois depuis longtemps."
v "\"Des émeutes, des pillages, comme d'habitude, bien qu'un peu inhabituel pour Adastra City comparé à, disons, Lux.\""
"Amicus me regarde, mais c'est à ce moment-là qu'il y a une secousse soudaine alors que le char avance, vers la limite des arbres."
play loop "sfx/chariot.ogg" fadein 3.0
"Virginia regarde Amicus."
show vir p with dis
v "\"Je dois dire que ton animal de compagnie est bien plus fascinant que je ne le pensais au départ. Il pouvait à peine parler quand je l'ai rencontré pour la première fois.\""
show ami embarrassed with dis
a "\"Euh ... oui, il était timide.\""
"Je suppose que j'aurais dû dire à Amicus que ma couverture avait été révélé à ce stade."
v "\"Eh bien, il faut renouer avec cette Simia, alors. Ils semblent étrangement intelligents.\""
show ami surprised with dis
a "\"Mmh, oui ... Oh, merci aux dieux pour les arbres. Vita est beaucoup trop dure aujourd'hui.\""
"Amicus essaye clairement de changer de sujet alors que la route se transforme en forêt épaisse."
scene bg forest with dissolve
stop loop fadeout 5.0
play music "sfx/forest.ogg" fadein 5.0
"Nous sommes recouverts d'une étrange lueur verte alors que la forêt nous enveloppe."
"Des insectes étranges et brillants volent autour de notre voiture, et je remarque à quel point les arbres ont l'air vieux, noueux et rugueux, bloquant presque complètement le ciel."
v "\"J'espère qu'ils nous permettront de nous rafraîchir un peu avant la cérémonie. Je ne serais plus présentable au moment où nous atteindrons la ville.\""
"Virginia sort à nouveau son grand éventail brodé, l'agitant frénétiquement sur son visage."
"J'aurais aimé en avoir un aussi, ma peau collant presque immédiatement dans l'air humide."
show nef at zero with dissolve
n "\"Tu t'inquiètes trop tu seras très bien. De plus, nous serons tous dans le même état.\""
show ami crossed serious at twelve with dissolve
"Amicus jette un coup d'œil au chacal."
a "\"Je me demande ce qui t'a amené, Neferu?\""
show nef smile eyes a with dis
n "\"Ma présence a été demandée.\""
a "\"Par qui?\""
show vir serious with dis
v "\"Oh, pour l'amour de Vita, ne commence pas, Amicus.\""
show ami surprised with dis
a "\"Quoi? Je suis simplement curieux. \""
v "\"Non, tu essayes de commencer un combat, ce qui est la dernière chose dont nous avons besoin devant les triumvirats\""
show ami crossed serious with dis
a "\"Hmph ...\""
show vir with dis
v "\"D'ailleurs, ta politique n'est-elle pas de te lier d'amitié avec les Khemians?\""
a "\"Une alliance ce n'est pas de l'amitié.\""
show nef with dis
n "\"Les Khemians le voient comme de l'amitié.\""
v "\"D'ailleurs, tout le monde pense probablement que vous êtes déjà très ... proche après ce qui a été diffusé.\""
show ami shocked with dis
a "\"Virginia!\""
show nef smile eyes a
show vir smile p
with dis
"Elle cache son sourire narquois derrière l'éventail alors que Neferu sourit à côté d'elle."
show vir with dis
v "\"Je te rappelle simplement que cela pourrait être encore frais dans l'esprit de tout le monde lorsque nous arriverons.\""
show ami angry with dis
"Amicus s'affaisse sur son siège, les jambes allongées devant lui."
a "\"Raison de plus pour paraître distant. Cela affectera probablement ma réputation pendant des ANNÉES.\""
show vir p with dis
v "\"Oh, ne sois pas si dramatique. Les gens aiment ces scandales, ils font simplement semblant d'être indignés.\""
"Amicus renifle, mais ne dit rien de plus, signalant que la conversation est terminée."
hide ami
hide nef
hide vir
with dissolve
"Je me demande si Cassius, assis juste derrière nous, écoute."
"Probablement."
"Je trouve tout cela étrange, le loup qui a essayé de saboter Amicus en divulguant ce qui était essentiellement un porno est assis juste derrière nous."
"Je tourne légèrement la tête, essayant de regarder Cassius pour voir s'il nous regarde."
"Je ne vois rien, alors je me retourne plus complètement et constate que le loup blanc est couché, les yeux fermés avec sa tête sur les genoux d'Alex."
show ale with dissolve
"Alex lève les yeux vers moi et sourit avec un signe de la main."
"Je fais un signe maladroit avant de me retourner rapidement."
hide ale with dissolve
"Virginia et Neferu semblaient être pris dans leur propre conversation pour le moment alors qu'Amicus continuait de bouder, fixant ses pieds."
m "\"Alors ... que va-t-il se passer exactement quand nous arriverons?\""
show ami crossed serious with dissolve
a "\"Hm? Oh, eh bien, la rencontre avec les triumvirats, comme je l'ai dit plus tôt.\""
show ami crossed with dis
a "\"Après ça, nous allons probablement marcher dans les rues du quartier pour visiter les boutiques et un restaurant.\""
m "\"Alors je serai juste à côté de toi?\""
show ami eyes with dis
a "\"Oui.\""
m "\"Très bien.\""
stop music fadeout 5.0
"Pour le reste du trajet, je m'appuie contre Amicus, et après plusieurs minutes, je commence à piquer du nez."
"Amicus le remarque et enroule un bras autour de moi, et je suis capable de m'appuyer confortablement contre sa poitrine pour m'endormir ..."

scene bg cityday with transition_fade
"Amicus me réveille avec un petit coup de coude, et lorsque j'ouvre les yeux, je constate que nous sommes arrivés à destination."
"Je me retrouve à regarder plusieurs bâtiments, le changement soudain de décor me laissant étourdi."
"J'essaye toujours de me repérer alors qu'Amicus saute hors de la voiture, tendant les bras pour me soulever."
"Quand je regarde en arrière, je peux voir un grand groupe de loups sur le côté, nous regardant attentivement."
"Immédiatement, je me sens gêné, la foule étant le plus grand rassemblement de loups que j'ai vu en personne."
"Ils sont de toutes formes et tailles différentes, et je suis surpris de voir que certains d'entre eux sont presque aussi petits que moi."
"La seule caractéristique que tous partagent cependant, c'est leur stature imposante."
"Amicus me guide pour me tenir devant le char avec Neferu, Virginia, Cassius et Alex, me tenant près de lui."
"Un des vieux loups sort du groupe."
play music "music/secondthoughts1.ogg" fadein 3.0
"Triumvirat" "\"Bienvenue famille impériale! Merci beaucoup d'être venus en ce jour de la deuxième Épreuve. C'était un spectacle merveilleux!\""
"C'est osé de dire ça après la diffusion d'un clip de Neferu et Amicus en train de baiser."
"Il ne semble pas y avoir de gêne cependant, les vieux loups semblant impatients de parler à Amicus."
"Triumvirat" "\"Je suis Cicéron, premier triumvirat d'Ad Rotae.\""
"Le vieux loup s'avance vers Amicus, posant ses pattes sur les épaules du plus gros loup et touchant les côtés de leurs museaux ensemble."
"Du coin de l'œil, je remarque que Cassius nous lance un regard amer et empli de colère."
"Le loup et Amicus tiennent une courte conversation, le loup plus âgé demandant à Amicus ce qu'il pensait d'Ad Rotae, quels problèmes la ville avait actuellement et comment ils pourraient procéder à l'avenir."
"Après cela, il se dirige ensuite auprès de Virginia où leur conversation est beaucoup plus courte."
"Un autre loup du groupe avance pour parler à Amicus, la conversation suivant un schéma à peu près similaire."
"On ne parle pas d'Amicus comme empereur, mais l'hypothèse est là, et quand chacun d'eux arrive à Cassius, c'est presque aussi bref qu'avec Virginia."
"Malgré la nouveauté de cette situation, je m'ennuie rapidement, et les conversations se mélangent très vite alors que plus d'une douzaine de ces vieux loups s'avancent pour se présenter à Amicus."
"Pour sa part, Amicus fait un très bon travail en semblant enthousiaste pour chaque introduction, mentionnant qu'il sait déjà qui ils sont et qu'il a une très, très haute estime pour leur ville et leur région."
"De temps en temps, ils me regardent et commentent à quel point j'ai l'air étrange, même si c'est généralement avec un ton positif, félicitant Amicus de m'avoir attrapé."
"Cela semble mettre Amicus mal à l'aise, mais je garde un visage impassible et je m'incline à chaque fois, semblant ravir les vieux loups avec mon étiquette."
"Finalement, ces présentations se terminent, mais alors que nous commençons à nous diriger vers les magasins, les triumvirats continuent de nous suivre, et j'ai plus en plus de mal à suivre Amicus."
"Il est pratiquement entouré par les triumvirats."
"J'abandonne mes tentatives de rester à côté de lui, et même s'il n'arrête pas de me regarder et de m'appeler plusieurs fois, je lui fais un signe de la main, choisissant à la place de marcher aux côtés de Neferu et de Virginia."
"Bien sûr, c'est ennuyant, mais il est sur le point de devenir empereur, donc il est logique qu'il soit si populaire."
"Alors que nous marchons dans les rues, les loups appellent Amicus depuis les portes et les fenêtres, et il essaye de les saluer tous."
"Plus haut sur la route, un groupe d'enfants ... des louvetaux se présentent avec des fleurs dans leurs pattes, les distribuant à Amicus et aux triumvirats."
"Alors que je regarde cela se produire, je remarque une enfant particulièrement inégale, pas plus grande que ma taille qui se tient maladroitement sur le côté, me regardant droit alors qu'elle tient une fleur dans ses pattes."
stop music fadeout 10.0
"Je m'arrête, ne sachant pas si elle veut me le donner."
"Quand je le fais, elle se rapproche."
"Alors je me penche, tend la main et ses yeux s'écarquillent, probablement à la fois horrifiés et fascinés d'attirer l'attention de l'extraterrestre fou."
"Néanmoins, elle se rapproche et pousse timidement la fleur froissée et fanée dans mes mains avant de se pencher soudainement et de toucher le côté de son visage contre le mien."
"Pendant un moment, je vois ses yeux larmoyants et injectés de sang."
"Puis je sens la fourrure légèrement humide effleurer ma peau avant qu'elle ne fasse un drôle de jappement et s'enfuie dans la rue."
"Je la regarde, me demandant si j'avais fait quelque chose de mal."
show nef with dissolve
n "\"Tu t'es trouvé un cadeau?\""
"Je regarde la fleur blanche, remarquant qu'il manque plusieurs pétales."
m "\"Je suppose.\""
show nef serious with dis
n "\"Celle-là n'avait pas l'air en bonne santé, n'est-ce pas?\""
m "\"Pas vraiment.\""
n "\"Peut-être que Cassius avait raison sur un point avec son discours.\""
m "\"Je pense qu'ils ont tous deux fait valoir de bons points, honnêtement.\""
"Neferu fait signe à la bande de loups qui s'éloignent de plus en plus de nous."
show nef with dis
n "\"Mieux vaut les rattraper avant qu'ils ne nous laissent derrière.\""
m "\"Ouais.\""
stop music fadeout 5.0
"Je regarde à nouveau la fleur, un peu inquièt maintenant, avant de la laisser tomber sur la route, me sentant un peu coupable."

scene bg cityday with dissolve
"Même si la cérémonie est techniquement terminée, les triumvirats ne semblent pas vouloir laisser Amicus seul."
"Je suis un peu étonné de voir à quel point Amicus gère bien la situation compte tenu de mon agacement grandissant pour celle-ci."
"Amicus essaye de me ramener à ses côtés à quelques reprises, en me montrant des bibelots et des souvenirs qu'il essayer d'expliquer, comme s'il voulait me montrer un peu de culture Adastrane."
"C'est sympa, et je peux dire qu'il veut m'impliquer, mais nous sommes constament coupés par des triumvirats et des habitants qui entrent toutes les cinq secondes pour demander ou dire quelque chose à Amicus."
"J'aurais aimé qu'il puisse leur dire de partir, mais je sais que ça ne marche pas comme ça."
"En plus de ça, mes articulations commencent vraiment à me faire mal à cause de toute la marche et je me demande si vivre dans le palais depuis si longtemps m'a rendu mou."
"Finalement, je suis juste le groupe de loups, parcourant les marchandises après eux."
"C'est intéressant, bien sûr, mais tout est tellement similaire à ce que nous avons sur Terre: des colliers, des boucles d'oreilles, des pinceaux, des vêtements, rien d'époustouflant."
"Finalement, Amicus crie très fort qu'il aimerait aller au restaurant avec son animal de compagnie, si tout le monde pouvait lui permettre de passer."
"Je prends ça comme un signal pour me déplacer à ses côtés et il met immédiatement un bras autour du mien, me tenant près de lui."
"Alors que nous marchons dans la rue (les nombreux loups qui suivent toujours derrière nous), Amicus met son museau près de mon oreille, envoyant un frisson sur mon cou… un qui est étrangement douloureux."
show ami embarrassed with dissolve
a "\"Tout va bien, [mc]? Tu sembles un peu ... mal à l'aise.\""
"Je hausse les épaules."
m "\"Tout ici est nouveau pour moi, alors je suppose que je me sens un peu ailleurs.\""
show ami with dis
a "\"Eh bien, installons-nous dans un restaurant. Nous pouvons nous rafraîchir et reprendre notre souffle là-bas.\""
"Le loup me serre rapidement avec son bras, et malgré mon humeur légèrement aigre, je ne peux pas m'empêcher de sourire un peu."
"Je veux dire, c'est plutôt cool que mon ami soit si populaire ... même si c'est parce qu'il va être le prochain empereur."
hide ami with dissolve
play music "music/lute.ogg"
"Nous entrons dans un petit restaurant confortable, et je peux dire tout de suite qu'il est plutôt haut de gamme avec ses piliers sculptés et les tapisseries fantaisie sur le mur."
"Là encore, tout dans ce quartier est plutôt haut de gamme, je suppose."
"Les triumvirats nous suivent cependant jusque dans le restaurant, et je pousse un soupir frustré."
"Amicus le remarque tout de suite et fait signe à un loup debout derrière un podium."
"Ce loup en particulier nous regarde les yeux écarquillés, apparemment estomaqué de voir le futur empereur apparaître dans son restaurant."
"Il trébuche pratiquement en s'emmêlant les jambes pour nous atteindre, se cognant la hanche sur le côté d'une table."
"Loup" "\"O-o-o-o-oui, votre, euh, votre .... euh, majesté?\""
"Amicus grimace."
a "\"Juste Amicus, s'il vous plaît. Pourriez-vous nous offrir une table isolée, de préférence sans personne assis à côté de nous.\""
"\"Bien sûr!\""
"Le loup trébuche à nouveau sur lui-même avant de nous conduire dans un coin du restaurant, en désignant une table là-bas."
"Il se tourne alors vers un couple à côté de la table et commence à siffler frénétiquement après eux pour qu'ils bougent."
"Ils le regardent avec étonnement jusqu'à ce qu'Amicus intervienne pour l'arrêter."
a "\"Tout va bien, juste euh, ne laissez personne de ... ce groupe là-bas s'asseoir à côté de nous, si c'est possible?\""
"Amicus secoue la tête en direction du troupeau de vieux loups, tous nous regardant d'un air plutôt belliqueux."
"\"Oh oui bien sûr!\""
"Il se précipite vers ledit groupe et nous sommes enfin capables de nous asseoir ... ou de nous allonger."
stop music fadeout 5.0
"Les sièges sont bien sûr de style romain."
"Amicus s'installe avec un énorme soupir, étirant son grand corps sur le lit."
scene dinner1 with slow_dissolve
a "\"Désolé pour ça. J'aurais dû t'avertir à quel point ... cela peut être frustrant avec tous les bavardages inutiles.\""
play music "music/dawn.ogg" fadein 3.0
"Je hausse les épaules."
m "\"Ça semble convenir à la politique.\""
a "\"Oh, c'est vrai, mais ne t'inquiètes pas, il est rare que tous les triumvirats soient dans la ville en même temps. C'est pour les Épréuves, bien sûr.\""
m "\"Ouais, ça a du sens.\""
a "\"Tu es sûr que tu vas bien? Je n'arrive jamais à le deviner avec toi.\""
m "\"Je vais bien.\""
"Je frotte mes bras, la peau est sensible et douloureuse, tout comme mes articulations."
"Je me demande si j'ai aussi attrapé un coup de soleil."
a "\"Très bien ... alors que penses-tu de la ville? Cette partie du moins. J'aimerais pouvoir t'emmener là où se trouvent les grattes-ciel, mais comme je l'ai dit, les choses sont un peu chaotiques en ce moment.\""
m "\"C'est plutôt cool. Ce ne serait pas improbable sur Terre, définitivement différent, mais vraiment similaire.\""
a "\"Ah, eh bien, vous avez été élevé par nous après tout.\""
m "\"... Ouais. Alors, c'est ce que tu vas faire en tant qu'empereur? Venir en ville et juste ... parler?\""
"Amicus rit."
a "\"Oh, il y en aura beaucoup plus, j'en suis sûr. J'espère que Cato m'apprendra un peu ... s'il parvient à se remettre de l'épreuve.\""
"Je me souviens que Cato a voté pour Cassius."
"Il est probablement furieux à ce sujet en ce moment."
m "\"Tu auras des conseillers ?\""
a "\"Eh bien, oui, mais je dois les choisir.\""
m "\"Tu choisiras Cato?\""
a "\"Je pourrais.\""
m "\"Mais le veux-tu?\""
a "\"Eh bien ... peut-être, mais les événements récents m'ont laissé un peu incertain à ce sujet.\""
m "\"Pourquoi ça?\""
"Amicus secoue la tête."
a "\"Ne t'en fais pas pour ça maintenant, nous devrions faire la fête.\""
m "\"Je veux dire, tu pourrais devenir empereur à tout moment. Tu ne devrais pas avoir quelqu'un qui a une bonne tête sur les épaules au début?\""
a "\"Heh, je suppose. Qui suggéreres-tu?\""
"J'ai le sentiment qu'il m'incite à me proposer, mais ce ne sera certainement pas le cas."
"Les quelques loups que je connais rendent la décision assez facile."
m "\"Virginia.\""
"Amicus hausse les sourcils avec une légère surprise."
a "\"Oh ... eh bien, oui, je la considérerais certainement. Le seul problème est l'image d'une femme qui me dit ce que je fais. La réputation de {i}leveur de queue{/i} est déjà assez mauvaise comme ça.\""
"Je roule des yeux."
m "\"Peut-être que le machisme des loups est une chose que tu pourrais régler pendant que tu es empereur?\""
"Amicus ne semble pas savoir comment répondre à ça, mais il n'est pas obligé de le faire car notre nourriture arrive."
"Je suis un peu surpris car nous n'avons pas commandé, mais en regardant autour de vous, il semble que tout le monde obtient la même chose."
scene dinner2 with dissolve
"Il y a les habituelles olives, des raisins, du fromage et du pain, mais aussi des fruits de mer et même des œufs ce qui me surprend."
"Amicus remercie le serveur nerveux avant de commencer immédiatement à manger."
"Je fais la même chose, mais pendant que j'étale du fromage sur le pain, mon esprit revient sur ce qui pourrait se passer dans la ville en ce moment."
m "\"Alors ... à quel point les choses sont-elles mauvaises dans la ville? Personne ne semble s’inquiéter à ce sujet.\""
a "\"D'après ce qu'on m'a dit, c'est assez léger. Les émeutes sont courantes à Adastra, mais elles ne durent pas longtemps. Je pense que les gens vont se calmer dans les prochains jours.\""
m "\"Oh, d'accord. Donc ce n'est pas comme si ... ils ne t'aimaient pas, ou quelque chose du genre?\""
"Il faut un moment à Amicus pour avaler sa bouchée de pain avant de parler."
a "\"Non, non, la plus grande partie de la colère est dirigée contre les triumvirats. Je dirai cependant que j'ai du pain sur la planche pour reconstruire ma réputation.\""
m "\"A cause de la sextape?\""
a "\"Heh ... oui.\""
"Amicus essaye de sourire avec légèreté, mais je peux voir ses oreilles devenir rouges."
"Ça doit être bizarre d'être dehors en public comme ça, sachant que tout le monde l'a vu."
a "\"L'un des triumvirats de Lux m'a dit de simplement dire que c'était faux ... je ne sais pas si ça fonctionnera.\""
m "\"Ça pourrait être une bonne idée.\""
a "\"Vraiment, le plus gros problème c'est que ça délégitime le projet d'alliance avec les Khemians. Les gens croiront que je suis redevable à Neferu d'une manière ou d'une autre.\""
"L'expression d'Amicus tombe finalement un peu, fixant la nourriture alors que son grignotage ralentit."
scene dinner3 with dissolve
m "\"Je suis sûr qu'ils s'en remettront. D'après ce qu'on m'a dit, il semble qu'ils oublient vite.\""
a "\"Eh bien oui, dès que le prochain scandale surviendra, j'espère que celui-ci ne m'impliquera pas.\""
m "\"Ouais.\""
"Nous mangeons en silence un moment, et je peux dire que quelque chose de lourd est dans l'esprit d'Amicus."
"En attendant, je suis un peu distrait par des démangeaisons sur des points spécifiques de mes bras, je sens de minuscules petites bosses sur la peau."
"Je me demande si je suis allergique à quelque chose, alors j'arrête de manger pour le moment, choisissant plutôt de me détendre sur le lit."
a "\"[mc], je voulais te demander quelque chose.\""
m "\"Ouais?\""
a "\"Veux-tu ... veux-tu rester ici, même après que je sois devenu empereur?\""
"La question me surprend, et il ne me reste plus qu'à essayer de rassembler mes pensées pendant un moment alors qu'Amicus continue de baisser les yeux."
m "\"Euh, qu'est ce que tu veux dire?\""
"Amicus soupire et me regarde."
a "\"Je veux dire, veux-tu rester ici avec moi, même si tu as la possibilité de rentrer chez toi?\""
"Amicus baisse rapidement les yeux."
a "\"Je suis désolé, je sais que ce n'est pas à moi de demander, mais ... j'ai pensé que je ferais mieux de demander.\""
"Je le regarde un instant, puis je baisse les yeux aussi."
m "\"Tu sais que je dois y retourner. Je dois au moins je dois faire savoir à mes amis et à ma famille que je vais bien. Je sais qu'ils me cherchent en Italie en ce moment ... probablement dans toute l'Europe à ce stade. Je dois leur faire savoir.\""
"Amicus tousse à la hâte."
a "\"Bien sûr.\""
m "\"Mais ... cela ne veut pas dire que je ne veux pas revenir. Car j'aimerais revenir. Je sais juste que c'est ... qu'il y a des problèmes.\""
"Je baisse la voix en me rappelant que nous sommes dans un lieu public et que mentionner un premier contact illégal ne serait pas une bonne idée."
m "\"Si nous pouvons résoudre les problèmes, honnêtement ... j'aimerais revenir et rester longtemps.\""
"Je me surprends un peu avec cette déclaration, mais c'est vrai."
"Amicus me regarde avec surprise."
a "\"Vraiment?\""
m "\"Ouais, si ce n'était pas un risque pour ton empire.\""
a "\"Bien sûr. Je vais parler aux parents dès que possible. Je suis sûr ... Je suis certain que nous pouvons trouver quelque chose.\""
"Le regard sur le visage d'Amicus en ce moment est si triste, mais j'y vois aussi de l'espoir. Ça me rappelle quelque chose que je voulais faire depuis la semaine dernière."
m "\"Hey Amicus?\""
a "\"Ouais?\""
"Je jette un coup d'œil autour de moi rapidement, m'assurant que les clients à proximité n'écoutent pas."
m "\"Tu veux sortir avec moi?\""
"La déclaration, si ridicule, si idiote dans cette situation, sort toute silencieuse et faible, mais je ne sais pas comment le demander autrement."
"Ces mots sont tellement compliqués entre nous maintenant avec la façon dont j'ai essayé de l'expliquer à Amicus."
"C'est quelque chose que je ne pense pas avoir jamais dit à personne auparavant, et tout comme Amicus, je me retrouve immédiatement à regarder vers le bas."
"C'est calme pendant un moment, et le restaurant s'illumine soudainement avec une teinte dorée alors que le coucher de soleil frappe les fenêtres juste à droite."
"J'entends une longue expiration et je me rends compte que le loup retenait son souffle."
"Je lève les yeux alors et vois Amicus me sourire."
scene dinner4 with dissolve
"Il y a un mélange de bonheur et de soulagement sur son visage, peut-être même un peu d'amusement."
"Je suppose que nous tournons autour du pot depuis si longtemps, nous savions tous les deux maintenant que c'est ce que nous voulions, ce que nous avons construit."
a "\"Bien sûr, [mc]. J'en serais honoré.\""
"Je vois ses yeux scintiller un peu, et je veux me lever tout de suite pour le rejoindre sur son lit, mais le cadre public me retient."
"J'imagine qu'Amicus ressent la même chose, et je me demande si le lui demander ici en public n'était pas le meilleur endroit pour ça."
"Mais c'était fait, et je me sens sourire malgré moi."
"Le loup sourit tout de suite."
m "\"Comme tu l'as dit, pendant que je suis ici, nous ferions aussi bien de mieux nous connaître ... et si tu trouves une solution à notre problème, je pourrais revenir.\""
"Amicus hoche la tête et la tourne de manière à pouvoir essuyer un œil sur son épaule, espérant probablement que je ne le remarquerais pas."
"Il a l'air tellement soulagé, je me rends compte que même après que nous nous soyons réconciliés dans la salle de médiation, il n'était plus certain de notre situation amoureuse."
m "\"Mais ... il y a des limites, et si je sors avec toi, tu dois tout me dire ... et ne pas coucher dans mon dos.\""
a "\"Bien sûr. J'ai promis de tout te dire, en particulier tout ce qui te concerne, et je n'ai pas l'intention de rompre cette promesse.\""
m "\"Et coucher avec d'autres hommes?\""
"Les oreilles d'Amicus se rabaissent et il jette un coup d'œil à nos voisins qui essayent DÉFINITIVEMENT d'écouter."
"Il baisse beaucoup la voix."
a "\"Certainement pas, pas que je n'ai personne avec qui le faire ... mais nous pourrons discuter de tout cela quand nous rentrerons dans notre chambre ... et—\""
"Amicus baisse encore plus la voix."
a "\"Peut-être en faire un peu plus?\""
"Ses oreilles s'aplatissent quand je roule des yeux, mais elles remontent quand je souris."
"\"Bien sûr.\""
"Immédiatement, sa queue commence à frapper le lit, et le regard impatient sur son visage me fait secouer la tête."
"Je ne peux pas nier que je suis excité aussi ... en fait, je me sens un peu nerveux maintenant que je viens de lui promettre ça."
"Comment pourrions-nous même commencer?"
stop music fadeout 5.0
"Nous restons assis ensemble un peu plus longtemps, la conversation se déplaçant vers des sujets plus informels comme la répartition des quartiers de la ville."
"Bien qu'une heure passe, je commence à avoir chaud et je me sens un peu étourdi, et quand j'en parle à Amicus, il suggère que nous retournions au palais."
scene bg citynight with fade
play music "sfx/crickets.ogg" fadein 3.0
"Vita a complètement disparu au moment où nous nous dirigeons vers la voiture."
"Bien sûr, plusieurs délégués nous entourent alors que nous commençons à partir, mais Amicus promet qu'il ne restera que dix minutes et je me dirige seul dans la rue pour me tenir à côté du char."
"C'est un peu plus agréable ici en plein air que dans le restaurant étouffant."
"Je peux dire maintenant que je suis définitivement en train de tomber malade, et toute cette douleur et cet épuisement n'étaient que le début d'une fièvre grimpante que je peux sentir traverser ma peau."
"Je finis par m'asseoir sur le marchepied de la voiture, la tête baissée alors que je me sens commencer à transpirer."
"Ce n'est pas quelque chose que je n'ai jamais ressenti auparavant, mais il y a une étrange sensation de picotement sous tout cela, comme des épingles et des aiguilles juste sous ma peau, me laissant envie de démanger à différents endroits de mon corps."
"Je souhaite juste qu'Amicus se dépêche ... les autres aussi, puisque je suis le seul à rester ici."
"Je ne me souviens même pas où Neferu et Virginia sont allés ... quelque part pour faire du shopping, je pense."
c "\"Simien ...\""
"La voix de Cassius est basse et silencieuse à ma gauche, et je jette un coup d'œil pour le voir se pencher nonchalamment contre le char."
"Je tente sans enthousiasme de m'incliner devant lui, faisant en quelque sorte simplement basculer la tête dans sa direction."
"Le loup me regarde avant de marcher vers moi."
show cas annoyed with dissolve
c "\"A quel jeu joues-tu?\""
"C'est probablement le pire moment pour que cela se produise."
m "\"Jeu?\""
"Je marmonne stupidement, regardant vers le restaurant pour voir si je peux voir Amicus à travers la foule rassemblée devant."
show cas angry with dis
c "\"Ne fais pas semblant d'être stupide. Je sais que tu es capable de comprendre.\""
"Je secoue juste la tête, mais je le regrette immédiatement car je sens toute la nourriture que je viens de manger me gambader dans l'estomac."
"Je suis vraiment malade, bien plus que je ne l'avais réalisé et je ne peux pas croire à quel point ça me frappe fort et vite."
show cas annoyed with dis
c "\"Tu te souviens il y a plusieurs semaines de cela, tu m'as servi pendant le déjeuner? Virginia et Neferu étaient là ...\""
"Je reste juste au silence maintenant, inquiet que bouger du tout me fasse vomir."
c "\"Bien sûr que tu t'en souviens. Tu as dit aux triumvirats ce que j'avais l'intention de faire, n'est-ce pas?\""
"Cassius se rapproche, mais les sensations qui parcourent mon corps me préoccupent tellement que je ne me soucis plus de lui en ce moment."
"J'ai besoin d'aller voir Amicus, je dois lui dire que quelque chose ne va pas."
"Je serre mes bras autour de moi, sentant cette sensation de picotement faire irruption à la surface, la peau sur mes bras, ma poitrine et mes jambes brûle et me démange de la manière la plus horrible."
"Je suis halètant."
show cas paw annoyed with dis
c "\"Qu'est-ce que c'est, une sorte de langue simienne? Écoute-moi. Je veux savoir ce que tu leur as dit ... et comment tu as su leur dire.\""
"Je sens des bosses sur mes bras… des bosses qui n'étaient pas là il y a quelques minutes."
"Je regarde en bas et même s'il est difficile de voir dans l'obscurité, je suis au moins capable de voir que ma peau est tachée et décolorée."
"En tremblant, je touche l'une des taches et regarde comme une larme de liquide clair suinte."
"C'est quoi ce bordel?"
"Quelque chose attrape le devant de mes robes et me tire vers le haut."
show cas furious with dis
c "\" Tu m'écoutes, animal? J'ai dis-\""
"Je m'inquiétais des petits mouvements, mais cette énorme embardée pousse mon estomac par-dessus bord et je vomis directement au milieu du torse de Cassius."
show cas surprised with dis
"Nous regardons tous les deux sa fourrure souillée qui commence à couler lourdement sur ses vêtements."
show cas scared with dis
c "\"Oh ... oh dieux .... OH DIEUX!\""
"Le loup hurle et en même temps, je vomis à nouveau, au même endroit."
hide cas with dissolve
"Cassius trébuche immédiatement en arrière, hurlant alors qu'il agite ses pattes inutilement sur les restes de mon diner... puis il commence à des haut-le-coeur."
"Je ne peux pas voir s'il vomit aussi."
"Au lieu de cela, je m'effondre pour m'asseoir sur le sol, sentant le monde tourner autour de moi."
"Heureusement, la prochaine chose que j'entends est la voix d'Amicus."
"On dirait que ça vient de très loin, même si je peux dire qu'il est accroupi juste à côté de moi."
show ami angry teeth with dissolve
a "\"Qu'est ce que tu lui as FAIT, Cassius!?\""
c "\"Je n'ai rien fait! Il ... il ... HUUURGH!\""
"J'entends des bruits éclaboussants."
show ami embarrassed with dis
a "\" [mc], que s'est-il passé? Qu'est-ce qui ne va pas?\""
"Je me balance et Amicus me laisse me pencher contre lui malgré mes robes couvertes de vomi."
m "\"Je ne ... je ne sais pas ...\""
a "\" Était-ce la nourriture? Es-tu-\""
"Je tends un bras et je sens le loup l'attraper délicatement, l'examinant."
a "\"Dieux ...\""
"Il marmonne dans un souffle."
v "\"Que - que s'est-il passé? Cassius?\""
hide ami with dissolve
"J'entends plus de pas et pour une raison quelconque, je me sens gêné que tout le monde me voit comme ça."
c "\"Ce barbare ... urgh ... il a vomi sur moi!\""
"On dirait que Cassius est sur le point de pleurer, et pour une raison quelconque, je trouve ça assez drôle à ce moment là."
"J'essaye de rire, mais j'ai tellement mal à la gorge…»"
a "\"Virginia ... il est malade.\""
n "\"Nous devons le ramener au palais. Montez dans la voiture.\""
a "\"C'est trop lent!\""
"Je sens le monde s'incliner alors que je semble juste léviter du sol ... puis je me rends compte qu'Amicus m'a ramassé."
v "\"Les Praetors ont des véhicules beaucoup plus rapides. Nous pourrions en obtenir un.\""
a "\"[mc]?\""
stop music fadeout 3.0
"J'entends sa voix mais pour une raison quelconque, je ne peux pas répondre ... c'est comme un rêve."
a "\"Il n'y a pas de temps, j'y vais en courant.\""
v "\"Amicus!\""

scene bg black with slow_dissolve
play music "music/between dimensions.ogg" fadein 3.0
"Je sens mon corps rebondir de haut en bas, jeté à gauche et à droite."
"C'est comme si j'étais dans une sorte de manège à sensations fortes."
"Je tends la main dans l'obscurité pour l'arrêter d'une manière ou d'une autre, mais tout ce que je ressens est quelque chose de velu et de chaud."
"Tout fait mal et démange en même temps."
m "\"Qu'est-ce que... c'est?\""
a "\" [mc] !? Hé, reste avec moi! Je suis ici.\""
"Qui?"
"Je force mes yeux à s'ouvrir, même s'ils brûlent tellement."
scene bg forestnight with slow_dissolve
"Je regarde les choses noueuses au-dessus de moi, et je me demande ce qu'elles sont."
"Tout ce qui me vient à l'esprit, ce sont des mains osseuses et sans peau qui s'étirent vers le ciel."
a "\"Tu peux m'entendre?\""
"Il y a une voix essoufflée et sifflante au-dessus de moi alors que l'horrible et rebondissant trajet continue."
"Je veux juste dormir."
"Il y a un autre son ... un bourdonnement étrange et le tremblement de terre s'arrête enfin."
n "\"Amicus! Monte, imbécile!\""
a "\"Neferu ... il a des convulsions ... il a des pustules sur tout le corps ...\""
"La voix au-dessus de moi sanglote et halète et je veux tendre la main et mettre une main sur sa bouche pour qu'elle se taise, que je puisse dormir."
n "\" Calme toi, Virginia a fait venir un médecin par vaisseau dans le palais. Tu dois...\""
scene bg black with slow_dissolve
"Tout redevient paisible."
"Je flotte à travers un vide de nuages ​​silencieux, doux et noirs qui me chatouillent et mordillent ma peau."
"Ça me démange, et je veux me démanger, mais quelque chose semble me retenir ..."
scene bg bedroom with slow_dissolve
"J'ouvre les yeux lentement, regardant le plafond."
"Je commence à être vraiment agacé de ne pas pouvoir m'endormir."
"J'ai tellement de choses à faire demain ... Nous partons en voyage à Naples, je pense, pour essayer l'authentique pizza italienne."
"Je vais passer un moment terrible si je ne dors pas au moins un peu ..."
"Je réalise que je ne peux pas bouger."
"Une peur glaciale me saisit la poitrine, et en même temps, je vois quelque chose de grand grimper le long du mur."
"Une araignée géante grimpe vers le haut, ses mouvements sont étranges, comme une marionnette tirée par des fils."
"Elle se déplace à travers le plafond, et même si elle a la taille d'un crabe géant, je ne peux pas ... bouger ... du ... tout. \" "
"\"{i} Les arachnides adastran sont d'une taille inquiétante ... {/ i}\""
"Je serre les dents alors qu'elle s'arrête au-dessus de ma tête ... puis tombe droit sur mon visage, les jambes en éventail ..."
scene bg amicusroom
m "\"ARRÊTEZ!\""
"Je la repousse, je sens toutes ses pattes qui me pressent le visage."
"\"Je vous ai dit de le maintenir!\""
a "\"J'essaye! [mc], écoute-moi, s'il te plaît! Tu es en sécurité, nous t'aidons!\""
"Je me concentre sur les monstres au-dessus de moi, leurs énormes dents blanches et leurs yeux rouges et brillants."
"Leurs horribles mains descendent pour m'attrapper, et je sens une douleur piquante sur toute ma peau."
"Je me débat, mais ça ne sert à rien, ils sont trop forts ..."
unk "\"Il a une autre crise ...\""
scene bg black with slow_dissolve
"Je m'appuie contre le côté d'un immeuble sur la route déserte."
scene bg citynight with slow_dissolve
"La nuit est paisible et calme ... surtout calme, j'entends des claquements au loin ... des sons de chevaux au galop."
"Je fronce les sourcils et me penche un peu en avant, regardant la route sombre."
"Je vois un cheval courir vers moi, ses yeux rougeoient et crachent des mouches de sa bouche."
"Appeuré, je me presse plus près du bâtiment, mais le cheval m'ignore."
"Au lieu de cela, alors qu'il passe devant moi, je vois qu'il' traîne quelque chose ..."
"Un corps sans tête de loup, les bras écartés, la souche laissant une longue traînée rouge sur les pavés."
"J'ouvre la bouche pour crier ..."
scene bg amicusroomdim with slow_dissolve
"\"Nous n'avons rien d'enregistré pour son espèce.\""
a "\"Alors profilez-le.\""
"\"Y a-t-il une raison pour laquelle nous n'avons aucune données?\""
a "\"Juste, guérissez-le ... s'il vous plaît. C'est juste l'avia pox ...\""
"\"Eh bien, clairement, cela a un effet différent sur son espèce. Son système nerveux est déjà irrémédiablement endommagé. Vous devriez considérer ...\""
scene bg black with slow_dissolve
"..."
scene bg space with slow_dissolve
unk "\"Les choses ne semblent jamais se dérouler comme prévu, n'est-ce pas?\""
"..."
unk "\"Je suis désolé que tu ais dû faire cette expérience... Je ne l'avais pas prévu.\""
scene watching with slow_dissolve
unk "\"Ne t'inquiétes pas ... tu es toujours sur la bonne voie.\""
unk "\"Tu pourras terminer cette tâche.\""
unk "\"J'ai juste besoin d'un peu de temps\""

jump a2s1