label a1s7:
scene bg throneroom with fade
"Je suis Neferu jusqu'à la salle du trône, l'espace caverneux aussi vide qu'il l'était lors du premier procès."
"Comme lors du premier essai, quelques-uns des habitués du palais sont assis sur les bancs; Virginia sur le côté gauche de la pièce, tandis qu'Alex est assis sur la droite."
"Le chat est assis seul, il a l'air minuscule par rapport au reste de la pièce, sa queue parfaitement enroulée sous ses pattes sur ses genoux."
"Il sourit quand il me voit, et je fais comme pour aller m'asseoir à côté de lui ... mais c'est là que le chacal me prend la main."
"Je fais une pause et je vois le regard curieux d'Alex avant de me tourner vers Neferu."
m "\"Quoi?\""
show nef sidetalk f with dissolve
n "\"Pourquoi ne donnons-nous pas de la compagnie à Virginia?\""
show nef sidesmile f with dis
"Le chacal me sourit doucement, une de ses oreilles bougeant en direction de la louve."
m "\"Euh, vous pouvez. J'allais m'asseoir avec Alex.\""
"L'expression de Neferu ne change pas, mais il ne lâche pas non plus, et sa voix prend un ton doux mais inquiétant, me mettant un peu mal à l'aise."
show nef sidetalk f with dis
n "\"En fonction du déroulement de cet essai, il se peut que nous ayons des affaires à régler avant qu'il ne se termine officiellement. Il vaudrait mieux que vous soyez proche de moi.\""
"C'est alors que je réalise ce qu'il veut."
"Bien que je ne sache pas quel est le processus pour devenir \"l'animal de compagnie\"de Neferu, j'imagine que cela implique une sorte de travail officiel, comme signer quelque chose."
hide nef with dissolve
"Alors, je fronce les sourcils à Alex et hausse les épaules, faisant un geste vers le chacal."
"Le chat continue d'avoir l'air confus alors que je me détourne et suis Neferu jusqu'aux bancs de l'autre côté de la pièce."
play background "music/memories.ogg" fadein 5.0
show vir at left with dissolve
v "\"Neferu.\""
"Virginia s'assoit délicatement sur le banc, une jambe élégamment croisée sur l'autre alors qu'elle tient une patte, que le chacal embrasse."
show nef a at right with dissolve
n "\"Bonne journée à vous, Virginie.\""
"Même si j'essaye de rester derrière Neferu, Virginia regarde autour du côté musclé du chacal pour me regarder droit."
show vir tilt with dis
v "\"Je vois que vous avez amené un invité.\""
"Elle tend à nouveau sa patte, et il me faut un moment pour réaliser que je devrais l'embrasser."
"J'ai commencé cette tendance après tout."
show nef with dis
n "\"En effet. Amicus a demandé que je lui tienne compagnie pendant le procès.\""
"En sortant du baiser de la patte, je vois Virginia froncer les sourcils."
show vir serious with dis
v "\"Mon frère ne devrait pas vous accabler d'une corvée idiote comme celle-là. L'animal est capable de rester dans sa chambre, j'imagine.\""
show nef a with dis
n "\"C'était un accord mutuel. De plus, il est plutôt en bonne compagnie une fois que vous apprenez à le connaître.\""
v "\"Oh vraiment? Il semble que notre petit simien soit plein de surprises.\""
"La louve me regarde d'un œil pointu, et je n'ai pas beaucoup de temps pour me demander de quoi elle parle avant que Neferu ne s'assoie à côté d'elle, me tirant à ses côtés pour m'asseoir à côté de lui."
show nef f with dis
n "\"Ce serait une observation précise.\""
"Il y a une pause momentanée avant de voir Virginia se pencher un peu du coin de l'œil."
"Quand elle parle à nouveau, sa voix est basse."
show vir sad p with dis
v "\"Les rumeurs sont donc vraies?\""
"Il y a une autre pause, cette fois de Neferu."
show nef serious with dis
n "\"Je ne crois pas être en mesure de spéculer là-dessus. Ce n'est pas à moi de m'impliquer dans la politique des loups.\""
show vir smile p
"Virginia rit doucement, un qui semble complètement faux."
v "\"Je ne suis pas un imbécile, Neferu. J'apprécie peut-être vos tactiques suaves, mais je préfère que vous ne les utilisiez pas contre moi.\""
show nef sad with dis
n "\"Je ne rêverais pas d'une telle chose, Virginie.\""
show vir tilt with dis
v "\"Sûrement.\""
"Virginia change de nouveau et maintenant je sais avec certitude qu'elle me regarde directement."
v "\"Alors ... je suppose qu'il comprend ce que nous disons, alors?\""
show nef f with dis
n "\"Eh bien, il est intelligent, et il possède un lingua.\""
show vir serious with dis
v "\"Je veux dire, il {i} nous comprend {/ i}.\""
"Virginia met encore plus l'accent sur le mot."
"Je vois Neferu regardant le sol, toujours souriant, bien que ses pattes semblent se serrer un peu plus que d'habitude."
show nef a with dis
n "\"Vous le sauriez mieux que moi, étant un loup. Nos enfants sont aussi intelligents que nous, alors je suis habitué à une telle idée.\""
show vir smile with dis
v "\"Ne feignez pas l'ignorance, Neferu. Vous avez été beaucoup plus près de lui que moi. C'est une question simple, à laquelle vous devriez répondre honnêtement, sinon dois-je supposer que vous avez amené un petit espion à notre conversation?\""
"Bien que les mots semblent durs et dangereux, le ton de Virginia est léger et Neferu rit."
show nef smile with dis
n "\"Vous m'accusez de tromperie, mais nous savons tous les deux que vous avez déjà trouvé la réponse. Pourquoi {i} vous {/ i} feignez l'ignorance?\""
"Le loup s'évente avec un air de nonchalance."
show vir serious with dis
v "\"C'est la meilleure arme du discours ... et il est facile de feindre la stupidité, du moins pour moi. Il est attendu de ma part.\""
show nef sad with dis
n "\"Et pourquoi diriez-vous quelque chose comme ça?\""
show vir talking p with dis
v "\"J'ai un vagin, Neferu.\""
show nef smile eyes a with dis
"Il me faut un moment pour absorber ce que Virginia vient de dire, mais Neferu rit déjà avec ce qui est probablement le premier vrai rire de la conversation."
"Je vois Alex nous regarder à nouveau, et cette fois, il semble que ses yeux se sont un peu plissés."
"Il faut quelques secondes au chacal pour reprendre le contrôle alors que Virginia continue de faire signe à son éventail, l'air plutôt contente d'elle-même."
show nef smile eyes with dis
n "\"Désolé, je ne suis pas habitué à la franchise ici.\""
show vir with dis
v "\"Il n'est pas impossible pour nous d'être franc sur cette lune, Neferu, surtout entre amis.\""
"Je remarque que le loup me regarde à nouveau, et encore une fois, je baisse les yeux."
v "\"Quoi qu'il en soit, il semble que nous ayons fait une erreur en oubliant Simia. Je devrai peut-être faire mes propres recherches dans les archives. Amicus savait clairement quelque chose que nous ne savions pas.\""
"Recherche?"
"Je sens mon estomac tomber."
"Bien qu'Amicus m'ait assuré des choses, je ne sais même pas si je ressemble vraiment à un Simian."
"Tout ce qu'il faudrait, c'est une photo pour savoir que je ne suis pas vraiment de Simia."
hide vir
hide nef
with dissolve
play sound "sfx/dooropen.ogg"
stop background fadeout 10.0
"J'essaye de chasser cette pensée de mon esprit pour l'instant alors que les portes s'ouvrent soudainement et que Cato entre, se dirigeant rapidement vers le trône."
"Virginia me quitte enfin des yeux, et je ne peux qu'espérer qu'elle ne suivra pas ses plans de recherche."
"La salle du trône est si silencieuse que j'entends le vieux loup grogner alors qu'il monte les escaliers avant de se tourner vers nous."
"Après quelques secondes, il s'assied, son corps lourd et musclé un peu affalé sur son siège, nous regardant à travers sa visière."
"Quelques instants de plus passent en silence, et juste au moment où je me demande si le procès va commencer, j'entends un léger vrombissement mécanique alors que le panneau du plafond s'ouvre."
"Une douzaine de drones caméra dérivent paresseusement, se déployant dans les airs pour se positionner à divers endroits dans la pièce."
"L'un d'eux flotte vers nous et plane juste au-dessus de nos têtes, l'objectif semblant se concentrer sur mon visage."
"Je baisse encore la tête, l'action étant devenue une seconde nature depuis que j'ai atterri sur cette lune."
"Neferu me donne un coup de coude cependant."
n "\"Viens maintenant. Amicus vous a amené ici pour être vu.\""
"Son ton est léger comme toujours, mais je sens qu'il ne dit pas ça juste pour me taquiner."
"Nous jouons tous un rôle ici, et mon rôle est de donner une belle allure à Amicus, de montrer aux triumvirates qu'il s'est donné beaucoup de mal pour obtenir un animal exotique, fascinant et extraterrestre."
"Je n'aimerais peut-être pas ça, mais ça n'a pas d'importance pour le moment, alors je lève la tête."
"Au lieu du regard muet et vide que j'utilisais ce mois-ci, je pars avec un visage complètement impassible."
n "\"Regardez la lumière rouge sur le dessus du drone. Lorsqu'il devient vert, sachez que vous êtes en cours de diffusion.\""
com "\"Le deuxième essai commencera dans dix secondes.\""
scene bg throneroomdark with dissolve
"Avec ça, les lumières s'assombrissent lentement et tout devient complètement silencieux."
"Je suis juste assis là, regardant vers le trône, Caton assis aussi immobile qu'une ancienne sculpture romaine."
play sound "sfx/dooropen.ogg"
"Ensuite, les portes s'ouvrent et nous regardons tous par-dessus, y compris les caméras."
show ami at left
show cas at right
with dissolve
"Dans la promenade Amicus et Cassius, côte à côte."
"Ils ont dû attendre l'un à côté de l'autre, tout comme Alex et moi l'avions été avant le deuxième procès."
"Je dois me demander ce que ça a dû être."
"Sans un mot, ils marchent tous les deux dans l'allée large et moquette, synchronisés l'un avec l'autre."
"Je regarde attentivement Amicus alors qu'il passe, juste au cas où il me regarderait et je pourrais lui faire un sourire encourageant."
"Il regarde droit devant lui cependant, une expression plus sérieuse sur son visage que je n'ai jamais vu."
"Tout reste silencieux, le seul son étant le battement étouffé de leurs pieds rembourrés et de leurs griffes sur le tapis."
"Une fois qu'ils ont atteint le pied des escaliers, ils s'arrêtent avant de s'incliner tous les deux profondément devant Caton."
"Cela dure quelques secondes avant que Cato ne change finalement de nouveau, brisant l'illusion qu'il était fait de pierre."
ca "\" Très bien. Vous pouvez continuer.\""
hide smie
hide cas
hide ami
with dissolve
"Sur ce, les deux frères se redressent avant de monter les marches, se séparant pour se mettre de chaque côté de l'empereur par intérim."
"Ils se retournent et nous font face, tous deux au garde-à-vous, les bras tendus à leurs côtés."
"Un drone lévite du plafond et s'arrête doucement en l'air devant Cato."
"Je remarque que la minuscule lumière rouge sur le dessus du drone devient verte, et le vieux loup fixe ses yeux sur la caméra."
ca "\"Bienvenue au procès de la rhétorique.\""
ca "\"La rhétorique a longtemps été un aliment de base de la civilisation Wolven et l'un de nos plus grands atouts.\""
ca "\"Bien que connus pour notre force et notre ténacité, nous le sommes aussi pour notre utilisation des mots dans les négociations.\""
"Neferu renifle à côté de moi, assez fort pour que je me demande si Cato a pu l'entendre."
"J'espère que non."
ca "\"C'est pourquoi il est non seulement important d'honorer l'art et l'histoire du débat d'aujourd'hui, mais aussi de prouver notre capacité à bien les utiliser.\""
ca "\"Être un rhéteur compétent est essentiel pour être un empereur compétent.\""
ca "\"Souvenez-vous des règles; vous aurez la parole pendant vingt minutes. Ne faites pas référence à votre challenger. Maintenant, Amicus—\""
"Je vois la moindre contraction dans le cadre d'Amicus alors qu'il continue de regarder devant lui."
a "\"Oui, empereur?\""
ca "\"S'il vous plaît, honorez Adastra et passez à la salle. Proposez vos politiques à travers l'art de la parole.\""
"Il y a une légère pause, puis Amicus descend les escaliers."
"S'il est nerveux, ce que je sais qu'il est, il ne le montre pas du tout, ses mouvements sont calmes et réservés."
"Il fait plusieurs pas en avant, s'éloigne des escaliers pour se tenir au milieu de l'allée, juste légèrement devant moi."
show ami serious with dissolve
"Il est si proche, et j'aurais aimé pouvoir juste dire quelque chose, me lever et lui faire un câlin et lui dire qu'il va faire du bien."
"Mais je sais que le temps est passé, que le moment où tout s'est construit vient d'arriver."
"C'est une sensation étrange de regarder quelque chose qui va avoir un impact énorme sur votre vie, mais de ne pas pouvoir participer du tout."
"Je ne peux qu'espérer qu'Amicus est prêt."
play music "music/reveal2.ogg"
show ami talking with dis
"Il commence à parler, et quand il le fait, ce n'est pas comme sa voix habituelle."
"Au lieu de cela, c'est plus profond, plus large, plus sonore, je suppose."
"En fait, c'est plus proche du chant humain."
a "\"Il y a vingt millénaires, nous avons été choisis par les Romanus.\""
a "\"Sur mille espèces, ils nous ont choisis, et n'était-ce pas pour une raison?\""
"Il bouge beaucoup ses bras et ses pattes aussi, en larges mouvements de balayage."
"Ce n'est pas différent de la danse, bien qu'il reste la plupart du temps au même endroit."
a "\"Il y a quinze millénaires, nous les avons rejetés, nous sommes devenus le premier frère abandonné, et notre empire est entré dans un déclin comme nous n'avions jamais vu auparavant; fermer les relations avec les frères et sœurs, perdre des enfants, perdre des ressources—\""
"Un drone flotte autour de son corps, et je peux dire qu'il joue la performance, faisant des gestes dramatiques avec des expressions trop exagérées."
"Je me rends compte que c'est comme si je regardais ces drames que j'ai vus à la télévision Adastran."
a "\"- Nous sommes tombés longtemps et durement, comme si notre lune même était aspirée dans la fosse. Cinq mille ans de misère et de désolation, cinq mille ans jusqu'à ce que Drusus nous sauve tous.\""
"Amicus poursuit en décrivant l'histoire dont j'avais une vague connaissance, comment Drusus a rétabli le contact avec les parents, a réuni l'empire des loups et a renommé le monde Adastra, un nom qui représentait tout ce que l'empire représentait."
a "\"Depuis lors, nous nous sommes répandus dans toute la galaxie, avons retrouvé des enfants perdus, établi des routes vers les ressources dont notre lune avait désespérément besoin ...\""
a "\"Mais qu'est-ce que nous avons trouvé le plus précieux? Relancer les relations diplomatiques avec les autres frères et sœurs.\""
a "\"Avec eux, nous avons partagé nos connaissances et nos richesses, nous établissant à nouveau comme de véritables frères et sœurs ... jusqu'à la guerre.\""
a "\"Alors que nos raisons étaient solides pour déclencher le conflit, l'attaque soudaine et inattendue a effrayé les autres frères et sœurs, les laissant une fois de plus nous abandonner.\""
a "\"Nous avons défendu nos droits et notre dignité contre les Khemians—\""
n "\"Oh, Ahhotep ...\""
"Neferu marmonne ça dans sa barbe, heureusement."
a "\"Mais à un prix très élevé. Notre empire a souffert pour notre victoire ... mais il existe un moyen de renverser la situation.\""
"Je ne sais pas si le loup fait du bon travail puisque je n'ai aucun point de référence, mais pour autant que je sache, il semble bien se débrouiller."
"Pas de bégaiement, ni de trébuchement, son jeu est plutôt bon, surtout si je le compare aux acteurs dramatiques que j'ai vus sur les écrans."
"Ses mouvements sont puissants, mais élégants, tout comme sa voix, et je me retrouve rayonnant d'un sentiment de fierté que je n'ai jamais eu pour quelqu'un d'autre auparavant."
"Il poursuit en décrivant les politiques dont il m'avait déjà parlé: rétablir les relations avec les frères et sœurs, élever pleinement les enfants, remodeler leur rôle dans l'empire."
a "\"Et la première étape?\""
"Amicus se tourne soudainement pour nous faire face, bien que son regard soit sur Neferu."
a "\"Une alliance, une qui a été proposée par les Khemians.\""
a "\"Cela peut vous sembler une perspective inquiétante; cela n'a jamais été fait dans l'histoire des {i} Galaxias {/ i}, mais je peux vous promettre qu'en tant qu'empereur, j'exigerai le respect et l'égalité de traitement de la part des Khemians.\""
show ami motivated with dis
a "\"Leur arrogance sera apprivoisée et la dignité des loups sera restaurée.\""
"La lumière sur le drone caméra devant nous est verte, diffusant notre image à l'ensemble d'Adastra."
"Je suis au moins content que Neferu soit capable de contrôler son roulement des yeux en ce moment."
show ami talking with dis
a "\"Dans le cadre de ma règle, je placerai Adastra sur le même piédestal que tous les autres frères et sœurs, sinon plus haut. Nous ne serons plus le demi-frère des {i} Galaxias {/ i}.\""
a "\"Non, nous nous étendrons encore une fois au-delà de notre système, au-delà de notre quadrant, et oui, éventuellement au-delà de la galaxie.\""
"Amicus montre le plafond."
show ami motivated with dis
stop music fadeout 10.0
a "\" Comme Drusus l'a proclamé il y a dix millénaires; 'aux étoiles'.\""
a "\"Alors je dis maintenant; vers les étoiles et au-delà.\""
"Amicus fait une pause dramatique dans cette pose, puis s'incline avant de se retourner et de retourner sur le trône."
hide ami with dissolve
ca "\"Merci, Amicus. Cassius?\""
"J'ai laissé échapper un souffle, regardant Amicus monter les marches, dépassant Cassius alors que son frère se dirigeait vers le même endroit sur le sol."
"Alors c'est tout."
"La part d'Amicus est terminée."
"Maintenant c'est au tour de Cassius, et je le regarde se diriger vers le même endroit, un air renfrogné de colère sur le visage."
show cas annoyed with dissolve
"C'est plus en colère que d'habitude, presque furieux, et je me demande s'il est bouleversé par les bons résultats d'Amicus."
"Mais ensuite il commence à parler, et je réalise que cela fait partie de son émission."
play music "music/tension.ogg" fadein 3.0
show cas angry with dis
c "\"Depuis trois cents ans, notre empire est en ruine!\""
"Je sursaute, et je sens même Neferu se crisper à côté de moi alors que le loup blanc hurle pratiquement."
c "\"Pas à cause de la guerre, pas parce que nous avons choisi une voie différente. Non, c'est {i} parce que {/ i} de Drusus et de sa vision imparfaite des {i} Galaxias {/ i} dans leur ensemble!\""
c "\"Mon frère avait raison à propos d'UNE chose ... Adastra est le plus bas parmi les frères et sœurs, la risée de toute la galaxie!\""
ca "\"Aucune référence à Amicus, Cassius!\""
"Cato aboie de l'autre côté de la salle du trône, mais l'autre loup l'ignore, passant sa patte dans les airs, ses mouvements agressifs et violents."
show cas furious with dis
c "\"ASSEZ d'être la cible de plaisanteries, d'être craché dessus, d'être considéré au niveau de simples enfants!\""
c "\"Il est temps qu'Adastra soit à nouveau respecté, vénéré ... et craint, comme avant Drusus.\""
"Le discours de Cassius continue comme ça, décrivant Adastra en des termes qui le font sonner comme le pire endroit de la galaxie."
"Je ne sais pas si c'est bon ou pas."
"Il est définitivement beaucoup plus intense qu'Amicus, et si c'est le but, alors je suis inquiet."
"Je jette un coup d'œil à Neferu et Virginia, et les regards troublés sur leurs visages me disent que je devrais être encore plus inquiet."
"Je lève les yeux vers le trône, mais Amicus est toujours aussi immobile et impassible."
"Je me sens commencer à transpirer, me demandant si c'est le début de la fin."
show cas angry with dis
c "\"Mon frère a déclaré que la guerre était responsable de notre déclin soudain, un déclin pas si soudain alors qu'il se produit depuis des milliers d'années!\""
c "\"Non, cette guerre était la meilleure chose qui aurait pu arriver à cet empire. Cela montrait que nous n'avions pas peur, que la force la plus puissante de la galaxie ne nous intimidait pas!\""
c "\"On s'est moqué et on s'est moqué de nous avant la guerre! Maintenant, ces rires sont plus calmes, derrière des pattes délicates alors que nos frères et sœurs réalisent à quel point nous pouvons être dangereux. Ils nous prennent au sérieux maintenant ...\""
"Cassius tourne son regard furieux sur nous."
c "\"... mais pas assez sérieusement. Regardez qui ils ont envoyé pour proposer ceci ... cette {i} alliance {/ i} dont mon frère a parlé.\""
ca "\"Aucune référence à Amicus, Cassius.\""
"Mais Cato est plus calme maintenant, comme s'il savait qu'il ne pouvait pas arrêter le jeune loup."
"Le voyant de notre caméra devient vert, et j'ai à nouveau l'impression que l'émission affiche Neferu."
c "\"La seule et unique fleur de Khemia. Le fils de pédé du pharaon avec ses huiles et ses parfums, puant dans les couloirs de notre palais!\""
"Je regarde Neferu, mais son expression n'a guère changé, même si je vois un soupçon de sourire narquois sur ses lèvres."
"Pendant ce temps, Virginia cache un regard de choc, ou d'horreur ... ou les deux, derrière son éventail."
c "\"Cette alliance est hautement suspecte, et je dois me demander ce qui se passe réellement pendant ces ... négociations. En fait, laissez-moi vous donner une idée.\""
"Cassius fait une sorte de signal avec sa patte, puis fait une pause."
"Tout est silencieux pendant un moment, et en regardant les caméras ... aucune d'elles n'est verte."
"Je regarde les autres et je peux voir qu'ils sont également confus."
ca "\"Que diffusez-vous, Cassius?\""
"Cassius ne se retourne même pas pour reconnaître Cato."
show cas right with dis
c "\"Affichage d'un petit clip vidéo.\""
ca "\"De quoi?\""
"Je vois Amicus se hérisser à côté de Cato, et je sens les cheveux se dresser sur mon propre cou."
c "\"D'un acte traître entre mon frère et le chacal fleur.\""
a "\"quoi!?\""
"Amicus est tellement bouffi qu'il a presque deux fois sa taille naturelle."
a "\"Que faites-vous!?\""
ca "\"Oui Cassius, que fais-tu {i} {/ i}?\""
a "\"Cato, il a mis ma chambre sur écoute!\""
"Amicus commence à bouger, mais Cato sort de son trône pour le retenir."
show cas smile with dis
c "\"Reste là, mon frère, c'est presque fini. Et ne vous inquiétez pas; il est censuré.\""
"Cassius ricane à Amicus avant que la lumière rouge de son drone ne redevienne soudainement verte."
show cas annoyed with dis
"Cassius fixe l'objectif pendant un moment, laissant le silence s'étirer pour un effet dramatique."
c "\"Choquant, n'est-ce pas? J'ai déjà décrit la Fleur de Khemia ... voulons-nous aussi que la Fleur d'Adastra soit notre empereur?\""
ca "\"Temps, Cassius.\""
"La voix de Cato est douce, presque étonnée."
"Amicus a clairement beaucoup plus de mal à contrôler ses émotions maintenant."
"Même de cette distance, je peux le voir travailler sa mâchoire."
"Mais Cassius ne semble pas avoir fini."
c "\"Et laissez-moi vous laisser avec ceci—\""
ca "\"TIME, Cassius. Cédez le sol!\""
show cas furious with dis
c "\"Non, je ne céderai pas! Adastra est celle hors du temps! Cet empire est tendu, et ce hayon nous propose de s'étirer encore plus! Quand est-ce que nous cassons!?\""
"Cassius se retourne et pointe du doigt Amicus."
c "\"Il regarde vers les enfants et les frères et sœurs tout en nous ignorant complètement!\""
stop music fadeout 10.0
"La fourrure hérissée de Cassius recommence lentement à se recoucher, le loup essayant de reprendre le contrôle de lui-même."
show cas right with dis
c "\"Alors ... laissez-moi vous laisser avec ceci; en faisant campagne dans la périphérie de la ville d'Adastra, des zones complètement négligées par mon frère, je suis tombé sur un jeune enfant atteint de la même maladie qui m'afflige.\""
"La voix de Cassius devient beaucoup plus calme, douce, abaissant un peu son museau pour fixer le sol."
show cas disappointed with dis
c "\"Contrairement à moi, elle n'avait aucun médicament à proprement parler parce que sa pauvre famille d'agriculteurs n'en avait pas les moyens. Elle était attachée à un fauteuil roulant, ses os si fragiles que quelque chose d'aussi simple qu'un bain les fait se disloquer et se briser.\""
"La voix de Cassius attrape et, à ma grande surprise, je vois une larme couler sur sa joue."
show cas sad with dis
c "\"Comment cet empire a osé laisser notre peuple tomber dans un état tel que nous ne pouvons même pas nous soucier de notre propre peuple. J'entends que même maintenant, nous ne pouvons pas nous permettre de vacciner ceux qui sont au-delà de notre ville étincelante.\""
"Cassius regarde la caméra."
show cas paw with dis
c "\"Il peut sembler que nous ne pouvons pas vous entendre au-delà des murs de ce palais, mais je vous entends. Je promets de toujours vous entendre. Je ne répondrai pas aux besoins et aux désirs des frères et sœurs ou des enfants, des élites ou des fonctionnaires d'Adastra City.\""
"Cassius balaie dramatiquement une patte contre sa poitrine."
show cas paw talking with dis
c "\"Pas 'aux étoiles', mais à VOUS, les gens de l'empire ... Merci.\""
"Cassius s'incline devant la caméra avant de se retourner pour retourner sur le trône."
hide cas with dissolve
"Il y a un long moment de silence alors que nous regardons tous le loup blanc, puis la voix de Com crépite au-dessus de nos têtes."
com "\"Triumvirates, prenez vos décisions.\""
"Soudain, je sens quelque chose me saisir autour du poignet et regarder en bas pour voir la patte noire et velue de Neferu se tenant à moi."
show nef serious with dissolve
n "\"[mc], très tranquillement, nous allons nous lever et nous diriger vers ma chambre. Nous allons nous déplacer à l'arrière pour que la caméra ne voie pas.\""
m "\"Pourquoi?\""
show nef angry with dis
n "\"Parce que ce qu'Amicus avait craint est sur le point de -\""
com "\"Les triumvirates ont pris leurs décisions.\""
"Je vois les yeux de Neferu s'écarquiller de surprise."
show nef unsure f with dis
n "\"Déjà?\""
"Il semble se le dire, mais il se lève et je dois me tenir avec lui alors qu'il commence à marcher dans l'allée, vers le fond de la pièce, me tirant avec lui."
hide nef with dissolve
"Je regarde Amicus et je vois le loup me regarder, enfin."
"Ses yeux sont pleins d'inquiétude et de regret, et je peux dire que tout le monde sait que Cassius a gagné."
"Mon estomac baisse et je me rends compte que ce que j'ai été terrifié de se produire tout le mois est en train de se produire."
"Nous avons perdu."
"Je ne peux que fixer le bras musclé de Neferu alors qu'il me tire vers les portes, vers un avenir inconnu et indésirable ..."
com "\"Lupas—\""
"Après tout ce temps, après tout ce que nous avions fait ... nous avons perdu."
com "\"Amicus.\""
"Neferu fait une pause."
"Je lève les yeux vers le plafond, vers l'endroit où j'imagine toujours Com s'il était réel, puis je regarde le trône."
com "\"Ad Rotae: Amicus.\""
"Amicus a l'air aussi choqué que moi."
"Cassius, quant à lui, a la mâchoire serrée."
"Comme toujours, je ne peux pas lire Cato."
com "\"Lux: Amicus.\""
com "\"Gebii: Amicus.\""
"Que diable se passe-t-il?"
"Il avait juste semblé que tout le monde pensait que Cassius allait gagner, et si tout était basé sur la performance ... alors il devrait gagner."
com "\"Tricelli: Amicus.\""
"Il y a une pause, une qui me fait réaliser que nous venons de ... gagner?"
"Avons-nous vraiment gagné?"
com "\"Adastra?\""
"Cato regarde droit devant lui avec sa visière, et maintenant je peux voir ses pattes s'agripper aux accoudoirs de son trône."
"Le silence dure si longtemps que Com demande à nouveau."
com "\"Adastra?\""
"Cato laisse le silence continuer pendant plusieurs secondes de plus avant d'ouvrir enfin sa muselière."
ca "\"Cassius.\""
"Je ne sais pas quoi penser, mais Com répond immédiatement."
com "\"Le procès a été décidé. Amicus est le vainqueur.\""
"Le silence qui suit cette fois est assourdissant."
"Personne ne se réjouit, personne ne bouge."
"Même l'éventail de Virginia est figé, comme si nous étions tous coincés dans une image."
"Pendant tout ce temps, les caméras continuent de planer au-dessus de nos têtes, chacune d'entre elles clignotant en vert pendant un moment."
"Enfin, Com est à nouveau celui qui brise le silence."
com "\" Ceci conclut le deuxième essai. Merci.\""
"Avec cela, les lumières de la caméra s'éteignent complètement et les drones planent vers le compartiment au plafond."
scene bg throneroom with dissolve
"Les lumières se rallument."
"Comme ils le font, Neferu me tire une fois de plus vers les portes."
"Je veux me retenir et regarder, mais le chacal insiste, et la prochaine chose que je sais, les portes s'ouvrent tranquillement, et nous entrons dans l'atmosphère tout aussi silencieuse, bien que beaucoup moins tendue, des salles de marbre."
scene bg palace1 with dissolve
play sound "sfx/dooropen.ogg"
play loop "sfx/birds.ogg" fadein 3.0
m "\"Où allons-nous? Nous venons de gagner.\""
"En disant cela, je sens que l'excitation remplace enfin le choc."
"Nous avons gagné!"
m "\"Neferu, nous ne -\""
show nef serious with dissolve
n "\"Clairement, mais cela ne signifie pas que vous êtes encore en sécurité.\""
m "\"Quoi?\""
"Neferu est silencieux pendant un moment, à ce stade le chacal ayant lâché ma main, me permettant de juste suivre derrière lui."
m "\"Que s'est-il même passé?\""
show nef skeptic f with dis
n "\"Selon vous, qui aurait dû gagner, [mc]?\""
"Je fronce les sourcils."
m "\"Est-ce que c'est important? Les triumvirates ont décidé. Amicus a gagné.\""
n "\"C'est vrai, mais pas seulement les triumvirates regardaient. Nous savons tous qui aurait dû gagner.\""
"Je me sens sur la défensive."
m "\"Cassius était un connard total, et en plus, il a triché. Il a dépassé le temps imparti ET a fait référence à Amicus et à ses points.\""
"Neferu rit sans joie."
show nef with dis
n "\"Les règles n'ont pas d'importance. Je suis sûr que vous vous en êtes probablement rendu compte maintenant. Cassius a fait exactement ce qu'il aurait dû ... mais il a perdu à cause de toi.\""
m "\"Quoi?\""
show nef serious a with dis
n "\"Les triumvirates ont clairement pris leurs décisions bien avant le procès. Nous espérions qu'ils n'iraient pas contre la volonté du peuple, mais la performance de Cassius les a forcés à le faire.\""
m "\"Vous parlez de la rumeur selon laquelle Cassius s'en serait débarrassé?\""
n "\"Ce serait celui-là. J'avais pensé qu'une victoire aussi déséquilibrée de la part de Cassius aurait dissuadé au moins la plupart d'entre eux. Leur soif de pouvoir est insatiable, semble-t-il.\""
"Encore une fois, je me sens sur la défensive, mais il y a aussi un sentiment d'inquiétude qui s'installe."
m "\"Eh bien ... je ne sais pas, je pense qu'Amicus a fait du bon travail. En plus, c'est LEUR rôle de garder le pouvoir de l'empereur sous contrôle de toute façon, n'est-ce pas?\""
n "\"Oui, mais ce n'est pas le but des essais, et les gens le savent. Adastra ne sera pas contente de ça.\""
m "\"Eh bien ... qu'est-ce que cela signifie, alors?\""
"Nous nous arrêtons devant la chambre d'Amicus, et finalement, le chacal se retourne pour me faire face."
show nef with dis
n "\"Que je ne peux pas vous dire. Je ne suis pas un expert de la politique d'Adastra, je suis simplement un étudiant ici. Amicus a peut-être gagné cette bataille, mais je peux garantir que la lutte pour le pouvoir est loin d'être terminée.\""
n "\"Amicus pourra vous en expliquer davantage à son arrivée. Pour l'instant, attendez-le dans sa chambre.\""
"Le chacal commence à se retourner pour partir, mais semble remarquer l'expression confuse et probablement inquiète sur mon visage."
"Il fait une pause, puis pose une patte sur mon épaule."
show nef sidesmile f with dis
n "\"Ne vous inquiétez pas trop à ce sujet. C'est normal pour le cours de la politique Wolven, je le sais. Le drame est leur identité, et nous ne pouvons être que pour le trajet.\""
"Neferu me sourit."
show nef wink f with dis
n "\"Amicus vous gardera en sécurité, et si vous avez un besoin qu'il ne peut pas satisfaire, je suis également là.\""
"Je sais que Neferu a l'intention que cela paraisse salace, mais je pense aussi qu'il le pense ... d'une manière agréable."
"J'ai mis ma main sur sa patte."
m "\"Merci.\""
show nef with dis
"Le chacal me fait un signe de la tête avant de se détourner pour remonter le couloir, probablement vers sa propre chambre."
hide nef with dissolve
stop loop fadeout 5.0
"Une fois qu'il est hors de vue, j'appuie ma main sur le panneau et entre dans la chambre d'Amicus, assis sur le canapé pour attendre."

scene bg amicusroom with fade
"C'est étrange ... Amicus a gagné, mais ça ne se sent pas exactement comme ça après ce que Neferu vient de me dire."
"Amicus n'a pas vraiment gagné ... nous avions gagné à cause d'une rumeur, ce qui rendait tout le procès inutile."
"Pourtant, je ne peux pas vraiment me sentir mal à ce sujet."
"Cassius a mis sur écoute cette même pièce pour montrer des images d'Amicus en train de baiser Neferu."
"Je ferme les yeux, les frottant avec une main alors que je réalise à quel point cela a pu nuire à la réputation d'Amicus."
"Non seulement les gens se rendent compte que ce procès a été décidé dès le début par des triumvirates corrompus, mais aussi que leur futur empereur a eu des relations sexuelles avec un homme ... un homme khémien en plus."
"Mais encore une fois, Cassius perdant à cause de son intention de se débarrasser de l'un des rares contrôles de son pouvoir me semble être du karma."
"N'ont-ils pas gardé le pouvoir de l'empereur sous contrôle en prenant la décision qu'ils ont prise?"
"Techniquement, Amicus deviendra empereur maintenant, bien que je suppose que ce ne sera pas officiel tant que Cassius n'aura pas concédé le troisième essai."
"Je retourne ces pensées encore et encore dans ma tête pendant les 20 minutes suivantes, un peu ennuyé par le fait que même si j'ai eu exactement ce que je voulais, plusieurs problèmes étaient venus avec."
play sound "sfx/dooropen.ogg"
"Soudainement, la porte s'ouvre et j'oublie mon inquiétude pendant un instant alors que je vois Amicus debout là."
"Il ne fait que quelques pas dans la pièce avant que je sois déjà là, enroulant mes bras autour de son corps pendant que je le serre dans mes bras."
show ami with dissolve
play music "music/starship.ogg" fadein 3.0
a "\" Whoa! Hé, [mc]. Tout va bien?\""
"Le loup pose une lourde patte sur ma tête, frottant doucement les coussinets contre mon cuir chevelu."
m "\"Etes-vous?\""
show ami happy eyes with dis
a "\"Bien sûr.\""
"Amicus me sourit chaleureusement, mais l'ayant connu depuis si longtemps, je sais que ce n'est pas tout à fait vrai."
m "\"Eh bien ... nous avons gagné.\""
show ami with dis
a "\"Nous l'avons fait.\""
"Il est silencieux pendant un moment, continuant à me frotter la tête."
m "\"Ce n'est pas vraiment ce que j'imaginais.\""
"Amicus rit doucement."
show ami happy eyes with dis
a "\"Hahaha ... moi non plus, mais nous avons gagné, et c'est la partie importante.\""
"Amicus me serre à nouveau dans ses bras."
m "\"Est-ce que Cassius a fait, ce qu'il a montré ... à quel point était-ce mauvais?\""
show ami serious with dis
"Amicus grimace."
a "\"Mauvais, mais je trouverai un moyen de m'en sortir. Il semble que mon premier travail en tant qu'empereur sera de reconstruire mon image.\""
m "\"Quand deviens-tu empereur?\""
show ami crossed with dis
a "\"Dès que Cassius abandonne. Je ne pense pas qu'il soit encore d'humeur à faire ça, cependant.\""
"Nous restons là pendant un moment, Amicus continuant de me caresser la tête alors que je l'appuyais contre sa poitrine, écoutant le doux battement de son cœur."
m "\"Je suis juste content que ce soit fini.\""
a "\"Je ressens la même chose.\""
m "\"Et ensuite?\""
a "\"Eh bien ... pour l'instant, je dois aller en ville. Les triumvirates ont demandé à la famille impériale d'être vue immédiatement.\""
m "\"Oh, pourquoi?\""
a "\"Eh bien, tout le monde suppose que les épreuves sont terminées. Ils aimeraient discuter de choses avec la famille avant de quitter Adastra pour leurs propres villes.\""
m "\"Je vois.\""
a "\"Ils vous ont également demandé d'y aller.\""
"Je me penche en arrière pour regarder le loup."
m "\"Vraiment?\""
a "\"Oui, mais je leur ai dit de ne pas s'y attendre. Je sais que vous vouliez voir la ville, mais c'est à vous de décider ... eh bien, ce ne sera pas la ville réelle, juste le quartier où vivent les délégués. Les choses sont un peu ... chaotiques dans le centre-ville en ce moment.\""
m "\"Chaotique?\""
show ami serious crossed with dis
a "\"Les citoyens sont ... excités après le procès.\""
m "\"Ah.\""
"J'imagine qu'excité signifie en colère."
m "\"Je pourrais ... mais faire des trucs officiels semble un peu effrayant.\""
show ami crossed with dis
a "\"Tu n'aurais rien à faire, tu as juste l'air heureux d'être là, mais c'est à toi de décider.\""
m "\"Cela vous aiderait-il?\""
a "\"Peut-être, je serais certainement heureux de vous avoir là-bas.\""
m "\"Alors bien sûr.\""
show ami surprised with dis
"Les sourcils du loup se haussent de surprise."
a "\" Oh, vraiment? Très bien alors. Allons-y.\""
m "\"Maintenant?\""
show ami crossed with dis
a "\" Oui, je crois que les autres sont déjà dans le char. Es-tu prêt?\""
m "\"Je ... pense que oui, sauf si j'ai besoin d'apporter quoi que ce soit.\""
a "\"Pas du tout. Et désolé, je sais que les choses évoluent rapidement en ce moment. C'est normal après le procès, mais nous pourrons parler en privé à notre retour, d'accord?\""
m "\"D'accord.\""
stop music fadeout 10.0
hide ami with dissolve
"Amicus se tourne déjà pour me tirer, mais je l'arrête."
"Quand il se retourne, je fais ce que je voulais faire depuis juste avant le début du procès, et je l'embrasse sur les lèvres."

scene bg garden2 with transition_fade
"Le char n'est en réalité qu'un grand chariot métallique."
"Il a des bancs à l'intérieur avec un dessus ouvert."
"Il n'y a pas de chevaux, bien sûr, et il semble se déplacer tout seul."
"C'est la première fois que je vois des roues utilisées pour le transport ici, cependant."
"Alors que nous nous approchons, je remarque que Virginia et Neferu sont déjà assis à l'avant ... et Cassius est à l'arrière avec Alex."
"Il détourne délibérément le regard de nous."
"Je chuchote à Amicus alors que nous nous rapprochons du char."
m "\"Cassius part?\""
a "\"Oui ... Je pense que Cato l'a fait partir.\""
"Malgré tout ce que le loup blanc a fait, en particulier lors du procès, je ne peux m'empêcher de me sentir un peu désolé pour lui."
"Je ne peux pas imaginer devoir sortir en public juste après la défaite de votre campagne de plusieurs années."
"Amicus saute en premier, assis à côté de Virginia avant de se pencher vers moi pour me tirer à côté de lui."
m "\"Je pensais que nous volerions là-bas.\""
show ami embarrassed at twelve with dissolve
a "\" Nous le faisons habituellement, mais comme le bateau que nous avions l'habitude de transporter en ville, euh, s'est écrasé il y a quelques mois, nous avons décidé que le char était plus sûr et plus discret.\""
show vir at center with dissolve
v "\"Oui, quelque chose qui sera utile compte tenu de l'état de la ville en ce moment.\""
show ami serious crossed with dis
a "\"Oui.\""
m "\"Quel est l'état de la ville?\""
"Virginia fixe ses yeux sur moi, me regardant vraiment pour la première fois depuis longtemps."
v "\"Des émeutes, des pillages, comme d'habitude, bien qu'un peu inhabituel pour Adastra City comparé à, disons, Lux.\""
"Amicus me regarde, mais c'est à ce moment-là qu'il y a une secousse soudaine alors que le char avance, vers la limite des arbres."
play loop "sfx/chariot.ogg" fadein 3.0
"Virginia regarde Amicus."
show vir p with dis
v "\"Je dois dire que votre animal de compagnie est bien plus fascinant que je ne le pensais au départ. Il pouvait à peine parler quand je l'ai rencontré pour la première fois.\""
show ami embarrassed with dis
a "\"Euh ... oui, il était timide.\""
"Je suppose que j'aurais dû dire à Amicus que mon acte avait été révélé à ce stade."
v "\"Eh bien, il faut renouer avec cette Simia, alors. Ils semblent étrangement intelligents.\""
show ami surprised with dis
a "\"Mmh, oui ... Oh, merci aux dieux pour les arbres. Vita est beaucoup trop dure aujourd'hui.\""
"Amicus essaie clairement de changer de sujet alors que la route se transforme en forêt épaisse."
scene bg forest with dissolve
stop loop fadeout 5.0
play music "sfx/forest.ogg" fadein 5.0
"Nous sommes recouverts d'une étrange lueur verte alors que la forêt nous enveloppe."
"Des insectes étranges et brillants volent autour de notre voiture, et je remarque à quel point les arbres ont l'air vieux, noueux et rugueux, bloquant presque complètement le ciel."
v "\"J'espère qu'ils nous permettront de nous rafraîchir un peu avant la cérémonie. Je serai en désordre au moment où nous atteindrons la ville.\""
"Virginia sort à nouveau son grand éventail brodé, l'agitant frénétiquement sur son visage."
"J'aurais aimé en avoir un aussi, ma peau collant presque immédiatement dans l'air humide."
show nef at zero with dissolve
n "\"Vous aurez l'air bien. De plus, nous serons tous dans le même état.\""
show ami crossed serious at twelve with dissolve
"Amicus jette un coup d'œil au chacal."
a "\"Je dois me demander ce qui vous a amené, Neferu?\""
show nef smile eyes a with dis
n "\"Ma présence a été demandée.\""
a "\"Par qui?\""
show vir serious with dis
v "\"Oh, pour le bien de Vita, ne commence pas, Amicus.\""
show ami surprised with dis
a "\"quoi? Je suis simplement curieux. \""
v "\"Non, vous essayez de commencer un combat, qui est la dernière chose dont nous avons besoin devant les triumvirates\""
show ami crossed serious with dis
a "\"Hmph ...\""
show vir with dis
v "\"D'ailleurs, votre politique n'est-elle pas de vous lier d'amitié avec les Khemians?\""
a "\"Une alliance n'est pas une amitié.\""
show nef with dis
n "\"Les Khemians le voient comme de l'amitié.\""
v "\"D'ailleurs, tout le monde pense probablement que vous êtes déjà très ... proche après ce qui a été diffusé.\""
show ami shocked with dis
a "\"Virginie!\""
show nef smile eyes a
show vir smile p
with dis
"Elle cache son sourire narquois derrière l'éventail alors que Neferu sourit à côté d'elle."
show vir with dis
v "\"Je vous rappelle simplement que cela pourrait être encore frais dans l'esprit de tout le monde lorsque nous y arriverons.\""
show ami angry with dis
"Amicus s'affaisse sur son siège, les jambes allongées devant lui."
a "\"Raison de plus pour paraître distante. Cela affectera probablement ma réputation pendant des ANS.\""
show vir p with dis
v "\"Oh, ne soyez pas si dramatique. Les gens aiment ces scandales, ils font simplement semblant d'être indignés.\""
"Amicus renifle, mais ne dit rien de plus, signalant que la conversation est terminée."
hide ami
hide nef
hide vir
with dissolve
"Je me demande si Cassius, assis juste derrière nous, écoute."
"Probablement."
"Je trouve tout cela étrange, le loup qui a essayé de saboter Amicus en divulguant ce qui était essentiellement un porno assis juste derrière nous."
"Je tourne légèrement la tête, essayant de regarder Cassius pour voir s'il nous regarde."
"Je ne vois rien, alors je me retourne plus complètement et constate que le loup blanc est couché, les yeux fermés avec sa tête sur les genoux d'Alex."
show ale with dissolve
"Alex lève les yeux vers moi et sourit avec un signe de la main."
"Je fais un signe maladroit avant de me retourner rapidement."
hide ale with dissolve
"Virginia et Neferu semblaient être pris dans leur propre conversation en ce moment alors qu'Amicus continue de bouder, fixant ses pieds."
m "\"Alors ... que va-t-il se passer exactement quand nous y arriverons?\""
show ami crossed serious with dissolve
a "\"Hm? Oh, eh bien, la rencontre avec les triumvirates, comme je l'ai dit plus tôt.\""
show ami crossed with dis
a "\"Après cela, nous allons probablement marcher dans les rues du quartier pour visiter les boutiques et un restaurant.\""
m "\"Alors je serai juste à côté de toi?\""
show ami eyes with dis
a "\"Oui.\""
m "\"Très bien.\""
stop music fadeout 5.0
"Pour le reste du trajet, je m'appuie contre le côté d'Amicus, et après plusieurs minutes, je commence à hocher la tête."
"Amicus remarque et enroule un bras autour de moi, et je suis capable de m'appuyer confortablement contre sa poitrine pour m'endormir ..."

scene bg cityday with transition_fade
"La prochaine chose que je sais, c'est que je suis réveillé par Amicus."
"Je me retrouve à regarder plusieurs bâtiments, le changement soudain de décor me laissant étourdi."
"J'essaye toujours de me repérer alors qu'Amicus saute hors de la voiture, se levant pour me soulever."
"Quand je regarde en arrière, je peux voir un grand groupe de loups sur le côté, nous regardant attentivement."
"Immédiatement, je me sens gêné, la foule étant le plus grand rassemblement de loups que j'ai vu en personne."
"Ils sont de toutes formes et tailles, et je suis surpris de voir quelques-uns d'entre eux qui sont presque aussi courts que moi."
"La seule caractéristique que tous partagent cependant, c'est leur stature épaisse."
"Amicus me guide pour me tenir devant le char avec Neferu, Virginia, Cassius et Alex, me tenant près de lui."
"Un des vieux loups sort du groupe."
play music "music/secondthoughts1.ogg" fadein 3.0
"Triumvirat" "\"Bienvenue famille impériale! Merci beaucoup d'être venus en ce jour du deuxième procès. C'était un spectacle merveilleux!\""
"Cela semble être une chose audacieuse à dire après la diffusion d'un clip de Neferu et Amicus en train de baiser."
"Il ne semble pas y avoir de gêne cependant, les vieux loups semblant impatients de parler à Amicus."
"Triumvirat" "\"Je suis Cicéron, premier triumvirat d'Ad Rotae.\""
"Le vieux loup s'avance vers Amicus, posant ses pattes sur les épaules du plus gros loup et touchant les côtés de leurs museaux ensemble."
"Du coin de l'œil, je remarque que Cassius nous lance un regard amer et en colère."
"Le loup et Amicus tiennent une courte conversation, le loup plus âgé demandant à Amicus ce qu'il pensait d'Ad Rotae, quels problèmes la ville avait actuellement et comment ils pourraient procéder à l'avenir."
"Après cela, il se rend ensuite en Virginie où la conversation est beaucoup plus courte."
"Un autre loup du groupe avance pour parler à Amicus, la conversation suivant un schéma à peu près similaire."
"On ne parle pas d'Amicus comme empereur, mais l'hypothèse est là, et quand chacun d'eux arrive à Cassius, c'est presque aussi bref qu'avec Virginie."
"Malgré la nouveauté de cette situation, je m'ennuie rapidement, et les conversations se mélangent très vite alors que plus d'une douzaine de ces vieux loups s'avancent pour se présenter à Amicus."
"Pour sa part, Amicus fait un très bon travail en semblant enthousiaste pour chaque introduction, mentionnant qu'il sait déjà qui ils sont et qu'il pense très, très fortement à leur ville et à leur région."
"De temps en temps, ils me regardent et commentent à quel point j'ai l'air étrange, même si c'est généralement avec un ton positif, félicitant Amicus de m'avoir attrapé."
"Cela semble mettre Amicus mal à l'aise, mais je garde un visage impassible et je m'incline à chaque fois, semblant ravir les vieux loups avec mon étiquette."
"Finalement, ces présentations se terminent, mais alors que nous commençons à nous diriger vers les magasins, les triumvirates continuent de nous suivre, et j'ai plus de mal à suivre Amicus."
"Il est pratiquement entouré par les triumvirates."
"J'abandonne d'essayer de rester à côté de lui, et même s'il n'arrête pas de me regarder et de m'appeler plusieurs fois, je lui fais un signe de la main, choisissant à la place de marcher aux côtés de Neferu et de Virginie."
"Bien sûr, c'est ennuyeux, mais il est sur le point de devenir empereur, donc il est logique qu'il soit si populaire."
"Alors que nous marchons dans les rues, les loups appellent Amicus depuis les portes et les fenêtres, et il essaie de les saluer tous."
"Plus haut sur la route, un groupe d'enfants ... des chiots se présentent avec des fleurs dans leurs pattes, les distribuant à Amicus et aux triumvirates."
"Alors que je regarde cela se produire, je remarque une enfant particulièrement inégale, pas plus grande que ma taille qui se tient maladroitement sur le côté, me regardant droit alors qu'elle tient une fleur dans ses pattes."
stop music fadeout 10.0
"Je m'arrête, ne sachant pas si elle veut me le donner."
"Quand je le fais, elle se rapproche."
"Alors je me penche, tend la main et ses yeux s'écarquillent, probablement à la fois horrifiés et fascinés d'attirer l'attention de l'extraterrestre fou."
"Néanmoins, elle se rapproche et pousse timidement la fleur froissée et fanée dans mes mains avant de se pencher soudainement et de toucher le côté de son visage contre le mien."
"Pendant un moment, je vois ses yeux larmoyants et injectés de sang."
"Puis je sens la fourrure légèrement humide effleurer ma peau avant qu'elle ne fasse un drôle de jappement et s'enfuie dans la rue."
"Je la regarde, me demandant si j'avais fait quelque chose de mal."
show nef with dissolve
n "\"Vous avez trouvé un cadeau?\""
"Je regarde la fleur blanche, remarquant qu'il manque plusieurs pétales."
m "\"Je suppose.\""
show nef serious with dis
n "\"Celle-là n'avait pas l'air en bonne santé, n'est-ce pas?\""
m "\"Pas vraiment.\""
n "\"Peut-être que Cassius avait un point avec son discours.\""
m "\"Je pense qu'ils ont tous deux fait valoir de bons points, honnêtement.\""
"Neferu fait signe à la bande de loups qui s'éloignent de plus en plus de nous."
show nef with dis
n "\"Mieux vaut rattraper son retard avant qu'ils ne nous laissent derrière.\""
m "\"Ouais.\""
stop music fadeout 5.0
"Je regarde à nouveau la fleur, un peu inquiète maintenant, avant de la laisser tomber sur la route, me sentant un peu coupable comme moi."

scene bg cityday with dissolve
"Même si la cérémonie est techniquement terminée, les triumvirates ne semblent pas vouloir laisser Amicus seul."
"Je suis un peu étonné de voir à quel point Amicus traite bien avec eux compte tenu de mon agacement."
"Amicus essaie de me ramener à ses côtés à quelques reprises, en me montrant des bibelots et des souvenirs qu'il essaie d'expliquer, comme s'il voulait me montrer un peu de culture Adastran."
"C'est sympa, et je peux dire qu'il veut m'impliquer, mais c'est beaucoup trop occupé avec des triumvirates et des habitants qui entrent toutes les cinq secondes pour demander ou dire quelque chose à Amicus."
"J'aurais aimé qu'il puisse leur dire de partir, mais je sais que ça ne marche pas comme ça."
"En plus de ça, mes articulations commencent vraiment à me faire mal à cause de toute la marche et je me demande si vivre dans le palais depuis si longtemps m'a rendu mou."
"Finalement, je suis juste le groupe de loups, parcourant les marchandises après eux."
"C'est intéressant, bien sûr, mais tout est tellement similaire à ce que nous avons sur Terre: des colliers, des boucles d'oreilles, des pinceaux, des vêtements, rien de ce qui est époustouflant."
"Finalement, Amicus crie très fort qu'il aimerait aller au restaurant avec son animal de compagnie, si tout le monde pouvait lui permettre de passer."
"Je prends ça comme un signal pour me déplacer à ses côtés et il met immédiatement un bras autour du mien, me tenant près de moi."
"Alors que nous marchons dans la rue (les nombreux loups qui suivent toujours derrière nous), Amicus met son museau près de mon oreille, envoyant un peu de frisson sur mon cou… un qui est étrangement douloureux."
show ami embarrassed with dissolve
a "\"Tout va bien, [mc]? Vous semblez un peu ... inconfortable.\""
"Je hausse les épaules."
m "\"Tout ici est nouveau pour moi, alors je suppose que je me sens un peu mal.\""
show ami with dis
a "\"Eh bien, installons-nous dans un restaurant. Nous pouvons nous rafraîchir et reprendre notre souffle là-bas.\""
"Le loup me serre rapidement avec son bras, et malgré mon humeur légèrement aigre, je ne peux pas m'empêcher de sourire un peu."
"Je veux dire, c'est plutôt cool que mon ami soit si populaire ... même si c'est parce qu'il va être le prochain empereur."
hide ami with dissolve
play music "music/lute.ogg"
"Nous entrons dans un petit restaurant confortable, et je peux dire tout de suite qu'il est plutôt haut de gamme avec ses piliers sculptés et les tapisseries fantaisie sur le mur."
"Là encore, tout dans ce quartier est plutôt haut de gamme, je suppose."
"Les triumvirates nous suivent cependant jusque dans le restaurant, et j'ai poussé un soupir frustré."
"Amicus le remarque tout de suite et fait signe à un loup debout derrière un podium."
"Ce loup en particulier nous regarde les yeux écarquillés, apparemment gob frappé de voir le futur empereur apparaître dans son restaurant."
"Il trébuche pratiquement sur lui-même pour nous atteindre, se cognant la hanche sur le côté d'une table comme il le fait."
"Loup" "\"Y-y-y-oui, votre, euh, votre .... euh, majesté?\""
"Amicus grimace."
a "\"Juste Amicus, s'il vous plaît. Pourriez-vous nous offrir une table isolée, de préférence sans personne assise à côté de nous.\""
"\"Bien sûr!\""
"Le loup trébuche à nouveau sur lui-même avant de nous conduire dans un coin du restaurant, en désignant une table là-bas."
"Il se tourne alors vers un couple à côté de la table et commence à siffler frénétiquement après eux pour qu'ils bougent."
"Ils le regardent avec étonnement jusqu'à ce qu'Amicus intervienne pour l'arrêter."
a "\"Ils vont bien, juste euh, ne laissez personne de ... ce groupe là-bas s'asseoir à côté de nous, si ça va?\""
"Amicus secoue la tête en direction du troupeau de vieux loups, tous nous regardant d'un air plutôt belliqueux."
"\"Oh oui bien sûr!\""
"Il se précipite vers ledit groupe et nous sommes enfin capables de nous asseoir ... ou de nous allonger."
stop music fadeout 5.0
"Les sièges sont bien sûr de style romain."
"Amicus s'installe avec un énorme soupir, étirant son grand corps sur le lit."
scene dinner1 with slow_dissolve
a "\"Désolé pour ça. J'aurais dû vous avertir à quel point ... cela peut être frustrant avec tous les bavardages inutiles.\""
play music "music/dawn.ogg" fadein 3.0
"Je hausse les épaules."
m "\"Cela semble convenir à la politique.\""
a "\"Oh, c'est vrai, mais ne vous inquiétez pas, il est rare que tous les triumvirates soient dans la ville en même temps. Ceci est pour les essais, bien sûr.\""
m "\"Ouais, ça a du sens.\""
a "\"Vous êtes sûr que vous allez bien? Je n'arrive jamais à le dire.\""
m "\"Je vais bien.\""
"Je frotte mes bras, la peau est sensible et douloureuse, tout comme mes articulations."
"Je me demande si j'ai aussi un coup de soleil."
a "\"Très bien ... alors que pensez-vous de la ville? Cette partie au moins. J'aimerais pouvoir vous emmener là où se trouvent les gratte-ciel, mais comme je l'ai dit, les choses sont un peu chaotiques en ce moment.\""
m "\"C'est plutôt cool. Ce ne serait pas exactement hors de propos sur Terre, définitivement différent, mais vraiment similaire.\""
a "\"Ah, eh bien, vous avez été élevé par nous après tout.\""
m "\"... Ouais. Alors, c'est ce que tu vas faire en tant qu'empereur? Viens en ville et juste ... parle?\""
"Amicus rit."
a "\"Oh, il y en aura beaucoup plus, j'en suis sûr. J'espère que Cato m'apprendra un peu ... s'il parvient à surmonter l'épreuve.\""
"Je me souviens que Cato a voté pour Cassius."
"Il est probablement furieux à ce sujet en ce moment."
m "\"N'auriez-vous pas des conseillers, etc.?\""
a "\"Eh bien, oui, mais je dois les choisir.\""
m "\"Choisiriez-vous Cato?\""
a "\"Je pourrais.\""
m "\"Veux-tu?\""
a "\"Eh bien ... peut-être, mais les événements récents m'ont laissé un peu incertain à ce sujet.\""
m "\"Pourquoi ça?\""
"Amicus secoue la tête."
a "\"Ne vous en faites pas maintenant, nous devrions faire la fête.\""
m "\"Je veux dire, vous pourriez devenir empereur à tout moment. Tu ne devrais pas avoir quelqu'un qui a une bonne tête sur les épaules au début?\""
a "\"Heh, je suppose. Qui suggéreriez-vous?\""
"J'ai le sentiment qu'il me pousse à m'offrir, mais ce ne serait certainement pas le cas."
"Les quelques loups que je connais rendent la décision assez facile."
m "\"Virginie.\""
"Amicus hausse les sourcils avec une légère surprise."
a "\"Oh ... eh bien, oui, je la considérerais certainement. Le seul problème est l'image d'une femme qui me dit ce que je fais. La réputation des haltérophiles est assez mauvaise.\""
"Je roule les yeux."
m "\"Peut-être que la masculinité des loups est quelque chose que vous pouvez réparer pendant que vous êtes empereur?\""
"Amicus ne semble pas savoir comment répondre à cela, mais il n'est pas obligé de le faire car notre nourriture arrive."
"Je suis un peu surpris car nous n'avons pas commandé, mais en regardant autour de vous, il semble que tout le monde obtient la même chose."
scene dinner2 with dissolve
"Il y a les olives, les raisins, le fromage et le pain habituels, mais aussi les fruits de mer et même les œufs qui me surprennent."
"Amicus remercie le serveur nerveux avant de commencer immédiatement à creuser."
"Je fais la même chose, mais pendant que j'étale du fromage sur le pain, mon esprit revient sur ce qui pourrait se passer dans la ville en ce moment."
m "\"Alors ... à quel point les choses sont-elles mauvaises dans la ville? Personne ne semble s’inquiéter à ce sujet.\""
a "\"D'après ce qu'on m'a dit, c'est assez doux. Les émeutes sont courantes à Adastra, mais elles ne durent pas longtemps. Je pense que les gens vont se calmer dans les prochains jours.\""
m "\"Oh, d'accord. Alors ils n'aiment pas ... ne vous aiment pas, ou quoi que ce soit?\""
"Il faut un moment à Amicus pour avaler sa bouchée de pain avant de parler."
a "\"Non, non, la plus grande partie de la colère est dirigée contre les triumvirates. Je dirai cependant que j'ai du pain sur la planche pour reconstruire ma réputation.\""
m "\"A cause de la vidéo de sexe?\""
a "\"Heh ... oui.\""
"Amicus essaie de sourire avec légèreté, mais je peux voir ses oreilles devenir rouges."
"Ça doit être bizarre d'être dehors en public comme ça, sachant que tout le monde l'a vu."
a "\"L'un des triumvirates de Lux m'a dit de simplement dire que c'était faux ... je ne sais pas si cela fonctionnera.\""
m "\"Cela pourrait être une bonne idée.\""
a "\"Vraiment, le plus gros problème est qu'il délégitime le processus d'alliance avec les Khemians. Les gens croiront que je suis redevable à Neferu d'une manière ou d'une autre.\""
"L'expression d'Amicus tombe finalement un peu, fixant la nourriture alors que son grignotage ralentit."
scene dinner3 with dissolve
m "\"Je suis sûr qu'ils s'en remettront. D'après ce qu'on m'a dit, il semble qu'ils oublient vite.\""
a "\"Eh bien oui, dès que le prochain scandale surviendra, j'espère que celui-ci ne m'impliquera pas.\""
m "\"Ouais.\""
"Nous mangeons en silence un moment, et je peux dire que quelque chose de lourd est dans l'esprit d'Amicus."
"En attendant, je suis un peu distrait par des démangeaisons sur des points spécifiques de mes bras, je sens de minuscules petites bosses sur la peau."
"Je me demande si je suis allergique à quelque chose dans le repas, alors j'arrête de manger pour le moment, choisissant plutôt de me détendre sur le lit."
a "\"[mc], je voulais vous demander quelque chose.\""
m "\"Ouais?\""
a "\"Veux-tu ... veux-tu rester ici, même après que je sois devenu empereur?\""
"La question me surprend, et il ne me reste plus qu'à essayer de rassembler mes pensées pendant un moment alors qu'Amicus continue de baisser les yeux."
m "\"Euh, que voulez-vous dire?\""
"Amicus soupire et me regarde."
a "\"Je veux dire, voulez-vous rester ici avec moi, même si vous avez la possibilité de rentrer chez vous?\""
"Amicus baisse rapidement les yeux."
a "\"Je suis désolé, je sais que ce n'est pas à moi de demander, mais ... j'ai pensé que je ferais mieux de demander.\""
"Je le regarde un instant, puis je baisse les yeux aussi."
m "\"Vous savez que je dois y retourner. À tout le moins, je dois faire savoir à mes amis et à ma famille que je vais bien. Je sais qu'ils me cherchent en Italie en ce moment ... probablement dans toute l'Europe à ce stade. Je dois leur faire savoir.\""
"Amicus tousse à la hâte."
a "\"Bien sûr.\""
m "\"Mais ... cela ne veut pas dire que je ne veux pas revenir. Je fais. Je sais juste que c'est ... qu'il y a des problèmes.\""
"Je baisse la voix en me rappelant que nous sommes dans un lieu public et que mentionner un premier contact illégal ne serait pas une bonne idée."
m "\"Si nous pouvons résoudre les problèmes, honnêtement ... j'aimerais revenir et rester longtemps.\""
"Je me surprends un peu avec cette déclaration, mais c'est vrai."
"Amicus me regarde avec surprise."
a "\"Vraiment?\""
m "\"Ouais, si ce n'était pas un risque pour votre empire.\""
a "\"Bien sûr. Je veux parler aux parents dès que possible. Je suis sûr ... Je suis certain que nous pouvons trouver quelque chose.\""
"Le regard sur le visage d'Amicus en ce moment, si triste, mais un peu plein d'espoir, me rappelle quelque chose que je voulais faire depuis la semaine dernière."
m "\"Et Amicus?\""
a "\"Ouais?\""
"Je jette un coup d'œil autour de moi rapidement, m'assurant que les clients à proximité n'écoutent pas."
m "\"Voulez-vous sortir avec moi?\""
"La déclaration, si ridicule, si idiote dans cette situation, sort toute silencieuse et faible, mais je ne sais pas comment la demander autrement."
"Ce mot est tellement compliqué entre nous maintenant avec la façon dont j'ai essayé de l'expliquer à Amicus."
"C'est quelque chose que je ne pense pas avoir jamais dit à personne auparavant, et tout comme Amicus, je me retrouve immédiatement à regarder vers le bas."
"C'est calme pendant un moment, et le restaurant s'illumine soudainement avec une teinte dorée alors que le coucher de soleil frappe les fenêtres juste à droite."
"J'entends une longue expiration et je me rends compte que le loup retenait son souffle."
"Je lève les yeux alors et vois Amicus me sourire."
scene dinner4 with dissolve
"Il y a un mélange de bonheur et de soulagement sur son visage, peut-être même un peu d'amusement."
"Je suppose que nous dansons autour depuis si longtemps, nous savions tous les deux maintenant que c'est ce que nous voulions, ce que nous avons construit."
a "\"Bien sûr, [mc]. Je suis honoré que vous m'ayez.\""
"Je vois même ses yeux scintiller un peu, et je veux me lever tout de suite et le rejoindre sur son lit, mais le cadre public me retient."
"J'imagine qu'Amicus ressent la même chose, et je me demande si peut-être demander ici en public n'était pas le meilleur endroit pour cela."
"Mais c'était fait, et je me sens sourire malgré moi."
"Le loup sourit tout de suite."
m "\"Comme vous l'avez dit, pendant que je suis ici, nous ferions aussi bien de mieux nous connaître ... et si vous trouvez quelque chose, je peux revenir.\""
"Amicus hoche la tête et tourne la tête de manière à pouvoir essuyer un œil sur son épaule, espérant probablement que je ne le remarquerais pas."
"He looks so relieved, I realize even after we made up in the mediation room he was probably still feeling unsure of where we stood romantically." 
"Il a l'air tellement soulagé, je me rends compte que même après que nous nous soyons réconciliés dans la salle de médiation, il ne se sentait probablement toujours pas sûr de notre position romantique."
m "\"Mais ... il y a des limites, et si je sors avec toi, tu dois tout me dire ... et ne pas dormir dans mon dos.\""
a "\"Bien sûr. J'ai promis de tout vous dire, en particulier tout ce qui vous concerne, et je n'ai jamais l'intention de rompre cette promesse.\""
m "\"Et dormir?\""
"Les oreilles d'Amicus clignotent et il jette un coup d'œil à nos voisins qui essaient DÉFINITIVEMENT d'écouter."
"Il baisse beaucoup la voix."
a "\"Certainement pas, pas que je n'ai personne avec qui être ... mais nous pourrons discuter de tout cela quand nous rentrerons dans notre chambre ... et—\""
"Amicus baisse encore plus la voix."
a "\"Peut-être en faire un peu plus?\""
"Ses oreilles s'aplatissent quand je roule des yeux, mais elles remontent quand je souris."
"\"Je suis sûr.\""
"Immédiatement, sa queue commence à frapper le lit, et le regard impatient sur son visage me fait secouer la tête."
"Je ne peux pas nier que je suis excité aussi ... en fait, je me sens un peu nerveux maintenant que je viens de lui promettre ça."
stop music fadeout 5.0
"Comment pourrions-nous même commencer?"
"Nous restons assis ensemble un peu plus longtemps, la conversation se déplaçant vers des sujets plus informels comme la répartition des quartiers de la ville."
scene bg citynight with fade
play music "sfx/crickets.ogg" fadein 3.0
"Bien qu'une heure passe, je commence à avoir chaud et un peu étourdi, et quand j'en parle à Amicus, il suggère que nous retournions au palais."
"Vita a complètement pris au moment où nous nous dirigeons vers la voiture."
"Bien sûr, plusieurs délégués nous entourent alors que nous commençons à partir, mais Amicus promet qu'il ne restera que dix minutes et je me dirige seul dans la rue pour me tenir à côté du char."
"C'est un peu plus agréable ici en plein air que dans le restaurant étouffant."
"Je peux dire maintenant que je suis définitivement en train de tomber malade, et toute cette douleur et cet épuisement n'étaient que le début d'une fièvre rampante que je peux sentir éclater sur ma peau."
"Je finis par m'asseoir sur le marchepied de la voiture, la tête baissée alors que je me sens commencer à transpirer."
"Ce n'est pas quelque chose que je n'ai jamais ressenti auparavant, mais il y a une étrange sensation de picotement sous tout cela, comme des épingles et des aiguilles juste sous ma peau, me laissant envie de démanger à différents endroits de mon corps."
"Je souhaite juste qu'Amicus se dépêche ... les autres aussi, puisque je suis le seul à rester ici."
"Je ne me souviens même pas où Neferu et Virginia sont allées ... quelque part pour faire du shopping, je pense."
c "\"Simien ...\""
"La voix de Cassius est basse et silencieuse à ma gauche, et je jette un coup d'œil pour le voir se pencher nonchalamment contre le char."
"Je tente sans enthousiasme de m'incliner devant lui, faisant en quelque sorte simplement basculer la tête dans sa direction."
show cas annoyed with dissolve
"Le loup me regarde avant de marcher vers moi."
c "\"A quel jeu jouez-vous?\""
"C'est probablement le pire moment pour que cela se produise."
m "\"Jeu?\""
show cas angry with dis
"Je marmonne stupidement, regardant vers le restaurant pour voir si je peux voir Amicus à travers la foule rassemblée devant."
c "\"N'agissez pas stupide. Je sais que tu es capable de comprendre.\""
"Je secoue juste la tête, mais je le regrette immédiatement car je sens toute la nourriture que je viens de manger me gambader dans l'estomac."
show cas annoyed with dis
"Je suis vraiment malade, bien plus que je ne l'avais réalisé et je ne peux pas croire à quel point ça me frappe fort et vite."
c "\"Vous souvenez-vous il y a plusieurs semaines au cours desquelles vous m'avez servi pendant le repas de midi? Virginia et Neferu étaient là ...\""
"Je reste juste au silence maintenant, inquiet que bouger du tout me fasse hurler."
c "\"Bien sûr, vous vous en souvenez. Vous avez dit aux triumvirates ce que j'avais l'intention d'en faire, n'est-ce pas?\""
"Cassius se rapproche, mais les sentiments qui parcourent mon corps me laissent ne pas trop me soucier de lui en ce moment."
"J'ai besoin d'aller voir Amicus, je dois lui dire que quelque chose ne va pas."
"Je me serre dans mes bras, sentant cette sensation de picotement faire irruption à la surface, ma peau sur mes bras, ma poitrine et mes jambes brûle et me démange de la manière la plus horrible."
show cas paw annoyed with dis
"Je halète."
c "\"Qu'est-ce que c'est, une sorte de langue simienne? Écoutez-moi. Je veux savoir ce que tu leur as dit ... et comment tu as su leur dire.\""
"Je sens des bosses sur mes bras… des bosses qui n'étaient pas là il y a quelques minutes."
"Je regarde en bas et même s'il est difficile de voir dans l'obscurité, je suis au moins capable de voir que la peau est tachée et décolorée."
"En tremblant, je touche l'une des taches et regarde comme une larme de liquide clair suinte."
"Que diable?"
show cas furious with dis
"Quelque chose attrape le devant de mes robes et me tire vers le haut."
c "\" Écoutez-vous, mon animal de compagnie? J'ai dit-\""
show cas surprised with dis
"Je m'inquiétais des petits mouvements, mais cette énorme embardée pousse mon estomac par-dessus bord et j'ai immédiatement projeté du vomi directement au milieu du torse de Cassius."
show cas scared with dis
"Nous regardons tous les deux le désordre sur sa fourrure qui commence à couler lourdement sur ses vêtements."
c "\"Oh ... oh dieux .... OH DIEUX!\""
hide cas with dissolve
"Le loup hurle et en même temps, je vomis à nouveau, au même endroit."
"Cassius trébuche immédiatement en arrière, hurlant alors qu'il agite ses pattes inutilement vers le désordre ... puis commence réellement à vomir."
"Je ne peux pas voir s'il vomit aussi."
"Au lieu de cela, je m'effondre pour m'asseoir sur le sol, sentant le monde tourner autour de moi."
"Heureusement, la prochaine chose que j'entends est la voix d'Amicus."
show ami angry teeth with dissolve
"On dirait que ça vient de très loin, même si je peux dire qu'il est accroupi juste à côté de moi."
a "\"Que lui avez-vous FAIT, Cassius!?\""
c "\"Je n'ai rien fait! Il ... il ... HUUURGH!\""
show ami embarrassed with dis
"J'entends des bruits éclaboussants."
a "\" [mc], que s'est-il passé? Qu'est-ce qui ne va pas?\""
"Je me balance et Amicus me laisse me pencher contre lui malgré mes robes couvertes de vomi."
m "\"Je ne ... je ne sais pas ...\""
a "\" Était-ce la nourriture? Es-tu-\""
"Je tends un bras et je sens le loup l'attraper délicatement, l'examinant."
a "\"Dieux ...\""
"Il marmonne dans sa barbe."
hide ami with dissolve
v "\"Que - que s'est-il passé? Cassius?\""
"J'entends plus de pas et pour une raison quelconque, je me sens gêné que tout le monde me voit comme ça."
c "\"Ce barbare ... urgh ... il a vomi sur moi!\""
"On dirait que Cassius est sur le point de pleurer, et pour une raison quelconque, c'est assez drôle pour moi en ce moment."
"J'essaye de rire, mais j'ai tellement mal à la gorge…»"
a "\"Virginia ... il est malade.\""
n "\"Nous devons le ramener au palais. Montez dans la voiture.\""
a "\"C'est trop lent!\""
"Je sens le monde s'incliner alors que je semble juste léviter du sol ... puis je me rends compte qu'Amicus m'a ramassé."
v "\"Les préteurs ont des véhicules beaucoup plus rapides. Nous pourrions en obtenir un.\""
stop music fadeout 3.0
a "\"[mc]?\""
"J'entends sa voix mais pour une raison quelconque, je ne peux pas répondre ... c'est comme un rêve."
a "\"Il n'y a pas de temps, je suis en courant.\""

scene bg black with slow_dissolve
play music "music/between dimensions.ogg" fadein 3.0
v "\"Amicus!\""
"Je sens mon corps rebondir de haut en bas, jeté à gauche et à droite."
"C'est comme si j'étais dans une sorte de tour à sensations fortes."
"Je tends la main dans l'obscurité pour l'arrêter d'une manière ou d'une autre, mais tout ce que je ressens est quelque chose de velu et de chaud."
"Tout fait mal et démange en même temps."
m "\"Qu'est-ce que ... est-ce que c'est?\""
a "\" [mc] !? Hé, reste avec moi! Je suis ici.\""
"Qui?"
scene bg forestnight with slow_dissolve
"Je force mes yeux à s'ouvrir, même s'ils brûlent tellement."
"Je regarde les choses noueuses au-dessus de moi, et je me demande ce qu'elles sont."
"Tout ce qui me vient à l'esprit, ce sont des mains osseuses et sans peau qui atteignent le ciel."
a "\"Pouvez-vous m'entendre?\""
"Il y a une voix essoufflée et sifflante au-dessus de moi alors que l'horrible et rebondissant trajet continue."
"Je veux juste dormir."
"Il y a un autre son ... un bourdonnement étrange et le tremblement de terre s'arrête enfin."
n "\"Amicus! Entrez, imbécile!\""
a "\"Neferu ... il a des convulsions ... il a des pustules sur tout le corps ...\""
"La voix au-dessus de moi sanglote et halète et je veux tendre la main et mettre une main sur sa bouche pour qu'elle se taise, que je puisse dormir."
scene bg black with slow_dissolve
n "\" Calmez-vous, Virginia a un médecin par avion dans le palais. Tu dois...\""
"Tout redevient clémente."
"Je flotte à travers un vide de nuages ​​silencieux, doux et noirs qui chatouillent et mordillent ma peau."
scene bg bedroom with slow_dissolve
"Ça me démange, et je veux me démanger, mais quelque chose semble me retenir ..."
"J'ouvre les yeux lentement, regardant le plafond."
"Je commence à être vraiment ennuyé de ne pas pouvoir m'endormir."
"J'ai tellement de choses à faire demain ... Nous partons en voyage à Naples, je pense, pour essayer l'authentique pizza italienne."
"Je vais avoir un moment terrible si je ne reçois pas au moins un peu ..."
"Je réalise que je ne peux pas bouger."
"La peur glaciale me saisit la poitrine, et en même temps, je vois quelque chose de grand grimper le long du mur."
"Une araignée géante grimpe vers le haut, son mouvement se détache, comme si une marionnette était tirée par des ficelles."
"Il se déplace à travers le plafond, et même s'il a la taille d'un crabe géant, je ne peux pas ... bouger ... du ... tout. \" "
"\"{i} Les arachnides adastran sont d'une taille inquiétante ... {/ i}\""
scene bg amicusroom
"Je serre les dents alors qu'il s'arrête au-dessus de ma tête ... puis tombe droit sur mon visage, les jambes en éventail ..."
m "\"ARRÊTEZ!\""
"Je l'ai poussé dessus, aux choses qui me pressaient le visage."
"\"Je vous ai dit de le maintenir!\""
a "\"J'essaye! [mc], écoutez-moi, s'il vous plaît! Vous êtes en sécurité, nous vous aidons!\""
"Je me concentre sur les monstres au-dessus de moi, leurs énormes dents blanches et leurs yeux rouges et brillants."
"Leurs horribles mains descendent pour me presser, et je sens la douleur piquante sur toute ma peau."
"Je me débat, mais ça ne sert à rien, ils sont trop forts ..."
scene bg black with slow_dissolve
unk "\"Il a une autre crise ...\""
scene bg citynight with slow_dissolve
"Je m'appuie contre le côté d'un immeuble sur la route déserte."
"La nuit est paisible et calme ... surtout calme, j'entends des claquements au loin ... des sons au galop."
"Je fronce les sourcils et me penche un peu en avant, regardant la route sombre."
"Je vois un cheval courir vers moi, ses yeux rougeoient et crachent des mouches de sa bouche."
"Peur, je me presse plus près du bâtiment, mais le cheval m'ignore."
"Au lieu de cela, alors qu'il passe devant moi, je vois que ça traîne quelque chose ..."
"Un corps sans tête de loup, les bras écartés, la souche laissant une longue traînée rouge sur les pavés."
scene bg amicusroomdim with slow_dissolve
"J'ouvre la bouche pour crier ..."
"\"Nous n'avons rien enregistré pour son espèce.\""
a "\"Puis profilez-le.\""
"\"Y a-t-il une raison pour laquelle nous ne le faisons pas?\""
a "\"Guérissez-le ... s'il vous plaît. C'est juste avia pox ...\""
scene bg black with slow_dissolve
"\"Eh bien, clairement, cela a un effet différent sur son espèce. Son système nerveux est déjà irrémédiablement endommagé. Vous devriez considérer ...\""
scene bg space with slow_dissolve
"..."
unk "\"Les choses ne semblent jamais se dérouler comme prévu, n'est-ce pas?\""
"..."
scene watching with slow_dissolve
unk "\"Je suis désolé que vous ayez dû faire l'expérience de cela ... Je ne l'avais pas prévu.\""
unk "\"Ne vous inquiétez pas ... vous êtes toujours sur la bonne voie.\""
unk "\"Vous pourrez terminer cette tâche.\""

jump a2s1