label a2s1:
"..."
unk "\" Comprenez que ce ne sera pas facile, même pour les parents. \""
unk "\" La douleur sera temporaire. \""
"Que ce passe-t-il?"
"..."
unk "\" Vous saurez à temps ... mais pas encore. \""
scene bg black with slow_dissolve
"Le temps perd son sens."
"La noirceur ... à la fois éternelle et inexistante."
"Les cauchemars vont et viennent, se construisent et disparaissent."
"Des scènes de ma plus tendre enfance à mon atterrissage sur Adastra, toutes déformées par des images horribles et violentes qui ne se sont jamais produites."
"Mais dès que chacun se termine, j'oublie, comme n'importe quel autre rêve ... sauf un."
scene bg spaceship with slow_dissolve
play background "sfx/spaceshipinterior.ogg" fadein 3.0
"Je suis blotti sur le siège du navire, glacial, engourdi par le désespoir et la peur d'une mort imminente."
"Comment cela m'arrive-t-il?"
"Qu'ais-je fait pour mériter cela?"
"Je jette un coup d'œil à la forme froissée du loup à l'arrière du navire."
"Sa tête est encadrée par une mare de sang, le tuyau métallique à quelques mètres de là où je l'avais laissé tomber."
"J'ai fais une grosse erreur."
"La colère et la terreur que je ressentais depuis plusieurs heures, jours…»"
"...semaines?"
"... se construit jusqu'à ce que je hurle et que je brise mes deux poings sur les panneaux lumineux devant moi."
play sound "sfx/firestart.ogg"
play background "sfx/starrumble.ogg"
scene bg spaceshipstar at my_shake with dissolve
"La prochaine chose que je sais, la lumière souffle à l'intérieur du navire et je me couvre le visage avec mes mains."
"Pourtant, la lumière perce à travers et je vois rouge sang."
"Le vaisseau vibre violemment, et je sais tout de suite que nous y sommes entraînés."
"Je tends la main malgré la lumière impossible, martelant inutilement les panneaux qui ne répondent pas."
"Après quelques instants, la luminosité et la chaleur deviennent insupportables, et je me jette finalement au sol, rampant loin, rampant vers mon loup."
m "\" Amicus, AIDE! \""
scene bg white with slow_dissolve
stop background fadeout 5.0
"Mais la lumière continue de croître, et bientôt tout s'éclaire d'un blanc aveuglant, la chaleur si intense que le métal fond sous mes mains et mes genoux."
"Je suis en feu ... Je {i} suis {/ i} en feu. Je sens des lignes de plomb fondu traverser de la base de mon cou, le long de ma colonne vertébrale, se ramifier dans mes membres, même mes orteils et mes doigts . "
"Je ne peux que flotter dans l'enfer, me demandant bêtement pourquoi je me sens toujours mort, me demandant si cela {i} est {/ i} la mort en tant que vaisseau, loup, et je deviens une partie de l'étoile.\""
"Encore une fois, le temps est perdu et je n'existe que sous forme de feu."

scene bg islandnight with slow_dissolve
play loop "sfx/lakesounds.ogg" fadein 5.0
"Je regarde le ciel, l'air se refroidit soudainement alors que j'essaie de comprendre le changement soudain de la lumière dure et dévorante des étoiles au clair de lune doux et froid."
"Pourtant, le feu continue de jaillir à travers ma tête, mon cou, ma colonne vertébrale et mes membres en lignes angoissantes, mon corps tracé comme un bâton torturé."
"Ça fait mal ... ça fait plus mal que tout ce que j'ai jamais vécu, mais ça s'estompe après ce qui s'est passé dans l'étoile, alors j'essaye de me détendre dans le sable."
"Au bout de quelques minutes, je me rends compte que je peux entendre les vagues, et je sens quelque chose qui me tire vers l'eau."
"J'ai un peu peur de me lever, de tout mouvement, terrifié à l'idée que cela puisse déclencher à nouveau la douleur ... mais ce n'est pas le cas."
"J'ai presque l'impression que je ne bouge pas du tout."
scene bg lakenight with dissolve
"Je glisse vers l'eau, regardant la surface refléter la planète brillante et la lune en ondulations hypnotiques."
"Entrer dans le lac et sentir l'eau froide et douce sur ma peau est la meilleure sensation que j'aie jamais ressentie."
"Il m'enveloppe lentement, remontant mes jambes, mon torse et enfin ma tête, et juste comme ça, la douleur et le feu sont chassés, soumis à un battement sourd et picotant."
"Je halète de soulagement, capable de respirer sous l'eau."
"Je dérive dans l'eau sombre, regardant les globes de lumière danser et se balancer au-dessus de moi avant de finalement refaire surface."
"Ce n'est qu'alors que je me souviens d'Amicus."
"La peur me saisit."
"Était-il toujours sur ce navire?"
"Est-ce que je l'ai laissé dans l'étoile?"
"Je lève les yeux et vois les lumières scintillantes du palais et je commence à nager vers lui, en me déplaçant beaucoup plus vite que je ne devrais pouvoir le faire."
"Au lieu de nager jusqu'à la plage, je finis par me diriger vers le balcon, directement dans la chambre d'Amicus."
"En me rapprochant, je me rends compte que quelqu'un EST sur le balcon."
"C'est Amicus, et mon cœur se remplit de soulagement."
"Il a le dos à la balustrade, s'appuyant contre elle avec désinvolture."
"Même si je ne peux le voir que de derrière, je me rends compte que ce n'est pas l'Amicus que je connais."
"Au lieu de cela, il est en robe pleine, et il est beaucoup plus maigre que je ne me souviens."
"Je ralentis, me demandant pourquoi il ne me regarde pas avec tous les bruits d'éclaboussures que je fais."
"Juste au moment où je suis sur le point de l'appeler, je vois des bras bruns s'enrouler autour de lui, se lissant sur ses bras et son dos et c'est à ce moment qu'Amicus se tourne sur le côté."
"Je vois maintenant que ces bras appartiennent à un autre loup, plus petit et à fourrure brune, un loup que je n'ai jamais vu auparavant."
"Amicus lui fait la même chose, ses pattes se déplaçant autour de son corps d'une manière qui est maladroite et hésitante ... une paire de jeunes amants s'embrassant pour la première fois."
"Je regarde, me sentant soudainement embarrassé."

scene bg amicusroom with dissolve
stop loop
"Je suis de retour dans la chambre d'Amicus, et ce même loup adolescent est maintenant sur le canapé, penché, cachant son visage derrière ses pattes."
"Je n'ai jamais vu Amicus vraiment pleurer, mais je peux dire que c'est ce qu'il fait maintenant."
"Je ressens le sentiment de honte totale et absolue, le sentiment que vous avez laissé tomber tout le monde."
"Cela me consume."
"Je tend la main vers le jeune loup, voulant le réconforter, me demandant s'il saura même qui je suis."

scene bg space with dissolve
"Soudain, je suis aspiré dans le cosmos."
"Il n'y a pas de parent cette fois."
"Au lieu de cela, je flotte paisiblement à travers le vide, fixant ce que je suppose être Adastra."
"Même s'il n'y a personne ici avec moi, je sens des êtres tout autour de moi."
stop music fadeout 10.0
"J'ai aussi un sentiment d'approbation, comme leur travail est terminé."
"\" Achevez le travail de Meera, jeune humain ... \""
"Juste comme ça, je commence à redescendre vers la lune, descendant de plus en plus vite jusqu'à ce que tout devienne flou."

scene bg garden2night with transition_fade
play loop "sfx/crickets.ogg" fadein 3.0
"Cette fois, venir me semble réel, et je sais immédiatement que je ne suis pas dans un rêve."
"Je sens la lavande."
"Amicus?"
"Mes yeux ont l'impression qu'ils sont collés et je dois les frotter pour les ouvrir complètement."
"La première chose que je vois est le ciel, la planète {i} Ancoris {/ i} et la lune {i} Torque {/ i}, tous deux brillants."
"Je regarde les deux orbes flottants pendant un moment, attendant que les choses se mettent en place pour savoir pourquoi je suis ici."
"Je m'allonge sur quelque chose de dur, comme du béton, et je sens des choses douces mais lourdes sur ma poitrine."
"Mes mains sont enroulées autour, et je le soulève lentement pour jeter un coup d'œil, même si cela ressemble à un haltère de 50 livres."
"Fleurs..."
"Des fleurs avec un peu de lavande mélangées."
"Lentement, je tourne la tête et encore une fois, j'ai la sensation de poids lourds attachés à mon corps."
"Je le gère d'une manière ou d'une autre et vois immédiatement que je suis dans l'amphithéâtre."
"En même temps, je vois plus de fleurs et je me rends compte qu'elles sont disposées tout autour de moi en cercle."
"Bouger ma tête me fait aussi réaliser qu'il y a quelque chose de gratté et de piquant sur ma tête."
"Toujours en train de lutter avec ma main lourde, je tends la main et je l'attrape."
"Je le soulève de ma tête et le tiens devant mon visage, mes yeux prenant quelques instants pour se concentrer pour découvrir que c'est une couronne, des fleurs roses tissées dans les brindilles."
"J'ai finalement laissé tomber mon bras sur le côté, devenant trop fatigué pour le tenir et je le regarde rouler paresseusement à quelques mètres."
"Le mouvement envoie une vague de picotements à travers mon corps, mais il s'estompe rapidement"
"La lourde faiblesse commence également à s'estomper, mais je suis plus inquiète de savoir comment je suis arrivé ici et pourquoi je suis couvert de fleurs."
"D'après ce que je peux dire, je suis dans les jardins, même si je n'ai jamais visité une partie auparavant."
"Je ferme les yeux, essayant de me rappeler comment je suis arrivé ici."
"Amicus ... le procès de la rhétorique ... le restaurant ... étant malade."
"Encore une fois, je lève le bras, même si c'est plus facile cette fois, et je regarde la peau."
"Il est couvert de croûtes croustillantes et jaunes, même si elles ne font pas mal."
"Je ne sais pas pourquoi, mais j'ai le sentiment que la peau en dessous est complètement guérie."
"J'essaye de réfléchir à nouveau."
"Je me souviens d'avoir vomi sur Cassius, mais après ça ... juste de terribles rêves."
"Est-ce qu'ils m'ont guéri d'une manière ou d'une autre?"
"Est-ce que ce truc de fleur en fait partie?"
"Je sens une partie de ma force revenir, alors je me force à me mettre en position assise, les articulations éclatent et les muscles raides."
"Pourtant, à chaque mouvement, les choses deviennent plus faciles."
"Je deviens étourdi cependant, et je dois m'asseoir là pendant un moment, regardant à nouveau autour de moi, me demandant où est Amicus."
"Il avait l'air si désespéré et triste la dernière fois que je l'ai entendu."
"J'ai besoin de lui montrer que je vais bien maintenant… du moins je pense que je le suis."
"Je me relève lentement, écoutant les craquements par balle de mes genoux, comme si je ne les avais pas utilisés depuis des jours."
"Je me tiens instablement au centre de la place, regardant le cercle de fleurs."
"Je suis surpris quand je me retourne et vois un loup derrière moi ... mais ce n'est qu'une sculpture."
"Un loup mâle habillé d'une armure, les deux pattes levées vers le ciel."
"Il a un bouquet de fleurs tissées autour de ses poignets et sur sa tête aussi."
"J'attends quelques instants, à l'écoute de tous ceux qui pourraient être à proximité."
"Tout ce que j'entends, ce sont les insectes autour de moi."
"Alors, je commence à me diriger vers le chemin qui, je le sais, mène au palais."
"Bien que je sois à peu près sûr que je ne rêve pas maintenant, ce scénario étrange me fait remettre en question cela."
"Toute la situation est surréaliste."
"Toutes les choses dont je me souviens pour la dernière fois me semblent si éloignées."
"Bien que j'aie passé tout mon temps sur Adastra à essayer d'être secrète, je me retrouve à avoir envie de trouver quelqu'un, vraiment n'importe qui."
"J'ai juste besoin de savoir ce qui s'est passé."
"Et bientôt, je trouve quelqu'un."
"Il me tourne le dos, penché, fourrure presque fantomatique à la lueur des lumières du jardin."
"Le chat s'occupe de quelques fleurs, une paire de tondeuses en métal dans ses pattes."
"Alors que je me rapproche, je peux l'entendre fredonner juste au-dessus du bruit de sa capture occupée."
"J'ouvre juste la bouche quand je vois ses oreilles se redresser."
al "\" Cass? Tu sais que je n'aime pas ces jeux. \""
show ale with dissolve
"Alex se tourne pour me faire face, un sourire entendu sur ses lèvres."
show ale shocked with dis
"Cela disparaît rapidement à la seconde où il me voit, remplacé par un regard de choc complet."
al "\" Ah— \""
"Tout ce qu'il essayait de dire ne semble pas vouloir sortir, et à la place, il se tient juste là, me regardant bouche bée."
m "\" H — hé ... \""
"Je peux à peine parler, ma voix rauque comme du papier de verre sur du bois."
"Je fais un pas en avant et c'est alors qu'Alex réagit enfin, sautant de près d'un pied en l'air dans un mouvement vers l'arrière, mettant de l'espace entre nous alors qu'il hurle."
show ale vshocked e at jumping with dis 
al "\" Quoi ... quoi !? Comment!?\""
"Il bégaye et trébuche sur ses mots."
"J'ai déjà vu Alex énervé, mais jamais comme ça."
"Il y a une vraie peur dans ses yeux alors qu'il trébuche contre des buissons."
"Je me demande s'il va simplement décoller en courant, mais à la place il se tient là, tremblant alors qu'il tient la tondeuse devant sa poitrine, comme s'il envisageait de les utiliser comme une arme."
"Je lève les mains de manière rassurante."
m "\" Hé ... Alex, c'est moi ... \""
"Je tousse plusieurs fois, essayant de m'éclaircir la gorge."
"Je vois les oreilles d'Alex trembler au son alors qu'il abaisse lentement la tondeuse, bien qu'il se déplace du côté éloigné du buisson, se donnant un chemin clair vers le palais."
show ale shocked e with dis
al "\" [mc]? Mais comment?\""
"Il me regarde comme si ce qu'il voit est impossible."
m "\" Comment quoi? \""
"Je retrouve ma voix lentement, mais sûrement."
m "\" Que se passe-t-il? \""
"Alex semble enfin se ressaisir, sa fourrure se reposant lentement à nouveau alors qu'il me regarde, l'air presque méfiant."
show ale serious with dis
al "\" Je pourrais vous demander la même chose. \""
"Cela me prend au dépourvu."
m "\" Pourquoi? \""
al "\" Eh bien ... \""
"Alex regarde autour de lui avant de se concentrer à nouveau sur moi, inclinant la tête, comme pour me regarder sous un angle différent."
show ale tilt with dis
al "\" Vous étiez ... vous étiez mort. \""
m "\" Mort? \""
al "\" Eh bien, pas complètement, mais vous étiez dans le coma dont on nous a dit que vous ne vous réveilleriez pas. \""
m "\" Oh. \""
"Je me regarde, comme pour confirmer que je suis bel et bien vivant."
"Mis à part les croûtes inégales sur mes bras et mes jambes, je me sens bien, mis à part le grogginess."
m "\" Je pensais que le médecin m'avait guéri. \""
"Les oreilles d'Alex sont un avantage."
show ale shocked with dis
al "\" Docteur? \""
m "\" Je veux dire, je pense qu'il y avait un médecin ... Je l'ai entendu quand j'ai été ramené ici. \""
show ale serious with dis
"Les yeux d'Alex se rétrécissent."
al "\" Amicus nous a dit que vous étiez végétatif avant son arrivée, comment l'avez-vous entendu? \""
m "\" Je ... je ne sais pas, j'aurais pu le rêver. J'étais vraiment hors de moi. \""
al "\" Si vous étiez encore conscient quand il est arrivé, il aurait dû être en mesure d'arrêter les dégâts causés par le virus. Qui était le médecin? \""
"À chaque seconde qui passe, je retrouve de plus en plus de sens, et le comportement d'Alex me déroute."
"Il pensait que j'étais mort, et au lieu d'être heureux, j'ai l'impression qu'il m'interroge."
"C'est aussi là que je réalise autre chose:"
m "\" Attendez, vous pensez tous que je suis mort? \""
show ale tilt w with dis
al "\" Eh bien, plus moi, évidemment. Tout cela est très étrange ... comment as-tu survécu, exactement? \""
"Maintenant, le chat commence à m'ennuyer, et je regarde au-delà de lui vers le palais, la situation se pose enfin sur moi."
m "\" Où est Amicus? \""
"Le chat est silencieux pendant un moment, comme s'il contemplait quelque chose, puis fait un mouvement de tête."
al "\" Je ne suis pas sûr. Il a été ici et là, même si je ne l'ai pas vu depuis au moins un jour. \""
"Je passe devant le chat, vers le palais, réalisant dans quel état le loup pourrait être."
show ale with dis
al "\" Où vas-tu? Je suis très content de voir que tu vas bien. Tout cela est très soudain et inattendu. \""
"J'ignore Alex, pas vraiment d'humeur à comprendre pourquoi il agit ainsi."
"Il me donne l'impression que je rêve toujours."
hide ale with dissolve
"Alors je marche vite et je suis soulagé qu'il ne me suive pas."

scene bg palace1night with dissolve
"La vague d'air frais qui me frappe lorsque j'entre dans le palais est un sentiment de bienvenue, et je me sens reconnaissant d'être de retour."
"Bien qu'ayant apparemment été ici tout le temps, j'ai vraiment l'impression d'être absent depuis des semaines."
"Je accélère le rythme alors que je me dirige vers la chambre d'Amicus, pratiquement en train de courir."
"Je dois lui faire savoir que je vais bien."
"La courte distance qui mène à sa chambre semble prendre plus de temps que jamais auparavant, et je suis heureux de ne rencontrer personne d'autre en chemin."
"Cette interaction avec Alex était bizarre et je n'ai pas besoin de répéter ça pour le moment."
"Je suis enfin arrivé à sa porte et j'entends immédiatement des bavardages étouffés derrière."
"Je n'hésite pas cependant, et je presse ma main sur le panneau."
play sound "sfx/dooropen.ogg"
stop loop fadeout 3.0
scene bg amicusroomdim with dissolve
"La porte s'ouvre, et au lieu du souffle habituel d'air encore plus froid que je recevais souvent de la chambre d'Amicus, c'est étouffant, chaud et l'odeur un peu musquée."
"Les lumières sont tamisées et mon cœur se serre quand je vois le lit vide."
"Je m'attarde dans l'embrasure de la porte, quelque chose ne va pas."
"Le bavardage bourdonnant est Com, donnant ce qui ressemble à un monologue sur l'histoire d'un ancien empereur."
"Je vois aussi des bouteilles de vin, pour la plupart regroupées sur la table de chevet, mais il y en a aussi quelques-unes qui traînent ici et là sur le sol."
m "\" Amicus? \""
"J'appelle, commençant à avoir peur de ce que je pourrais trouver."
"Je fais quelques pas provisoires dans la pièce, puis j'entends un fort ronflement et instantanément, l'inquiétude agrippant ma poitrine commence à se libérer."
"Je reconnaîtrais ce son n'importe où."
"Je me dépêche de l'autre côté du lit où je trouve mon loup étalé sur le sol, une bouteille de vin à côté de sa tête, uniquement en sous-vêtements."
"Il est clairement endormi ... ou évanoui, le museau grand ouvert alors qu'un autre ronflement tonitruant secoue le sol."
m "\" Amicus! \""
"Je m'accroupis à côté de lui, posant une main sur sa poitrine, essayant de le secouer pour le réveiller."
"Sa seule réponse est quelques reniflements brisés supplémentaires avant de baver sur le côté de son museau."
"Je me suis mis à lui caresser le visage, puis à attraper son museau et à le secouer, remarquant à quel point la fourrure est croustillante, quelque chose que je n'avais jamais ressenti sur Amicus auparavant."
m "\" Amicus! \""
"J'envisage de le gifler comme j'ai vu des gens le faire dans les films, puis je vois la bouteille à côté de sa tête et décide d'opter pour une autre approche."
"Je le prends et je me dépêche d'aller à la salle de bain."
scene bg bathroom with dissolve
"Je tiens la bouteille sous le robinet pendant cinq bonnes secondes, la laissant se remplir d'eau savonneuse jusqu'à mi-chemin avant de me dépêcher de retourner dans la pièce."
scene bg amicusroomdim with dissolve
"Pendant ce temps, Com ne semble pas me remarquer, ronronnant sur la façon dont cet empereur en particulier était connu pour avoir un penchant pour les orchidées."
"Je m'accroupis à nouveau à côté d'Amicus, hésitant une seconde alors que je me demande si je devrais peut-être appeler Cato ... probablement pas Cato ... Neferu peut-être, juste au cas où Amicus aurait des ennuis."
"Je ne sais pas combien un loup peut boire avant de pouvoir les tuer, mais la quantité de bouteilles qui traînent dans la pièce m'inquiète."
"Je décide d'aller de l'avant avec mon plan, et je retourne la bouteille sur le visage d'Amicus."
"Il se déverse directement sur son nez et il s'étouffe aussitôt, tournant la tête de cette façon et cela pour éviter le jet d'eau bouillonnante."
"J'ai un moment pour me demander si le noyer est la meilleure approche avant qu'il ne se redresse soudainement, lui caressant le visage."
show ami frustrated u with dissolve
a "\" Gah! \""
"Le loup se couvre les yeux et ce n'est qu'alors que je réalise à quel point le savon pourrait être irritant pour eux."
m "\" Merde, désolé! Dois-je prendre de l'eau de la douche pour que vous puissiez vous rincer les yeux? \""
"Amicus se fige, couvrant toujours son visage, puis abaisse lentement ses pattes pour révéler ses yeux larmoyants et injectés de sang."
show ami surprised u with dis
play music "music/light years apart.ogg" fadein 5.0 noloop
"Il me regarde d'une manière qu'il n'a jamais fait auparavant."
"C'est un peu surpris comme Alex l'avait été, mais plutôt que de peur, Amicus a simplement l'air vide, engourdi."
m "\" Ça va? \""
"Je tends la main, mais Amicus détourne la tête."
show ami cringe u with dis
a "\" Loin de vous fantôme ... assez de votre tourment. \""
"Il garde la tête détournée, les yeux fermés."
m "\" Ghost? Amicus, c'est moi. \""
"Je tends la main et attrape son visage, et cela semble le choquer alors qu'il saute et se retourne pour me regarder droit dans les yeux."
show ami shocked u with dis
"Je peux dire qu'il est ivre, très ivre, mais il y a un regard très lointain dans ses yeux que je n'aime pas."
show ami surprised u with dis
m "\" Amicus ... sur quoi êtes-vous? Avez-vous pris quelque chose? \""
"Je tiens sa grosse tête stable, sentant la plénitude de ses joues dans mes mains, regardant dans ses yeux familiers, peu importe à quel point ils sont vitreux et flous."
hide ami with dissolve
"Puis je me retrouve à jeter mes bras autour de son cou et à me pencher contre son corps, la réalité de la situation m'écrasant d'un seul coup."
"Amicus halète dans mon oreille, comme si mon contact lui faisait soudainement réaliser que je suis réel, que je suis là."
"Maladroitement, il commence à se lever, me tirant avec lui."
"C'est difficile parce que je ne lâche pas prise, je suis presque soulevé de mes pieds avant de me décider à lâcher prise juste un instant pour le serrer dans mes bras plus bas, autour de son corps, pressant ma tête contre sa poitrine, entendant son cœur battre à l'intérieur."
"Enfin, il est capable de me saisir et de me repousser malgré mon intention de m'accrocher à lui pour toujours."
"Il me tient à bout de bras, me regardant."
"Je serre ses pattes sur mes épaules, le regardant, sentant mes yeux commencer à pleurer."
show ami embarrassed u with dissolve
a "\" Est-ce que ... est-ce possible? Est-ce que ... non, s'il vous plaît, je ne peux pas supporter une autre hallucination. \""
"Son expression ne cesse de passer de l'espoir et de la crainte à la dévastation."
"Je sens ses pattes s'agripper fermement à mes épaules, presque douloureusement, comme pour m'assurer que je suis réel."
m "\" C'est moi! Je me suis réveillé dans le jardin pour une raison quelconque, je vais bien ... \""
"Je veux le serrer dans mes bras à nouveau, mais il continue de me retenir, me regardant de haut en bas, repoussant mes cheveux et sentant ma peau croustillante."
a "\" Mais ... mais comment ... \""
m "\" Je ne sais pas. Je me souviens juste d'avoir fait des rêves fous, puis j'étais dans le jardin. \""
stop music fadeout 10.0
show ami surprised u with dis
"Pendant que je parle, je pense qu'Amicus croit enfin que c'est moi ... et je remarque que son corps commence à se balancer de manière inquiétante."
m "\" Amicus? \""
"Je tends la main pour le stabiliser, mais comme je le fais, ses yeux roulent en arrière et je réalise qu'il n'y a aucun moyen que je puisse empêcher un loup de plus de deux fois mon poids de basculer."
hide ami with dissolve
"J'essaye quand même, enroulant mes bras autour de lui alors qu'Amicus tombe en arrière, sa masse me tirant vers le bas avec lui avant qu'il ne retombe le premier sur la table de chevet, envoyant des bouteilles voler tandis que son haut du dos et sa tête se cognent contre le mur."
play sound "sfx/thud5.ogg"
with vpunch
"Ma chute est absorbée par sa façade beaucoup plus douce, mais le son est fort, la pièce tremble et réveille probablement tout le palais."

scene bg amicusroom with fade
play music "music/dawn.ogg" fadein 3.0
"Réveiller le loup pour la deuxième fois est beaucoup plus facile, probablement parce qu'il s'est évanoui plutôt que de s'évanouir à cause de trop de vin."
"Nous sommes au moins capables de nous déplacer sur le lit où Amicus est assis les jambes croisées, me tirant sur ses genoux et me tenant juste là, ses pattes bougeant autour de mon corps, essayant toujours de m'assurer que je suis réel."
"Pendant un moment, nous ne parlons pas, le loup vient d'appuyer son nez contre mes cheveux et de respirer profondément."
"Je me sens un peu gêné, sachant que je ne dois pas sentir très bon pour le moment, mais cela ne semble pas déranger Amicus alors qu'il continue d'appuyer son nez contre ma tête et mon cou, absorbant mon odeur."
"Enfin, il parle, mais c'est un mot:"
show ami embarrassed u with dissolve
a "\" Comment? \""
"Je tourne la tête vers le loup, posant ma joue contre son cou."
m "\" Je ne sais pas. Je ne sais même pas vraiment ce qui m'est arrivé. \""
a "\" Vous êtes tombé malade ... tellement malade. Vous aviez des convulsions, des lésions cérébrales et nerveuses, c'était ... c'était terrible. \""
show ami sad u with dis
"Les bras d'Amicus se resserrent autour de moi, sa voix, normalement profonde et forte, sonne maintenant faible et brisée."
"Cette déclaration m'inquiète cependant, et je dois me demander si je vais vraiment mieux."
"Il semble qu'il y ait des patchs manquants dans ma mémoire, et je me sens différent, comme si je ne suis pas complètement moi-même, mais je ne veux pas vraiment y penser maintenant."
m "\" Je pense que je m'en souviens un peu. J'ai eu-\""
"Je lève mon bras, montrant à Amicus les croûtes brillantes et croustillantes sur mon bras."
show ami embarrassed u with dis
a "\" C'était la variole aviaire, je - je ne peux pas croire que je n'ai pas envisagé la possibilité d'une maladie ou d'une maladie pour vous. Je suis tellement habitué à l'idée que toute nouvelle arrivée sur Adastra passe par ce processus ... évidemment, nous l'avons fait un peu différemment. \""
m "\" Ouais ... \""
show ami crossed serious with dis
a "\" Et honnêtement, je ne suis même pas sûr que vous le fassiez. Je ne sais pas si vous réagiriez différemment à ces vaccinations ... chaque espèce a son propre cocktail personnalisé. "
show ami embarrassed u with dis
a "\" Et la variole aviaire n'est pas incluse dans le kit de vaccination. C'est un virus si bénin que nous n'avons jamais vu personne réagir comme vous, même les autres primates. \""
"Je repense à la rapidité avec laquelle je suis tombé malade, à quelle vitesse j'ai failli mourir."
"Je remarque qu'Amicus me regarde à nouveau et je le regarde."
m "\" Quoi? \""
show ami sad u with dis
"Amicus secoue la tête."
a "\" J'essaie toujours de m'assurer que vous êtes ici, que vous êtes réel ... Je - j'ai peur que si je lâche prise, si je détourne même le regard, vous disparaîtrez. \" "
"Ses bras se resserrent à nouveau autour de moi, me tirant un souffle."
m "\" Je suis là, je le promets. \""
show ami crossed serious u with dis
a "\" Eh bien, j'ai eu beaucoup d'hallucinations; trop de comprimés anti-stress je pense. \""
m "\" Comprimés anti-stress? \""
a "\" Oui, un bon nombre d'entre eux en fait. \""
m "\" Avec du vin? \""
show ami eyes u with dis
a "\" Oh oui. \""
m "\" Amicus! \""
"Je ne sais pas vraiment ce que sont ces comprimés anti-stress, mais j'imagine que mélanger l'espace Xanax avec de l'alcool est une idée horrible."
"Amicus ne semble pas gêné par ma réprimande, au lieu de cela, se blottissant plus près de moi, son visage en croûte piquant contre ma peau."
show ami u with dis
a "\" Je t'aime, [mc]. \""
"J'ai cette sensation familière de piqué dans ma poitrine, comme si j'étais sur des montagnes russes."
"Je m'agrippe à ses bras."
m "\" Je t'aime aussi. \""
"Amicus soupire et pose son menton sur ma tête."
show ami embarrassed u with dis
a "\" Je pensais avoir raté l'occasion de le dire ... Je n'arrive toujours pas à croire que tu es réel. \""
m "\" Eh bien, je le suis. Je promets.\""
a "\" Mais je ne comprends toujours pas comment. Cela ne devrait pas être possible. On a déclaré que vous étiez dans le coma permanent, aucune activité cérébrale ... Je devais vous installer dans le jardin et n'espérer qu'un miracle. \""
m "\" Miracle? \""
"Amicus laisse échapper un soupir tremblant, passant ses doigts dans mes cheveux."
show ami sad u with dis
a "\" Lorsqu'un sapient tombe dans un tel état, nous le laissons simplement ... disparaître dans un cadre paisible, ou peut-être récupérer si le parent le permet. \""
a "\" Je suis resté assis là pendant un moment, mais je ne pouvais pas supporter de vous voir dépérir, alors je suis revenu dans ma chambre pour boire et me préparer à l'empereur. \""
"J'imagine Amicus déposant ces fleurs autour de moi et je sens mon cœur se briser un peu."
a "\" Est-ce que ... les parents sont venus vous voir, est-ce pour cela que vous êtes ici? J'espérais qu'ils le feraient. \""
"Je hausse les épaules."
m "\" Je ne me souviens vraiment pas de grand chose. \""
show ami serious u with dis
a "\" Ce n'est pas grave. Mes prières ont été exaucées, louez les dieux. \""
"Amicus recommence à m'étouffer avec son étreinte."
"De petits fragments d'images de mes rêves commencent à me revenir."
"Quelque chose qui s'est passé dans l'espace, quelqu'un me parle."
show ami crossed u with dis
a "\" Et à en juger par le seul humain que je connaisse, votre peuple est plein de surprises. Mais nous pouvons le découvrir plus tard ... Je veux juste te tenir dans tes bras maintenant. \""
m "\" D'accord. \""
a "\" ... et [mc]? \""
m "\" Ouais? \""
a "\" Veuillez éviter de mentionner que j'ai ... perdu connaissance en vous voyant. \""
m "\" Bien sûr. \""
"Alors nous restons assis là pendant un moment plus longtemps pendant qu'Amicus me fait des câlins en quelque sorte."
stop music fadeout 5.0
"Après environ une heure, nous décidons finalement de passer à la douche, compte tenu de l'état dans lequel nous sommes tous les deux."

scene bg bathroom with fade
play loop "sfx/showerloud.ogg" fadein 3.0
"Nous nous douchons ensemble, nous nous frottons à tour de rôle."
"L'eau chaude redonne vraiment vie à mes membres, et ces picotements inquiétants se sont estompés au point que je les remarque à peine maintenant."
"Amicus frotte doucement ma peau en croûte, et nous sommes tous les deux surpris de la voir disparaître, exposant une nouvelle peau sans tache en dessous."
show ami surprised n with dissolve
a "\" Incroyable. Je n'ai jamais su que les humains guérissaient à un tel rythme. \""
m "\" ... Ouais. \""
"Je ne sais pas si c'est vraiment le cas, et mon esprit continue de revenir à ces rêves vagues et difficiles à retenir que je faisais."
show ami eyes n with dis
"Pendant ce temps, Amicus s'appuie contre le mur alors que je frotte du savon sur son front, souriant doucement alors que je mousse sa poitrine."
"Je peux dire qu'il est encore assez ivre, mais cela n'empêche pas sa bite de se dresser complètement entre nous, ce que je fais juste semblant de ne pas remarquer."
"Ses yeux s'écarquillent comme s'il réalisait soudainement quelque chose."
show ami surprised n with dis
a "\" Attendez, est-ce que quelqu'un d'autre vous a remarqué? \""
"Je fais une pause, mes deux mains prenant ses gros pectoraux."
m "\" Ouais, en fait. Alex était dans le jardin et je lui ai parlé. \""
a "\" Juste Alex? \""
m "\" Ouais. \""
"Amicus semble se détendre un peu."
show ami serious n with dis
a "\" Qu'a-t-il dit? \""
m "\" J'ai juste semblé vraiment surpris - \""
a "\" Sans surprise. \""
m "\" - mais il agissait un peu bizarrement. \""
"Amicus hausse les épaules."
a "\" Il garde les choses pour lui pour la plupart. Je serais inquiet si vous tombiez sur Cato, ou Cassius en particulier. J'ai besoin de réfléchir à un moyen de leur expliquer cela. Cette apparence simienne est de plus en plus difficile à suivre. \""
show ami happy eyes n with dis
"Je suis sur le point d'en dire plus sur le comportement d'Alex, mais c'est à ce moment-là qu'Amicus recommence à me serrer dans ses bras, sa bite, chaude et ferme, s'écrasant entre nous comme il le fait."
"Je m'en fiche cependant, et Amicus ne semble pas non plus."
a "\" Je ne comprends rien de tout cela pour le moment, mais tant que c'est réel, je m'en fiche. \""
stop loop fadeout 3.0
"C'est si bon comme ça, sa fourrure mouillée glisse étroitement contre son corps épais qui se presse parfaitement contre moi."
play background "sfx/showerfan.ogg" fadein 3.0
hide ami with dissolve
"Amicus coupe finalement l'eau et nous sommes bombardés d'air chaud."
"Je suis séché en moins d'une minute et je trébuche pour essayer de fixer mes cheveux poofy dans le miroir pendant qu'Amicus reste un peu plus longtemps dans la cabine de douche."
stop background fadeout 5.0
"Après encore quelques minutes, je le regarde sortir et venir derrière moi pour me museler les oreilles, m'embrassant à nouveau."
"Il ne peut vraiment pas garder ses pattes loin de moi, mais je comprends parfaitement pourquoi."

scene bg amicusroomdim with dissolve
"Il commence à me pousser dans la chambre, avant de me tourner pour lui faire face, en baissant son visage vers le mien ... et je réalise enfin où cela va."
"C'est si soudain, surtout après tout ce qui s'est passé, je pense que nous pourrions utiliser plus de temps pour nous ajuster ... mais je m'embrasse quand même."
"Nous nous sommes embrassés quelques fois auparavant, mais seulement avec nos lèvres."
"Maintenant, sa langue se presse contre ma bouche et j'hésite seulement un instant avant de la laisser entrer, sa langue plus fine et plus longue caressant la mienne avec une force agile et surprenante."
"Je pensais que ce serait un peu difficile de comprendre la façon dont son museau est formé, mais Amicus y parvient, ses lèvres se serrant autour de ma bouche alors qu'il m'embrasse plus profondément."
"Je suis étonné de voir à quel point il est audacieux, et je me demande si c'est peut-être parce qu'il est encore assez ivre."
"Il berce doucement ma tête, me faisant reculer lentement, sa queue poussant contre mon aine et mes cuisses de temps en temps jusqu'à ce que je vienne contre le lit."
"Doucement, il m'abaisse pour me reposer sur mon dos, les deux pattes venant se presser de chaque côté de mes épaules alors qu'il se profile au-dessus de moi, souriant avant de faire une pause."
show ami n with dissolve
a "\" Est-ce que ça va? \""
"Je pense."
m "\" Je veux dire, ça va? On peut attendre demain quand tu seras moins ... ivre. \""
"Il sourit à nouveau."
a "\" Je voulais faire ça depuis si longtemps, pour te montrer à quel point je t'aime ... \""
"Amicus se penche, se blottissant contre mon cou."
show ami serious n with dis
a "\" Je pensais avoir raté cette chance. Je ne peux pas vous dire à quel point ces trois derniers jours ont été sombres pour moi. Je - j'ai manqué de larmes hier. \""
"Amicus détourne le regard pendant un moment."
a "\" ... Je ne vais pas rater cette chance maintenant. \""
hide ami with dissolve
play music "music/romance.ogg" fadein 10.0
"Je tends la main et maintiens sa tête ferme à nouveau avant de me pencher pour l'embrasser."
"Cela peut être alimenté par l'alcool, cela peut être soudain, mais après tout ce qui s'est passé, après ce qu'Amicus a vécu ... Je veux que nous puissions faire cela avant que quoi que ce soit {i} d'autre {/ i} n'arrive."
"Il souffle fort par le nez, l'éclat d'air chaud chatouillant mon visage alors qu'il tombe sur le lit, roulant sur le côté pour me tirer sur lui."
"Son corps massif et doux me protège comme il le fait toujours, montant et descendant avec ses respirations accélérées, ses baisers devenant de plus en plus agressifs alors qu'il laisse échapper de petits grognements et grognements."
"Toutes les réserves que j'avais à propos d'avoir des relations sexuelles avec un loup extraterrestre disparaissent à ce moment-là."
"Après tout ce qui s'est passé, et surtout après avoir failli mourir ... je m'en fiche."
"Nous nous frottons l'un contre l'autre, tous les deux dur maintenant alors que nous explorons simplement le corps de l'autre, ses pattes géantes glissant de haut en bas sur mes côtés pendant que je lui fais de même."
"Finalement, je m'assieds, chevauchant sa taille, le regardant, juste en quelque sorte de l'accueillir."
"Encore une fois, il a ce sourire idiot sur son visage, ses pattes sur mes cuisses, pétrissant la peau et les muscles."
a "\" Vous êtes belle. \""
"Ça me fait rire."
m "\" Beau? Eh bien, tu es adorable. \""
"Amicus lève un sourcil."
a "\" Je ne suis pas sûr que ce soit le descripteur correct pour le prochain empereur d'Adastr-aaahh! \""
"Je me penche en avant et je frotte agressivement son ventre, son point faible, neutralisant immédiatement son grognement alors que ses pattes retombent au-dessus de sa tête, les yeux roulant presque de plaisir avant qu'il ne les ferme."
"Il se tord et se cambre autour de mes mains, se penchant dans le frottement alors que je glisse mes mains sur sa poitrine, puis tout le long de son ventre."
"Quand cela arrive, je sens sa bite sauter contre mon derrière, me faisant réaliser à quel point je le prends."
"J'obtiens de la même manière que je fais onduler avec plaisir le corps fort et épais sous moi."
"Sa tête roule d'un côté à l'autre, la langue se balançant d'avant en arrière et quand je rigole après lui, cela semble finalement le sortir de sa transe."
"Il grogne et saisit mes bras."
a "\" qui triche. \""
"Sur ce, il me fait rouler, inversant facilement nos positions alors qu'il me monte, épinglant mes mains au-dessus de ma tête avec une patte."
"Avec son autre, il essaie de me frotter le ventre, ce qui me fait rire et me tortiller jusqu'à ce qu'il me lâche enfin."
m "\" Cela ... cela ne fonctionne pas ... sur les primates. \""
a "\" Semblait que cela fonctionnait bien pour moi! \""
"Il lâche mes mains et se penche pour se museler mon visage, son nez froid explorant mon menton, mes joues et mon front."
"Il commence alors à ajuster son positionnement avant de s'arrêter brusquement, en levant les yeux vers moi."
show ami embarrassed n with dissolve
a "\" Euh ... \""
"Ses oreilles plus basses, et je peux dire qu'il est gêné."
m "\" Quoi? \""
a "\" Est-ce que vous les humains ... pour les hommes, passez-vous par, euh ... l'arrière? \""
m "\" Oh. \""
"Je pense à ça."
"Ce serait l'itinéraire prévu, mais en regardant la longueur d'Amicus ..."
"Le loup suit mon regard et a l'air encore plus embarrassé."
show ami disappointed blush n with dis
a "\" Nous n'avons pas à le faire! Je ne veux pas te blesser, bien sûr. \""
"Je me tiens sur mes coudes, regardant entre nous deux."
m "\" Ouais ... peut-être une autre fois. Vous êtes un peu épais. \""
"Amicus sourit."
show ami n with dis
a "\"merci.\""
"Il recommence à s'ajuster, s'accroupissant alors qu'il se dandine pour que nos bites soient parallèles les unes aux autres."
a "\" Peut-être ... peut-être ceci? \""
"Il s'abaisse lentement jusqu'à ce que nous prenions contact."
scene amiscene1 with slow_dissolve
"La sensation et la vue sont électriques, la chair chaude de son sexe se pressant fermement contre la mienne."
"Hors de vue, je sens ses boules poilues venir se poser doucement sur les miennes, les formes douces se moulant facilement."
"Amicus s'arrête là, me souriant doucement alors qu'il pose ses deux pattes de chaque côté de ma tête."
a "\" Vous devrez excuser mon ignorance. Je ne sais pas comment les humains pourraient copuler. \""
"Il remue ses hanches, faisant glisser sa longueur d'un côté à l'autre sur les miennes, et je dois étouffer un halètement."
m "\" Je ... je pense que c'est à peu près la même chose ... d'après ce que j'ai vu. \""
"Amicus fronce les sourcils pendant un moment alors qu'il réalise à quoi je fais référence exactement, mais se rétablit rapidement alors qu'il se penche pour m'embrasser à nouveau."
"Une fois qu'il a fini, je lui souris."
m "\" Mais oui, ça va. \""
"Je pose mes mains sur ses genoux, remarquant comment il équilibre la plupart de son poids considérable dans un squat."
m "\" Etes-vous à l'aise? Cela ressemble à un entraînement. \""
a "\" Heh, Cato me travaille beaucoup plus dur que ça, [mc]. \""
"Amicus fronce les sourcils à nouveau en réalisant comment cela pourrait être interprété."
a "\" Je veux dire, il me fait faire beaucoup d'exercices accroupis. Je vais juste considérer cette pratique supplémentaire. \""
"Je tends la main et je sens la poitrine et le ventre du loup pendant qu'il parle, m'émerveillant à nouveau de la puissance de tout cela."
"Amicus rit et se cambre un peu pour me donner une meilleure sensation, prenant de grandes respirations et gonflant sa poitrine."
"Il frissonne alors que je frotte ses tétons, les boutons de chair se durcissant instantanément."
a "\" Mmmh ... alors, maintenant que vous êtes à l'aise— \""
"Provisoirement, Amicus se penche avec sa patte gauche et soulève soigneusement ma longueur de mon ventre pour se presser contre le sien."
scene amiscene2 with slow_dissolve
"Cette fois, j'ai laissé échapper un petit hoquet, étant serré ensemble comme ça, envoyant une secousse de plaisir de ma bite, à travers mon corps et dans mon cerveau."
"Immédiatement ma peau se transforme en chair de poule alors que je frissonne au toucher d'Amicus, sa patte douce mais enveloppante se sent si bien en ce moment."
"Il commence lentement au début, commençant à nous branler tous les deux en petits et rapides mouvements."
"Je peux dire qu'il est trop prudent avec moi, alors je remue mes hanches contre lui, encourageant davantage."
"Il semble comprendre l'allusion, et il prend de la vitesse, nous donnant des coups plus profonds et plus rapides qui me font agripper les draps de chaque côté de moi, fixant le plafond alors que je laisse échapper un pantalon mou et des gémissements."
"Amicus est de plus en plus dedans, fuyant déjà partout sur ma propre bite alors qu'il pompe sa patte, les biceps gonflés avec l'effort."
"J'ai déjà été branlé par d'autres, mais la patte d'Amicus est vraiment autre chose."
"Bien sûr, il est gros, mais les coussinets doux et visqueux sur sa paume et ses doigts ajoutent au plaisir, me donnant une texture que je n'ai jamais ressentie auparavant."
"Le loup commence à enfoncer ses puissantes hanches dans la caresse, faisant grincer et trembler le lit."
"Encore une fois, sa force est évidente dans la façon dont il bouge pratiquement tout mon corps à chaque poussée, l'idée qu'il se retient m'excite encore plus."
"Je sens son sac lourd rebondir sur le mien."
"Mes genoux se redressent à chaque poussée, et chaque fois qu'ils le font, je sens son grand arrière-train claquer contre eux, sa forme velue serrée et serrée."
a "\" Je ... me rapproche ... de ... \""
"Il halète au-dessus de ma tête, une goutte de bave coulant sur ma joue."
"Je commence à me battre contre lui sérieusement, voulant égaler son apogée."
"À ce stade, nous rebondissons presque sur le lit avec la force avec laquelle le loup se bosse contre moi, oubliant sa force sur le moment."
"Cela ne me dérange pas, je ne me soucie pas vraiment de la douleur que je vais avoir demain alors que le plaisir me rattrape."
"Cela me frappe tout d'un coup et je tends la main pour mettre une main contre son visage, lui faisant savoir, et il prend cela comme son signal de lâcher prise aussi."
"Je le sens dans tout son corps, le loup se crispe, ses muscles se resserrent, ressortent à travers la fourrure sur ses cuisses, son ventre et sa poitrine."
"Je vois alors son visage alors qu'il se balance sur le bord de l'apogée, les yeux écarquillés et regardant vers le plafond, la bouche ouverte, un regard de pure admiration."
"Je le sens aussi dans sa bite, et en même temps, nous sommes tous les deux poussés par-dessus bord."
scene amiscene3 with slow_dissolve
"Je gémis, quelque chose que je ne fais pas d'habitude, mais l'accumulation, la situation, le sentiment est trop grand."
"Il est cependant noyé par le son qu'émet Amicus."
"Il s'affaisse pratiquement sur moi, laissant échapper un gémissement d'extase grave et grondant."
"Entendre la voix masculine et profonde émettre un son d'un tel plaisir stimule un autre spasme de ma bite."
"Je pense que la même chose arrive à Amicus, parce qu'il se penche à nouveau en avant, le museau juste à côté de mon oreille alors qu'il gémit à nouveau, son souffle chaud sur le côté de mon visage me faisant frissonner."
"Le grand loup continue de se pousser contre moi, au rythme des giclées de sa queue, le regard sur son visage maintenant un de plaisir loufoque, sa longue langue tombante, dégoulinant sur ma poitrine."
stop music fadeout 10.0
"Son orgasme dure plusieurs secondes de plus que le mien et je le regarde gicler sur mon ventre encore et encore jusqu'à ce qu'il s'effondre enfin contre moi, sa fourrure humide de sueur."
"J'enroule mes bras autour de lui alors qu'il respire, sentant son corps se dilater et se contracter contre le mien."
"Il se blottit contre ma tête, son estomac s'aplatissant contre le mien, contre le désordre que nous avons fait."
"Nous allons devoir prendre une autre douche."
scene bg amicusroomdim with dissolve
"Même si je suis un peu essoufflé, je suis plutôt amusé de voir à quel point Amicus est haletant, comme s'il venait de courir un marathon."
"Il a vraiment tout mis là-dedans."
a "\" Huh ... huh ... vous ... \""
"Je tiens sa tête contre la mienne, me tournant pour l'embrasser sur la joue."
m "\" Moi? \""
a "\" Vous ... êtes ... incroyable ... \""
m "\" Merci ... vous êtes vraiment quelque chose aussi. \""
a "\" Un ... bon quelque chose? \""
m "\" Un très bon quelque chose. \""
"Nous sommes restés là tranquillement pendant un moment, Amicus se redressant un peu sur ses genoux et ses coudes pour que tout son poids ne repose pas sur moi."
m "\" Comment vont vos jambes? \""
a "\" Heh, brûlant. Probablement l'exercice le plus intense que mes cuisses aient jamais fait, mais cela en valait la peine. \""
"Encore une fois, nous nous sommes allongés là tranquillement alors qu'Amicus me caresse les cheveux."
a "\" Je suis toujours terrifié que ce soit un rêve. \""
"Je le serre plus étroitement contre mon corps, le forçant presque à tomber sur moi."
m "\" Je suis là, et je serai là le matin quand vous vous réveillerez. \""
a "\" Tu ferais mieux, sinon je ne te pardonnerai jamais. \""
"Son discours est un peu insultant alors qu'il chuchote dans mon oreille."
"Je le regarde."
m "\" Alors, à quel point êtes-vous ivre? \""
"Le loup hausse les épaules, roulant lentement hors de moi, l'air froid frappant les fluides sur mon estomac."
show ami happy eyes n with dissolve
a "\" Je suis assez sobre maintenant. Allons-nous nous laver? \""
"Il tend une patte et je la prends, légèrement surpris alors qu'il me tire pour être porté dans ses bras, comme si j'étais sa nouvelle épouse."
hide ami with dissolve
"Nous allons à la douche et nous nous lavons à nouveau, encore plus lentement que la première fois."
"Quand nous revenons au lit, Amicus continue de chérir sur moi, ne me laissant presque jamais partir à aucun moment."
"Je peux dire qu'il est légitimement inquiet que ce ne soit pas réel, et je ressens la même chose."
"Après tout ce qui s'est passé, cela ne semble pas possible."
"Finalement, je me suis allongé dans le lit à côté de lui, et il me cuillère contre son corps."
"Il est extrêmement chaud, mais sans couvertures et l'air froid dérivant sur nous, c'est parfait."
"Bientôt, je m'endors en écoutant les doux ronflements du loup dans mon oreille."
"Heureusement, je ne rêve pas ..."
scene bg black with slow_dissolve
"..."

scene bg amicusroom
"\"SE LEVER!\""
"Je sursaute en même temps que je sens Amicus se soulever contre moi."
"Nous avons tous les deux du mal à nous asseoir tout en tirant les couvertures autour de nous."
show cat angry with dissolve
ca "\" HORS DU LIT! \""
"L'apparence choquante de Cato me fait le regarder avec surprise, ne sachant pas quoi faire."
"Mais Amicus bouge immédiatement, me tirant du lit avec lui, se tenant légèrement devant moi alors qu'il me tend la couverture pour me couvrir."
"Nous regardons tous les deux Cato, le vieux loup tremblant de fureur."
ca "\" Soyez décent, Amicus. \""
"Amicus attrape à la hâte des sous-vêtements de la commode, me donnant aussi un des miens."
"Alors que je lutte pour attacher le mien, je remarque Cassius debout sur le pas de la porte, quelque chose de brillant et clignotant avec des lumières dans sa patte."
"Il n'a pas l'air aigre habituel sur son visage cependant."
"Au lieu de cela, il a presque l'air effrayé."
"Caton nous laisse rester en silence pendant un moment avant de tourner la tête vers la porte."
ca "\" Felix! Entrer!\""
"J'entends se balader dans le couloir et Cassius se déplace sur le côté pour permettre à un loup à la robe soignée d'entrer."
"Il a l'air aussi vieux que Cato, mais loin d'être aussi grand."
"Il bouge timidement, regardant autour de lui avec ses oreilles baissées."
"Félix" "\" Y-oui, Votre Majesté Impériale? \""
ca "\" Est-ce que c'est l'extraterrestre que vous avez traité pour la variole aviaire? \""
"Cato secoue la tête vers moi, gardant ses yeux sur Félix."
"Felix se retourne pour me regarder, et je peux dire qu'il essaie de penser à la bonne chose à dire."
"Finalement, il avale juste et hoche la tête."
"Felix" "\" Oui, je l'ai traité il y a trois nuits pour la variole aviaire. \""
ca "\" Et son espèce n'avait pas de profil? \""
"Felix" "\" N — non, je pourrais seulement dire qu'il était un primate ... comment ... comment est-il conscient— \""
ca "\" Com, escorte Félix aux donjons. \""
play music "music/tension.ogg" fadein 3.0
com "\" Oui, Cato \""
"Félix" "\" Quoi? Pourquoi!? Pourquoi les donjons ... Votre Majesté? \""
"Félix regarde Cato avec imploration avant que les sondes n'entrent."
com "\" Rendez-vous dans la salle ou risquez de vous faire tirer dessus, Félix. \""
"Felix" "\" S'il vous plaît, que se passe-t-il? \""
"Même pendant qu'il parle, Felix recule hors de la pièce, Cato l'ignorant complètement."
"Nous écoutons tous les pas trébuchants du médecin dans la salle en écho, le loup essayant de demander à Cassius ce qui se passe avant que les choses ne se taisent à nouveau."
ca "\" Cassius, entre et ferme la porte. \""
show cas scared at zero with dis
play sound "sfx/doorclose.ogg"
"Cassius, l'air encore plus effrayé maintenant, entre et laisse la porte se fermer."
"Cato nous regarde tous les deux."
"À ce stade, Amicus a une patte sur mon bras, me gardant fermement à mi-chemin derrière son dos."
"Je suis toujours capable de regarder autour de son épaule le furieux empereur par intérim."
"Lentement, je commence à réaliser ce qui pourrait se passer en ce moment, et les prochains mots de Cato le confirment."
show cat frown with dis
ca "\" Amicus ... avez-vous établi un premier contact? \""
"Amicus reste silencieux pendant un moment, mais répond d'une voix forte et confiante."
show ami serious u at twelve with dissolve
a "\" Non, bien sûr que non. De quoi diable parles-tu, Caton? \""
"Cato regarde fixement, la mâchoire serrée, puis nous crie dessus à un volume dont je ne pensais pas qu'il était capable."
show cat angry with dis
show ami surprised u at jumping with dis
with vpunch
ca "\" NE JOUEZ PAS AUX JEUX AVEC MOI AMICUS! \""
"A son crédit, Amicus ne fait qu'un petit saut, sa prise toujours fermement sur mon bras."
"Le silence qui suit résonne dans mes oreilles alors que Caton semble travailler pour se calmer."
"Quand il parle à nouveau, sa voix est à peine au-dessus d'un murmure."
show cat bow with dis
ca "\" Il n'est pas profilé. TOUS les enfants, abandonnés ou non, sont profilés. Ce n'est pas un Simien, alors qu'est-ce qu'il est? \""
"Amicus est gelé, et je sens mon estomac tomber, comme si j'allais me faire chier."
"Je vois Cato travailler sa mâchoire."
show cat angry with dis
ca "\" Et est-ce vrai que c'est votre amant? \""
"Amant?"
"Comment pourrait-il savoir quoi que ce soit à ce sujet?"
"Amicus ne répond pas cette fois, et cela semble être suffisant pour Cato."
ca "\" Très bien, ne réponds pas. Nous prendrons les bonnes précautions. COM! \""
com "\" Oui, Cato? \""
ca "\" Terminer [mc]. \""
show ami shocked u at jumping with dis
a "\" NON! \""
show ami angry u with dis
"Amicus se jette simultanément devant moi tout en tendant la main et en me serrant contre lui avec les deux pattes, me plaçant contre le mur."
"Les drones commencent à entrer dans la chambre, mais Cato aboie un autre ordre."
ca "\" Suspend la dernière directive! \""
com "\" Pause de la dernière directive. \""
"Ma vue est obscurcie maintenant, mais je peux entendre la respiration lourde d'Amicus, son cœur battant si fort que je peux le sentir dans son dos."
"Une fois de plus, Cato permet au silence de s'étirer avant de parler."
show cat forwn with dis
ca "\" Alors dis-nous la vérité, Amicus. \""
show ami angry teeth u with dis
a "\" Vous ne devez pas lui faire de mal! Sinon, je ne te donnerai rien et ... et je te ferai jeter dans le donjon quand je deviendrai empereur! \""
"Plus de silence."
"Je grimace, me demandant comment cela aurait pu être la bonne chose à dire."
"Ensuite, j'entends un faible grognement, celui dont je suis sûr qu'il vient de Cato."
show cat angry with dis
ca "\" Comment osez-vous. Tu penses que tu deviendras empereur après ça? En fait...\""
"J'entends un mouvement rapide et la prochaine chose que je sais, c'est qu'Amicus est arraché devant moi."
hide ami 
hide cat
with dissolve
play sound "sfx/thud.ogg"
with vpunch
"Je le regarde glisser sur le sol avant que Cato ne se jette sur lui, l'épinglant là."
ca "\" Cassius! Attrapez l'extraterrestre! Réglez le nervo sur mortel. \""
a "\" NON! S'IL TE PLAÎT!\""
"Je suis figé, mais j'arrive à regarder Cassius qui semble aussi figé que moi, tenant le nerf dans ses pattes tremblantes."
ca "\" DÉPLACEZ-VOUS IDIOT! \""
show cas scared at twelve with moveinright
"Cassius saute et se précipite vers moi."
"Je commence à m'éloigner, mais il m'attrape dans une prise maladroite, posant le nerf contre mon cou."
a "\" NOOO! \""
"Les luttes d'Amicus doublent et Cato est bouleversé comme s'il était sur un taureau mécanique."
ca "\" Cessez de vous battre, Amicus! Il ne sera pas blessé si vous faites ce que je dis! \""
"Amicus semble se calmer un peu à cela, haletant humide contre le sol alors qu'il me regarde droit, le visage plein de désespoir."
ca "\" Vous avez prouvé que vous étiez un imbécile incompétent, même plus que je ne le pensais au départ. Vous avez mis en danger tout notre empire. Pour cela, vous ne deviendrez pas empereur, les règles soient damnées. \""
ca "\" C'est une merveille de savoir comment vous pensiez vous en tirer. Ce ne peut être qu'un miracle que les moniteurs n'aient pas découvert, et ils le feraient sûrement si vous deveniez empereur avec cette ... chose. \""
"Cato se lève et remet Amicus sur ses pieds, tordant les pattes de l'autre loup derrière son dos assez fort pour qu'Amicus laisse échapper un aboiement de douleur."
show cat at four with dissolve
show ami cringe u at one with dissolve
ca "\" Le troisième essai commence aujourd'hui. Vous perdrez et Cassius deviendra empereur. \""
"Cato commence à pousser Amicus vers la porte."
ca "\" Faites ce que je dis, et je laisserai vivre l'extraterrestre, sinon nous pourrons faire tout cela de la manière la plus désagréable possible, compris? \""
"Amicus est silencieux jusqu'à ce que Cato le secoue par ses bras épinglés."
a "\" Agh! ... Oui. \""
ca "\" Bon, maintenant à l'amphithéâtre. Nous allons le faire rapidement. Ne faites pas de mouvements stupides sinon je laisserai les drones vous escorter à la place. \""
"Cato pousse Amicus vers la porte."
show ami embarrassed u with dis
"Je vois Amicus me jeter un coup d'œil, le regard sur son visage comme une impuissance totale."
hide cat
hide ami
with dissolve
stop music fadeout 10.0
"Ils sont sortis au moment où Cassius se rend compte qu'il est censé suivre."
"Il saute avant de me pousser maladroitement après eux."

scene bg amphitheaterevening with transition_fade
play music "sfx/forest.ogg" fadein 5.0
"C'est déjà le coucher du soleil quand nous arrivons à l'amphithéâtre."
"Nous avons dû dormir presque toute la journée."
"Amicus et Cato se tiennent déjà au centre de l'amphithéâtre alors que Cassius a du mal à me faire descendre les marches."
show cat angry at center with dissolve
ca "\" Asseyez-le, Cassius, et descendez ici! \""
"Shakily, Cassius me plante sur l'une des marches de pierre avant de se déshabiller soudainement."
"C'est à ce moment-là que j'ai remarqué qu'il a ramené le nerf dans sa ceinture."
"Peut-être à cause de la nature frénétique de toute la situation, Cassius semble l'avoir oublié, et je le regarde tomber dans ses vêtements alors qu'il le laisse tomber de sa taille."
"Il trébuche ensuite vers le centre."
"Amicus, quant à lui, se tient raide à côté de Cato, les pattes serrées, et je sens mon cœur se serrer en voyant l'expression sur son visage."
"Il ne sait pas quoi faire."
"Plusieurs drones de caméra nous avaient suivis jusqu'à l'amphithéâtre, leurs lumières brillaient d'un rouge inquiétant."
"Pendant quelques instants, Caton les regarde s'organiser autour du petit théâtre, leurs lentilles clignotant dans la lumière qui s'estompe."
show cas scared u at one with dissolve
c "\" Caton? \""
ca "\" Quoi, Cassius? \""
c "\" Aucun essai n'est prévu pour aujourd'hui ... comment cela sera-t-il diffusé n'importe où? \""
ca "\" Ce ne sera pas en direct. Je penserai à une raison de le dire aux gens plus tard. Nous n'avons besoin que d'un seul extrait de votre victoire. \""
show ami crossed serious u at twelve with dissolve
a "\" Ils ne le croiront jamais. \""
"Bien qu'Amicus ait un visage courageux, je peux entendre sa voix trembler."
ca "\" {i} Pugnu {/ i} est une combinaison d'habileté et de chance, et ce n'est pas toujours le plus fort qui gagne. Nous allons gérer. \""
a "\" Et comment - \""
play sound "sfx/thud2.ogg"
hide ami with dis
show cas scared u at jumping
"Cato se retourne soudainement sur Amicus, lui lançant un coup de poing si fort dans sa mâchoire que l'autre loup tourne à presque 360 ​​degrés avant de s'effondrer sur le sol dur de l'amphithéâtre."
"Je me lève sans même m'en souvenir, le cœur martelant ma gorge alors que je regarde Amicus."
"Il ne bouge pas."
"Pendant ce temps, Cato secoue légèrement sa patte, comme si elle ne piquait qu'un peu."
"Cassius, d'un autre côté, serre ses deux oreilles dans ses pattes, regardant son frère dans un mélange de choc et d'horreur."
show cas furious u with dis
c "\" C - Caton! Que faites-vous!?\""
show cat talking with dis
ca "\" Le rendre plus authentique, c'est tout. \""
"Amicus remue sur le sol alors, gémissant et se poussant vers le haut."
"Je vois des taches sombres se former sous son visage, du sang coulant de son nez."
"Un drone caméra dérive lentement, filmant Amicus alors qu'il crache du sang."
"Je réalise alors que je dois faire quelque chose."
"On m'a dit de rester à l'écart pendant bien trop longtemps."
"Et je ne suis pas entièrement convaincu que je vais bien après ça."
"Je suis un risque pour tout l'empire."
"Pourquoi Cato me laisserait-il vivre après que j'aie fini d'être utile?"
"Je {i} dois {/ i} faire quelque chose."
"Alors je m'assois tranquillement et je me penche pour atteindre la pile de vêtements de Cassius, trouvant rapidement le nerf et le tirant."
"Ensuite, je me relève pour faire un pas vers le bas, et personne ne semble le remarquer."
ca "\" Allez Amicus, levez-vous. Vous devez vous débattre avec Cass. \""
show cas disappointed u with dis
c "\" Pourquoi n'avons-nous pas simplement utilisé du maquillage à la place? \""
ca "\" Il n'y a pas de temps. \""
"Cato se penche enfin pour attraper Amicus sous les bras et le mettre debout, le gros loup trébuchant de façon instable, le sang coulant sur son menton."
ca "\" Cassius, attrape Amicus dans une cheville et laisse-le tomber. Cela devrait suffire. \""
hide cat
hide ami
hide cas
with dissolve
"Ils ont mis en place leur scène, même si Amicus semble presque complètement en dehors."
"Tous sont distraits et je me rends compte que c'est peut-être ma seule chance."
"Lentement, je fais un pas à la fois, vers le centre de l'amphithéâtre."
"Pendant ce temps, Cassius a du mal à prendre la jambe d'Amicus, perdant presque son équilibre comme il le fait."
"Après cela, Cato dit à Amicus de se replier, ce que fait le loup, lentement."
"Cassius le cloue au sol après ça, et je ne pense pas que ça ait l'air convaincant du tout."
"Mais cela n'a plus vraiment d'importance maintenant car je ne suis qu'à quelques pas du rez-de-chaussée."
ca "\" Maintenant, levez-vous et levez les pattes en signe de victoire, Cass. Ayez l'air fier. \""
"En ce moment, les choses commencent à bouger au ralenti."
"Amicus est à plat sur le dos, mais il me regarde droit."
"Il y a un regard interrogateur dans ses yeux, puis un regard suppliant, comme pour me pousser à prendre du recul."
"Je ne."
"Au lieu de cela, je fais le dernier pas sur le sol de l'amphithéâtre, juste derrière Cassius, en direction de Caton."
"Mais le loup blanc continue de célébrer sa prétendue victoire, et il se retourne les pattes levées pour me faire face."
"Je vois la reconnaissance soudaine sur son visage."
"Je suis à court d'options et je lui enfonce le nerf dans la poitrine."
stop music fadeout 5.0
play loop "music/tensebackground.ogg" fadein 3.0
"Instantanément, Cass est abattu de plusieurs pieds en arrière pour se froisser à côté d'Amicus, frissonnant et convulsant."
"Avant que je puisse même me tourner vers Cato, le vieux loup est sur moi, attrapant le nerf de mes mains et me tirant plus près par le devant de ma robe, mes dents claquant avec la vitesse à laquelle il le fait."
"Il regarde le nervo plutôt que moi, cependant."
show cat angry with dissolve
ca "\" Bon sang! Remerciez les dieux que l'idiot ne l'avait pas mis sur la mort. \""
"Cato tripote l'appareil et je réalise qu'il est sur le point de l'utiliser sur moi."
"Je me bats, donnant des coups de pied au loup massif, mais il est fort, plus fort que même Amicus."
"Mais juste au moment où il retourne l'appareil, les deux broches métalliques pointées vers mon visage, je vois une patte passer au-dessus de la tête de Cato."
"Amicus s'accroche à la grille métallique du masque facial de Cato, les doigts se verrouillant dans les espaces avant de tirer."
hide cat with dissolve
"Cato hurle, et j'entends un horrible mélange de craquements, de déchirures et de sifflement électronique alors que je vois une giclée rouge du visage du vieux loup pendant juste un moment avant qu'il ne s'effondre."
"Amicus me regarde avec des yeux fous alors qu'il essaie de garder Cato coincé."
a "\" [mc], courez ... courez vers Neferu! COURS!\""
"Je regarde Amicus d'un air engourdi pendant un moment, un moment où je veux faire tellement ... mais je ne peux pas, puis me retourne et commence à courir."
"Je cours aussi vite que je peux, disparaissant derrière les arbres et les buissons, tout comme j'entends Cato crier à Com de m'exécuter."
jump a2s2

stop loop fadeout 5.0
scene bg black with transition_fade
"À suivre..."
window hide
scene bg credits with dissolve
pause
stop sound fadeout 3.0
return


