label a2s3:
"Derrière moi..."
"Il n'y a pas de \"derrière moi\" parce que je n'ai plus de corps."
"Au lieu de cela, le sentiment rampe juste en dehors de ma conscience."
"Chaque fois que j'essaye de me concentrer dessus, ça s'échappe."
"Alors à la place, je l'ai simplement laissé aller, flottant dans l'espace, ne ressentant presque rien."
"Et ne rien ressentir maintenant, après tout, ça fait du bien."
"Mais après un moment, je commence à avoir des sentiments vagues et lointains."
"Pas mes propres sentiments, mais les sentiments des autres, et je les capte comme des chuchotements lointains."
"\"Nous avons déjà trop interféré.\""
"\" Rien ne se passe comme prévu avec les loups. Il faut le faire...\""
"Je n'écoute qu'à moitié, je roule sur les vagues d'un espace vide et apaisant."
"Si c'est comme ça que la drogue vous fait ressentir, je suis plutôt dedans."
"\"Plus nous interférons, plus il sera difficile de prédire quoi que ce soit.\""
"\"Il n'y a pas d'autre choix.\""
"Les sentiments de voix cessent à ce moment-là, et je continue à onduler sur les vagues de l'univers."
"C'est alors que je remarque quelque chose qui apparaît au centre de mon espace infini."
scene watching with slow_dissolve
"J'ai… déjà vu cette chose… je pense."
"Les rêves qui avaient fui mon esprit au moment où je m'étais réveillé sont soudainement revenus."
"Je me concentre sur cet être, cette créature qui me suit depuis que j'ai été enlevée."
"Il se profile là-bas, me regardant, même si je suis partout à la fois."
"Le silence dure un moment ... ou peut-être pas."
"Je n'ai toujours pas le sens du temps."
"C'est jusqu'à ce que la créature parle."
play music "music/memories.ogg" fadein 10.0
unk "\"[mc].\""
"La voix est profonde et masculine, grondant à travers mon être."
"J'attends un moment, puis j'essaye de le saluer, rendu difficile par le fait que je n'ai pas de bouche à qui parler."
unk "\" Si vous souhaitez communiquer, faites-le. Je peux t'entendre.\""
"\"Quoi?\""
"J'essaye de penser le mot à lui, mais c'est lent et maladroit dans mon esprit, et j'aimerais juste pouvoir parler."
"Il y a un grondement d'amusement dans l'air."
unk "\"Si vous désirez un corps, le voudra-t-il simplement. La perte de soi est un sentiment dérangeant pour vous créatures, je sais.\""
"Ce qu'il dit n'a pas beaucoup de sens, mais j'essaye quand même, et juste comme ça, je sens que mon être commence à se ressaisir."
"Je commence à me matérialiser juste devant la créature, et je vois à nouveau mes mains devant moi."
"Quand je regarde en bas, je vois mon corps, nu."
"Dès que je vois ça, je ressens un choc d'embarras, et ma robe apparaît soudain sur mon corps."
"Je ne me sens toujours pas bien, comme si je ne suis toujours pas dans ce corps que je vois."
"Pourtant, je me sens mieux et je suis capable d'ouvrir la bouche."
m "\"Qu'est-ce que c'est?\""
"Ma bouche est étrange et caoutchouteuse, et en même temps, j'ai l'impression que du coton recouvre l'intérieur."
unk "\"Ceci est ...\""
"Pour la première fois, la créature semble incertaine de ce qu'il devrait dire."
unk "\" Eh bien, c'est un peu compliqué à expliquer, mais c'est simplement un espace où vous et moi pourrions être en mesure de communiquer paisiblement. "
"Ce n'est pas vraiment une réponse."
unk "\"Non, mais si je devais l'expliquer en profondeur, cela perdrait le peu de temps que nous avons ensemble et vous confondrait encore plus.\""
"J'essaie de rester concentré, voulant en savoir le plus possible sur ce type avant que la drogue ne disparaisse."
m "\"Vous êtes un parent?\""
"Ce rire grondant me chatouille à nouveau au bord de mon existence."
unk "\"Non, certainement pas. Je suis un moniteur.\""
"Surveiller."
"La peur glaciale coule le long de ma colonne vertébrale imaginée alors que je réalise ce que tout cela pourrait signifier."
"Le moniteur tient rapidement une patte."
mon "\"Non, non, ne vous inquiétez pas. Vous n'êtes pas en difficulté.\""
"Je le regarde prudemment, comme s'il ne faisait que me bercer dans un faux sentiment de sécurité avant de m'anéantir sur place."
"Encore une fois, ce sentiment d'amusement."
mon "\"Maintenant, ce serait impossible à faire ici.\""
"J'essaye de garder mes pensées concentrées."
m "\"Et Amicus? A-t-il des ennuis?\""
mon "\"Non. Il n'a fait que ce que nous avions prévu pour lui de faire.\""
m "\"Planifié?\""
"Il y a une pause, comme si le moniteur rassemblait ses pensées."
mon "\"Non, je reçois simplement des instructions.\""
"\"je viens de?\""
mon "\"Les parents.\""
"Je le regarde."
m "\"Ils vous parlent?\""
mon "\"Oui, à propos de vous et de ce que je peux et ne peux pas vous dire.\""
m "\"Pourquoi {i} ils {/ i} ne me parlent-ils pas alors?\""
mon "\"Parce qu'ils ne peuvent pas. La communication directe est impossible.\""
m "\"Alors comment—\""
mon "\"J'ai été spécialement conçu pour être un pont entre votre ... disons dimension, et la leur.\""
"Je ne sais pas vraiment quoi penser de ça, mais j'ai le sentiment que je ne devrais pas être distrait par ces choses pour le moment."
mon "\"Ce serait sage.\""
m "\"Alors, que voulez-vous dire par «planifié»? Les parents ont mis Amicus en place d'une manière ou d'une autre?\""
mon "\"Votre enlèvement et votre introduction à l'empire des loups étaient censés se produire.\""
m "\"Pourquoi?\""
"Encore une petite pause."
mon "\"Les loups pourraient à eux seuls défaire les {i} Galaxias {/ i}, mais vous pouvez changer cela.\""
"Je fronce les sourcils, sentant une certaine anxiété glisser à travers le calme induit par la drogue."
m "\" Quoi? Comment?\""
mon "\"Les loups sont ... un frère têtu, peut-être une erreur commise au tout début, mais les parents peuvent toujours voir le chemin et la destination corrects.\""
m "\"Voyez? Peuvent-ils voir le futur, ou quelque chose?\""
mon "\"D'une certaine manière, oui. Leur esprit existe plusieurs fois à la fois.\""
"Je commence à me perdre et soudain, je commence à me sentir comme une forme de vie primitive, incapable de comprendre cet ancien monolithe extraterrestre avant moi."
mon "\"Ne vous sentez pas de cette façon. Vous ne comprenez peut-être pas vous-même, mais votre espèce dans son ensemble est plus que capable.\""
"Mon esprit repense automatiquement à la façon dont nous avons été abandonnés par les loups, peut-être même par les chacals aussi."
mon "\"Vous avez été abandonné par tous les frères et sœurs.\""
"Pendant un seul instant, de multiples images de plusieurs créatures différentes me traversent l'esprit; un ours, un loup, un chacal, un lion, un bélier ..."
"Ils sont tous reconnaissables, et ce qu'ils portent est également reconnaissable, ce qui me rappelle plusieurs cultures différentes sur Terre."
"Les images s'arrêtent enfin sur un tigre dans une robe fluide avec des dessins et des motifs complexes, et ce qui ressemble à un sari drapé sur son épaule."
"Alors que l'image disparaît de mon esprit, je sais immédiatement que c'est Meera."
mon "\"Oui, nous avons régné chez les loups une fois auparavant avec l'aide des hindous, mais cela a duré beaucoup plus court que ce que nous avions prévu. C'est pourquoi nous nous sommes tournés vers vous, pour jouer son ancien rôle.\""
m "\" Mais ... nous ne faisons pas partie des {i} Galaxias {/ i}. Tout le monde n'a pas réussi à nous élever, alors n'est-ce pas quelque chose qui ne va pas avec nous?"
"Une autre pause."
mon "\"D'une certaine manière, oui, mais après les tentatives, tous les parents ont réalisé que les humains prendraient en compte les {i} Galaxias {/ i} plus tard ... maintenant.\""
"\"centre commercial? Les parents ne sont-ils pas en concurrence les uns avec les autres? \""
"Cette fois, je n'obtiens le silence qu'en réponse."
"Je me demande si on lui a juste dit qu'il ne pouvait pas me dire ça."
m "\" Alors ... qu'est-ce que je suis censé faire? Qu'est-ce que tu veux avec moi?\""
"La réponse cette fois est immédiate."
mon "\"Restaurez Amicus à sa place légitime sur le trône.\""
"J'attends, mais il n'y a pas d'autre explication."
#
m "\"Et ... comment faire ça?\""
"Silence."
m "\"Pourquoi moi?\""
"Plus de silence."
"Je souffle de l'air de frustration, ou j'essaie de le faire puisque rien ne sort."
m "\" Pourquoi ne pouvez-vous pas tous simplement {i} me dire {/ i} quoi faire? Vous m'avez amené ici, n'est-ce pas? Dis-moi.\""
"Rien."
"Je suis sur le point d'abandonner, d'attendre la fin du voyage quand le moniteur recommence à parler."
mon "\"Les interférences conduisent souvent à la déstabilisation des événements qui devraient suivre. Les {i} Galaxias {/ i} doivent se développer et apprendre à leur manière.\""
m "\"Sauf pour le moment, non? Cela interfère, n'est-ce pas?\""
mon "\"Sauf dans divers cas où les enfants et les frères et sœurs s'éloignent trop de leur route.\""
"Cette fois, je ne sais pas trop quoi dire."
"J'avais toujours vu les parents comme des êtres omniscients avec seulement de bonnes intentions pour leurs enfants, mais maintenant ..."
"Comment puis-je savoir qu'on peut même leur faire confiance?"
"Ce que je sais, c'est que le moniteur est apparemment capable d'entendre toutes mes pensées, donc il a certainement entendu cela."
"Pourtant, il ne dit rien, juste en me regardant silencieusement."
m "\"Alors ... je suppose que vous ne pouvez pas me dire quel est le but de tout cela, alors? Les {i} Galaxias {/ i} dans leur ensemble?\""
mon "\"Cette connaissance n'a pas encore été acquise par les sapients.\""
"Ma méfiance grandit."
m "\"Eh bien ... pouvez-vous me donner quelque chose, {i} quelque chose {/ i} qui pourrait m'aider à faire sortir Amicus du donjon? Si je m'éloigne du parcours, dites-moi comment y revenir.\""
"Le moniteur fait une pause pendant un moment, comme s'il obtenait plus d'informations de la part des parents."
mon "\"Surveille le chat.\""
"Le chat."
m "\"Alexios?\""
"J'attends, mais encore une fois, j'obtiens le silence."
"Je secoue la tête."
"Si les parents sont vraiment omniscients et tout-puissants, alors pourquoi ne peuvent-ils pas simplement me dire…»"
mon "\"Nous ne sommes ni l'une ni l'autre de ces choses, c'est pourquoi nous devons être si prudents.\""
"Je reste juste là, ne sachant pas quoi faire d'autre."
"Je regarde autour."
m "\"Est-ce que euh, est-ce que Cassius va bien?\""
mon "\"Le faux empereur? Oui, il est quelque part par ici.\""
"Le moniteur regarde d'un air dédaigneux."
m "\"Nous a-t-il entendus?\""
mon "\"Non, il est trop occupé à paniquer. Un effet secondaire d'être un imposteur lâche.\""
"Je fronce les sourcils, sentant que c'est un peu dur, même pour quelqu'un comme Cassius."
m "\"Pouvez-vous ... pouvez-vous l'aider, peut-être l'amener ici?\""
"J'ai une impression du moniteur que je ne peux décrire que comme un soupir agacé."
mon "\"je suppose.\""
"Quelques instants passent avant que je commence à voir quelque chose apparaître à côté de moi."
show cas scared at fourteen with dissolve
"La forme incomparable de Cassius se matérialise, effrayée et tremblante."
"Il me voit immédiatement."
show cas scared at my_shake
c "\" [mc] !? Où sommes-nous? Ce qui s'est passé? Es-tu-\""
"Puis il voit le moniteur."
show cas scared at jumping
c "\"Agh!\""
"Il saute derrière moi, se protégeant de la créature."
c "\" Le démon! Aide-moi!\""
"Je ressens ce sentiment d'amusement de la part de la créature dragon, et je fronce les sourcils."
m "\"Lui avez-vous fait peur?\""
"J'ai la sensation d'un haussement d'épaules de la part de la créature."
mon "\"S'il a peur, c'est son choix.\""
m "\"Et les parents sont d'accord pour que tu fasses ça?\""
mon "\"Peut-être pas, mais le loup blanc signifie peu pour eux.\""
show cas angry with dis
c "\"Quoi?\""
"Cela semble attirer l'attention de Cassius, et il passe sa tête autour de moi pour me regarder fixement."
ca "\"E-excusez-moi, mais je suis l'empereur—\""
mon "\"Non, vous ne l'êtes pas.\""
"Je fronce les sourcils, la scène devenant de plus en plus surréaliste devant moi."
show cas surprised with dis
c "\"Excusez-moi!?\""
stop music fadeout 10.0
"Cassius semble incapable de penser à autre chose à dire."
"Juste au moment où je suis sur le point de passer entre eux deux, je me trouve incapable de garder ma conscience plus longtemps et je commence à dériver ..."

scene bg amicusroom with transition_fade
"Lentement, je viens vers le canapé, mes yeux s'ouvrant alors que je grimace sous le mal de tête palpitant que j'ai."
"Il y a une sensation de froid autour de ma bouche et je tends la main pour sentir que je baigne partout sur moi-même."
"Je me retourne, ressentant une vague de vertige comme je le fais."
"Je m'arrête là, attendant que la somnolence passe."
"Quand c'est finalement le cas, je peux mieux me concentrer sur mon environnement."
"Je regarde pendant dix secondes avant de me souvenir où je suis et ce que je fais là-bas."
"Je regarde le lit et vois Cassius allongé sur les couvertures, ses yeux flottant."
"Je le regarde pendant un moment, réalisant qu'il est toujours inconscient."
"Il a pris beaucoup plus de drogue que moi, donc je suppose que c'est logique."
"Très lentement, je glisse mes jambes hors du canapé et je m'assois là alors qu'un deuxième sort de vertige m'envahit."
"J'attends une bonne minute pour que celui-ci passe pour que lorsque je me lève, je ne finisse pas par tomber."
"Quand je suis capable de faire ça, je trébuche dans la salle de bain, me sentant de plus en plus lucide à la seconde."
scene bg bathroom with dissolve
play sound "sfx/dooropen.ogg"
"Quand j'arrive au lavabo, je me repose là, me regardant dans le miroir."
"Mes yeux sont rouges et mes cheveux sont foirés dans tous les sens."
"J'ai mouillé l'une des serviettes et me suis lavé le visage et au moment où j'ai fini, je me sens mieux."
"Alors que je me repose là contre l'évier, je repense à ce qui vient de se passer."
"Pas seulement le voyage de drogue que j'ai été envoyé, mais ce qu'on m'a dit."
"Tous les rêves que j'avais faits depuis que j'étais sur cette lune; je me souviens de tout."
"Je ne sais pas si c'est réel ou pas, si je viens vraiment de parler aux parents."
"Cela avait semblé trop complexe pour ne pas être réel."
"My mind wouldn't be able to make up something like that, would it?" 
"Mon esprit ne pourrait pas inventer quelque chose comme ça, n'est-ce pas?"
"Encore une fois, je ne sais pas ce que Cassius fumait."
scene bg amicusroom with dissolve
"Comme au bon moment, j'entends le loup renifler dans la chambre et je sort de la salle de bain, trouvant Cassius à ses côtés maintenant, se détournant de moi."
m "\"Cassius?\""
"Lentement, je fais le tour du lit et je vois que les yeux du loup, tout aussi rouges que les miens, sont ouverts, regardant dans le vide."
"J'essaie encore."
m "\"Cassius? Ça va?\""
"Le loup marmonne quelque chose, sans même me regarder."
"Je marche vers le côté du lit, tendant la main avec hésitation avant de le toucher doucement sur le bras."
"Cela semble le sortir de sa stupéfaction et il se recule, haletant de surprise et de peur alors qu'il se recule et me regarde."
"Je lève mes mains pour lui montrer que je ne veux pas de mal, et il me regarde pendant ce qui me semble plus d'une minute."
show cas annoyed with dissolve
play music "music/dawn.ogg" fadein 3.0
"Enfin, il marmonne mon nom."
c "\"[mc] ...\""
"J'acquiesce lentement, ne voulant pas faire de mouvements brusques."
show cas angry with dis
m "\"Oui, je suis [mc]. Vous êtes dans le palais, dans le vieux ro d'Amicus -\""
c "\"Je sais où je suis, idiot.\""
"On dirait qu'il revient à son ancien moi."
m "\"Eh bien, c'est bien. Tu as eu une très mauvaise réaction à ... quoi que ce soit.\""
show cas dissapointed with dis
"Cassius se met en position assise, le faisant lentement comme je l'avais fait."
"Il laisse sa tête pendre pendant un moment, traversant probablement les mêmes vertiges que je viens de vivre."
"J'attends patiemment, décidant de retourner sur le canapé pendant que je le fais."
show cas annoyed with dis
"Ses oreilles se redressent lorsque je m'assois, et il me regarde."
c "\"Que faites-vous?\""
"Je fronce les sourcils."
show cas with dis
m "\"Que voulez-vous dire?\""
c "\"Je veux dire pourquoi es-tu toujours là? Vous pouvez partir.\""
m "\"Euh, je suppose que je pourrais. Je veux juste m'assurer que tout va bien d'abord.\""
show cas paw with dis
"Cassius laisse échapper un léger grognement indigné."
c "\"Vous pensez que je crois cela? Vous êtes renvoyé.\""
"Je lui lance un regard incrédule."
m "\"Sérieusement? Tout d'abord, c'est la chambre d'Amicus, deuxièmement, je suis un Khémien. Je ne vous vois pas commander Neferu comme ça.\""
show cas paw annoyed with dis
"Cette fois, Cassius laisse échapper un grognement plus fort."
c "\"Ha! Il est de la royauté, et un vrai Khemian, tu penses que je te paierais la même chose…\""
"\"Les khémiens voient tous leurs citoyens comme des égaux. Je vaux autant qu'il l'est à leurs yeux.\""
show cas disappointed with dis
"Au lieu de reculer, Cassius baisse simplement la tête, les yeux fermés avant de laisser échapper un profond soupir désespéré."
c "\"Je suis fatigué, si vous souhaitez me contrarier, veuillez le laisser une autre fois.\""
"J'ai repoussé les limites avec Cassius exprès pour voir quelles sont les limites, et je deviens plus à l'aise pour converser avec lui sans crainte."
"Pourtant, je suis un peu décontenancé par le ton soudain de défaite de Cassius."
"C'est une chose que je n'ai pas souvent entendue."
"Nous sommes tous les deux silencieux pendant environ une minute, puis je prends enfin la parole."
m "\"Euh ... alors qu'est-ce que c'était? Ce truc de fumée? C'était une drogue, non?\""
show cas with dis
"Cassius est silencieux un peu plus longtemps, et je me demande s'il va me demander de repartir, mais à la place, il soupire juste et finalement lève les yeux, ses yeux paraissant un peu plus clairs maintenant."
c "\"Elle s'appelle {i} somni {/ i}, une plante de la région sud de ce continent. Cela nous aide à nous connecter avec les parents.\""
m "\"Ouais ... tu as dit que c'était la méthode traditionnelle?\""
c "\"L'ancienne méthode, oui. Habituellement, nous communiquons via la technologie parentale, mais comme vous le savez, ils ne nous parlent pas actuellement avec cette méthode.\""
m "\"Sooo ... cela le force à arriver?\""
c "\"D'une certaine manière.\""
show cas annoyed with dis
m "\"Est-ce que ça marche?\""
"Cassius me regarde."
c "\" Vous le sauriez. Tu étais là.\""
"Je me tais, cette déclaration me surprenant."
"J'avais vu Cassius, bien sûr, mais je pensais que cela ne faisait que partie de l'hallucination."
m "\"Vous ... m'avez vu?\""
c "\"Oh s'il te plait, simian ... ou peu importe ce que tu es. Vous essayez seulement de m'humilier davantage. J'étais juste à côté de toi.\""
"Alors ça avait été réel?"
"Je m'assois sur mes mains, contemplant tout cela."
"J'ai lu des expériences de DMT sur Terre, comment si vous percez, vous pouvez rencontrer des êtres extra-dimensionnels qui vous révèlent les secrets de l'univers."
show cas righteyes with dis
"J'aurais considéré mon expérience comme étant entièrement dans ma tête, mais si Cassius était réellement là ..."
"Je remarque alors que Cassius me regarde de très près, jaugeant mon expression."
m "\"Quoi?\""
c "\" Il vous a parlé, n'est-ce pas? Qu'a t'il dit?\""
m "\"Euh ...\""
"J'essaye de penser à quoi dire."
"Si c'est réel, alors je doute que dire à Cassius que tout m'aide de quelque façon que ce soit."
show cas furious with dis
"Il doit voir l'hésitation sur mon visage, parce que sa fourrure est hérissée."
c "\"L'empereur vous demande de lui dire ce qu'ils vous ont dit!\""
"Je lève les yeux sur Cassius, ayant de moins en moins peur de lui à chaque menace qu'il m'envoie."
"Il est vraiment tout aboiement et pas de morsure."
m "\" Il m'a simplement demandé ce que je faisais là-bas. C'est ça.\""
show cas disappointed with dis
"Cassius me regarde avant de finalement paraître vaincu une fois de plus, baissant les yeux."
m "\"Mais il semblait d'accord avec moi. C'était aussi un moniteur. Je ne pense pas qu'Amicus ait des ennuis.\""
"Cassius secoue la tête."
c "\"Je n'ai confiance en rien de ce qu'il a dit. C'était un démon.\""
"Je soupire."
show cas annoyed with dis
m "\"Qu'est-ce qu'ils vous ont dit {i} vous {/ i}? Vous aviez l'air assez effrayé.\""
c "\"Je n'avais pas peur!\""
show cas angry with dis
"J'ai laissé échapper un rire involontaire avant de pouvoir l'arrêter."
show cas disappointed with dis
c "\" Damn you! Je n'étais tout simplement pas préparé pour l'expérience; c'était beaucoup plus intense que le précédent que j'avais. C'est tout.\""
"Cassius regarde à nouveau le sol, et je peux voir que l'intérieur de ses oreilles est d'un rouge brûlant."
"Je sais que rire de lui était un geste de merde de ma part."
"Je devrais travailler pour le mettre de mon côté, pour aider Amicus."
"Je fais un effort pour maîtriser mon expression."
m "\"Ecoute, je ne suis pas contre toi Cassius. En fait, je pense que nous travaillons ensemble ici. J'essaye juste ... de trouver la meilleure façon d'aider ton frère.\""
"Cassius continue de fixer le sol en silence, même si je vois une oreille se tordre comme si je reconnaissais ce que je venais de dire."
m "\"Si nous voulons travailler ensemble, nous devons être au moins un peu honnêtes les uns envers les autres. Peut-être que je pourrais vous aider à comprendre certaines choses.\""
"Je me rends compte à quel point c'est hypocrite, d'autant plus que je cache ce que les parents venaient de me dire."
show cas annoyed with dis
"Cassius laisse échapper un souffle sceptique."
c "\"Vous, aidez-moi?\""
show cas right with dis
m "\"Oui.\""
"Cassius semble contempler, puis secoue la tête."
c "\"Eh bien, rien là-bas ne pourrait nous aider. Ils me tourmentent simplement quand j'essaye de communiquer avec eux.\""
show cas righteyes with dis
m "\"Tourment?\""
c "\"Ils apparaissent comme des démons et me narguent. Il semble que les parents veulent vraiment couper le contact avec nous ... ce qui me convient.\""
"Cassius dit ce dernier morceau avec un tel défi que je suis presque désolé pour lui."
show cas annoyed with dis
m "\"C'était peut-être juste la drogue? J'ai entendu beaucoup d'histoires de personnes paniquées par des trucs qui altèrent l'esprit, surtout si elles ont des problèmes d'anxiété—\""
c "\"Je n'ai pas l'esprit faible, [mc].\""
show cas with dis
m "\"Th - cela ne veut pas dire que vous avez un esprit faible, parfois vous juste -\""
c "\"Assez. Je ne vous ferai pas spéculer sur mes capacités mentales.\""
"Cette fois, c'est moi qui soupire, me demandant pour la centième fois comment diable ce loup est le frère d'Amicus."
m "\"Alors ils ne vous ont rien dit?\""
show cas sad with dis
"Cassius fait une pause, un froncement de sourcils tirant au coin de sa bouche."
c "\"Non\""
show cas annoyed with dis
"Je lève un sourcil vers lui."
c "\"Quoi? Bien sûr, ils m'ont dit des choses, mais rien d'utile.\""
show cas angry with dis
m "\"Vous êtes sûr?\""
show cas disappointed with dis
c "\"Bien sûr, je suis sûr! Les parents se sont retournés contre nous. C'est tout ce que j'ai besoin de savoir.\""
"Je repense à la conversation que nous avons eue dans l'hallucination."
"Le moniteur nous avait dit à tous les deux que Cassius n'était pas l'empereur, et si Cassius avait entendu ce que j'avais entendu, alors c'est probablement ce à quoi il pense en ce moment."
"Mais je sais que ce n'est pas le moment de le défier, et je peux dire qu'il essaie toujours de se remettre du voyage."
"Pourtant, le regardant en ce moment, fixant le sol, l'air échevelé et vaincu… Je sens que je veux l'aider."
stop music fadeout 5.0
"De tout le monde sur cette lune, il semble être le plus stressé, et je me sens mal pour lui malgré tout ce qui s'est passé."
"Mais je sais qu'il ne veut pas de ma pitié pour le moment."
scene bg palace1 with dissolve
play loop "sfx/birds.ogg" fadein 3.0
"Alors, j'ai finalement laissé Cassius seul sur le lit et je suis retourné dans les couloirs, comme si des semaines s'étaient écoulées depuis ma dernière sortie ici."
"Je repense à ce que cette créature ressemblant à un dragon m'avait dit, à la façon dont je suis ici pour une raison, que tout a été planifié."
"Planifié par des parents qui semblent complètement frustrés par le comportement des loups et leur incapacité à mener à bien leurs \"plans\"."
"Pendant un bref instant, je me demande à quel point les choses se seraient déroulées plus facilement si j'avais été enlevé par quelqu'un comme Neferu et emmené quelque part comme Khemia."
"Mais alors je n'aurais pas rencontré Amicus."
"De plus, il semble que ce ne sont que les loups qui posent des problèmes aux parents, pas aux autres frères et sœurs."
"Ce qui me rappelle le seul petit conseil que les parents m'ont donné:« surveillez le chat »."
"Espionner Alexios."
"C'est quelque chose que je pense pouvoir faire, si je fais attention."
"Malgré le nouveau niveau de contrôle auquel je suis tombé, je me suis également promené dans les couloirs du palais ces derniers jours sans incidence."
"J'ai même rencontré Cato à quelques reprises, mais pour une raison quelconque, il m'a complètement ignoré."
"Tout pour le mieux."
"Alors, je commence à fouiller le palais à la recherche du chat."
"Il est en fait assez difficile à trouver quand il ne vous cherche pas, mais je sais au moins qu'il est habituellement dans les jardins, sinon dans les couloirs pour arroser les plantes."
scene bg garden2 with dissolve
"Alors après avoir mangé un déjeuner rapide, je décide de commencer ma recherche dans les jardins."
"Je regarde dans les deux sens à travers le feuillage alors que je marche tranquillement le long des différents sentiers."
"C'est calme, agréable et paisible, mais après tout ce qui s'est passé, cela a un côté inquiétant, comme si quelque chose pouvait me sauter dessus à tout moment."
"Je fais ça pendant environ une demi-heure avant de commencer à réaliser à quel point cette recherche pourrait être infructueuse."
"Alex serait difficile à trouver même s'il {i} était {/ i} ici, et en plus, il pourrait même être complètement en ville pour faire son \"travail d'ambassadeur\", quoi que ce soit."
"Juste au moment où je suis sur le point d'abandonner, j'entends quelque chose."
stop loop fadeout 5.0
"Reniflant, haletant et ... pleurant?"
"Je fais une pause, écoutant."
"C'est un peu difficile d'entendre à travers le léger bruissement des feuilles dans le vent, mais il y a certainement quelqu'un ici qui semble bouleversé."
"Je ne peux pas vraiment dire de qui il s'agit car on dirait qu'ils essaient de se taire."
"Ça, et il y a un autre son aussi; une autre voix, et celle-là que je reconnais."
"Alex»."
"C'est un léger murmure, comme s'il apaisait quelqu'un, probablement la personne qui pleure."
"J'attends là quelques instants, attendant de voir si le son s'estompe ou se rapproche, ce qui me dirait s'ils bougent, mais ça reste constant."
"Alors, convaincu qu'ils sont assis, ou du moins debout au même endroit, je me rapproche de l'endroit d'où vient le son."
"C'est dans une partie isolée du jardin, venant d'une petite place qui est entourée d'arbres et de buissons."
"Je connais cette place, celle avec la statue de Drusus, où j'avais été amenée à mourir."
"Je sais que je ne peux pas utiliser le petit chemin qui mène à la statue; je serais certainement vu, alors je marche vers les buissons qui l'entourent et commence à chercher une pause dans les différentes branches et feuilles."
"Le son sanglotant continue, et je peux entendre la voix d'Alex plus clairement maintenant."
"Je ne peux toujours pas dire exactement ce qu'il dit, mais j'attrape occasionnellement \"ne vous inquiétez pas\" et \"tout va bien\"."
"Je ne peux pas imaginer ce qui se passe là-dedans."
"Je commence à me demander si c'est exactement ce que les parents espéraient que je trouverais, et mon cœur se met à battre dans ma poitrine."
"Suis-je sur le point de trouver quelque chose qui va m'aider à sortir du désordre dans lequel nous nous trouvons?"
play music "music/romance.ogg" fadein 10.0
"Je trouve enfin une couverture plus fine dans le feuillage et je suis capable de voir à travers."
"D'abord, je vois Alex, le dos tourné vers moi, accroupi par terre devant la statue."
"Il est drapé sur quelque chose ... quelqu'un, les étreignant, son visage pressé sur le côté de leur tête."
"Je ne peux voir que leurs oreilles et des parties de leur épaule, mais je sais tout de suite que c'est Cassius."
"Il a la tête profondément inclinée vers le sol, ses pattes contre son visage, tremblant de ses sanglots."
"Alex le serre fermement dans ses bras, lui chuchote à l'oreille, essayant clairement de le réconforter."
"Cassius ne répond qu'en secouant occasionnellement la tête avant de finalement s'évanouir;"
c "\"Mais suis-je un fraudeur?\""
"Sa voix grince de façon inhabituelle sur le dernier mot et Alex répond avec un gentil« chut »avant de frotter le museau du loup.»"
"Je regarde encore quelques instants avant de reculer, me sentant mal à l'aise, sachant que c'est un moment privé entre eux deux."
"Je sais maintenant que cela ne m'aidera en aucune façon, à part me faire me sentir encore plus mal pour Cassius."
"Pourtant, j'ai trouvé Alex, alors je m'éloigne, vers un banc plus haut sur le chemin, un qui me donne une bonne vue de l'entrée de la place et à une distance qui ne me rendra pas suspect."
stop music fadeout 10.0
play loop "sfx/birds.ogg" fadein 5.0
"Une bonne dizaine de minutes s'écoulent avant qu'il n'y ait aucun mouvement."
"D'abord, Cassius sort, en train de redresser son armure, son expression vide alors qu'il s'éloigne du chemin, loin de moi."
"J'attends un peu ... un bon moment, peut-être encore cinq minutes, en me demandant si Alex a pris une sortie différente de la place."
"Mais à ce moment-là, je le vois sortir, l'air complètement neutre alors qu'il regarde autour de lui."
"Je me fige, je suis sûr qu'il est sur le point de me voir même si ça irait, mais il marche droit devant, vers l'étang."
"Je le regarde partir pendant un moment, puis je suis."
"C'est étrange d'essayer d'espionner l'ambassadeur de compagnie comme ça, surtout quand je n'ai aucune idée de ce que je fais."
scene bg garden1 with dissolve
stop loop fadeout 3.0
play music "sfx/fountain.ogg" fadein 3.0
"Mais c'est le seul indice qui m'a été donné pour libérer Amicus, et si c'est le seul moyen, alors je vais le faire."
"Je trouve le chat sur les piliers, déjà en train de s'éloigner des mauvaises herbes."
"Je soupire et j'attends, regardant pendant un moment, réalisant que cela pourrait durer des heures car Alex semblait toujours aimer désherber pour une raison quelconque."
"Le chat est si méticuleux dans le jardinage ici, et je dois me demander pourquoi, compte tenu de ses efforts, ne serait vraiment pas si visible dans un jardin aussi grand."
stop music fadeout 5.0
"Mais je me rappelle pourquoi je suis ici et je m'installe sur un autre banc, qui est également à une bonne distance pour ne pas paraître trop méfiant s'il me voit."
scene bg garden2night with fade
play loop "sfx/crickets.ogg" fadein 3.0
"Cette fois, je suis assis là pendant quelques heures, ajustant de temps en temps la façon dont je suis assis alors que mon cul se fait mal sur le banc de pierre, et au coucher du soleil, je réalise à quel point l'espionnage est ennuyeux."
"Vers la deuxième heure, le soleil s'est complètement couché, et je débat juste d'abandonner et d'essayer un autre jour."
"À ce moment-là, un drone dérive soudainement vers moi, me faisant sursauter et baisser un peu la tête, comme si cela m'aiderait à me cacher d'Alex."
com "\"Requêtes Neferu—\""
m "\"Chut!\""
"Je siffle au drone, et la voix de Com plonge automatiquement dans un murmure et continue comme si de rien n'était."
com "\"- votre emplacement et si vous avez besoin de son assistance.\""
"Bien sûr, à ce moment précis, je vois Alex se promener sur le chemin, bien qu'il ne se dirige pas vers le palais."
"Au lieu de cela, il commence à remonter le chemin dans ma direction et je trébuche rapidement hors du banc et dans les buissons, priant pour qu'il ne me voie pas alors que je me cache parmi les feuilles."
"Le drone me suit, puis s'arrête au bord du trottoir."
"Je me souviens que ces choses ne peuvent probablement pas sortir de la grille des sentiers."
"Juste à travers les feuilles, je peux voir les lumières de cette fichue chose allumée, attendant obstinément ma réponse."
"En même temps, j'entends le doux grattage des sandales d'Alex sur le chemin alors qu'il se rapproche."
"Bon sang."
"Cela aurait été mieux si je restais simplement sur le banc."
"Maintenant, ce drone va me révéler à Alex pendant que je me cache dans les buissons comme la personne la plus suspecte du palais."
"Je vois les pointes vertes des oreilles du chat pousser au-dessus des buissons alors qu'il fredonne doucement."
"Je m'accroupis plus bas dans le feuillage jusqu'à ce que je ne puisse même pas voir ça."
"Je veux que le chat ignore le drone, mais le bourdonnement s'arrête et ses pas aussi, et je sais qu'il l'a repéré."
al "\"Hmm, avez-vous un drone errant ici, Com?\""
com "\"Toutes les machines de drones sont prises en compte, Alexios.\""
al "\"Que fait celui-ci?\""
"Je sens mon cœur s'arrêter, avaler difficilement."
"Il y a une pause, comme si Com calculait quelque chose."
com "\"Cette information est classifiée, Alex.\""
al "\"Par qui?\""
com "\"Neferu.\""
"Il y a une pause, puis un petit rire alors que les pas d'Alex reprennent, s'éloignant plus loin sur ma gauche."
al "\"Oh, ce chacal.\""
"Je retiens toujours mon souffle alors que j'écoute les pas disparaître le long du chemin avant de me relever lentement de mon accroupissement, fixant le drone."
m "\"Dites à Neferu que je suis occupé, mais que je serai de retour ce soir. J'ai des choses à lui dire.\""
com "\"Message reçu. Merci [mc].\""
m "\"Ouais, pas de problème.\""
"Je le dis sarcastiquement alors que le drone s'envole lentement et paresseusement."
"À ce stade, le soleil s'est complètement couché, et je me demande pourquoi Alexios s'est dirigé dans cette direction particulière, menant soit vers les portes du palais, soit vers le lac."
"Je suis le chemin lentement, gardant les yeux ouverts pour le chat."
"Au début, je suis presque sûr qu'il se dirigerait vers la porte, peut-être en route pour la ville."
scene bg lakenight with dissolve
"Ce serait la fin de ma petite mission puisque je sais que je ne peux pas quitter les limites du palais sans être ... blessé d'une manière ou d'une autre, probablement tué."
"Mais à la place, je repère la forme du chat, à peine visible devant le lac, sa surface scintillant à la lumière de la lune."
"Je m'arrête et me cache derrière un arbre, en m'assurant que je ne suis à proximité d'aucun des lampadaires."
"Je regarde Alex se déplacer sous le petit belvédère avec les motomarines en dessous."
"Effectivement, quelques minutes plus tard, il arrive en planant sur le Sightseer."
"Il flotte sur le rivage, puis sur le lac ... en direction de l'île."
"Je sais tout de suite que je vois quelque chose d'important."
"Il n'y a rien sur l'île dont le chat doit s'occuper, pour autant que je sache, et à moins qu'il ne sorte pour une sortie nocturne sur la plage (extrêmement douteux), alors il fait définitivement quelque chose de suspect."
stop loop fadeout 5.0
"J'attends un moment, regardant la forme sombre du chat et de l'engin devenir de plus en plus petits jusqu'à ce qu'ils disparaissent fondamentalement, en direction de l'île."

scene bg emperorbedroomnight with fade
"Bien sûr, je sais que je ne peux pas le suivre là-bas pour le moment, mais je peux certainement en parler à Neferu ..."
"Neferu est dans sa chambre quand j'arrive, tapotant sur ce qui ressemble à une tablette transparente."
"C'est une chose étrange à voir compte tenu de l'inexistence de la technologie portable dans ce palais."
"Peut-être que c'est un truc khémien."
play music "music/memories.ogg" fadein 3.0
show nef at center with dissolve
"Dès qu'il me voit, le présentoir glisse de nouveau dans la petite barre de métal dont il faisait saillie alors qu'il se tourne pour me faire face."
n "\"Bonjour, [mc]. Vous étiez parti depuis un bon moment.\""
show nef a with dis
m "\"Euh, ouais.\""
n "\"Voulez-vous partager votre visite avec Cassius et, espérons-le, Amicus?\""
"Il me faut un moment pour me rappeler exactement de quoi il parle."
"Après mon petit voyage, tout ce qui s'est passé avant semble si lointain."
show nef talking f with dis
"J'essaie de dire à Neferu autant que je me souvienne d'avoir impliqué Cassius avant le truc des parents, et il semble impressionné."
n "\"Hm, je suppose que ramener Cassius à nos côtés ne sera pas aussi difficile que je l'avais pensé auparavant. Il semble qu'il ait des doutes similaires à propos de Caton.\""
m "\"Ouais, et Amicus va bien, juste un peu déprimé par tout ce qui se passe, évidemment.\""
show nef serious with dis
"Je fais une pause alors, ce que Neferu remarque."
n "\"Y a-t-il autre chose qui s'est passé?\""
"Je prends une profonde inspiration, réfléchissant à la meilleure façon de décrire ce que j'ai vécu."
show nef skeptic f with dis
m "\"Eh bien, quand je revenais, il y avait cette odeur bizarre venant de la salle de méditation ...\""
"Neferu lève un sourcil et je continue à expliquer comment je suis tombé à nouveau sur Cassius, puis tout ce qui s'est passé après."
"Quand j'ai fini, le chacal est calme, me regardant juste avec un regard rétréci."
"C'est généralement le regard qu'il me lance quand il réfléchit sérieusement à quelque chose, alors je lui laisse le temps de répondre."
show nef unsure f with dis
"Quand il le fait, c'est hésitant et réservé, ce n'est généralement pas quelque chose que j'entends de Neferu."
n "\"C'était donc une hallucination provoquée par la drogue, oui?\""
m "\"Eh bien, je suppose, mais je pense que c'était réel aussi. Genre, Cassius était là, et il se souvient de m'avoir vu avec lui.\""
n "\"Hmm ...\""
show nef serious with dis
m "\"Qu'est-ce qui ne va pas?\""
n "\"Eh bien, c'est une façon très ... primitive de contacter les parents. Pour le dire franchement, cela ne fonctionne pas. C'était une méthode utilisée dans les premiers jours, lors du premier contact entre le frère et le parent.\""
n "\"Ils se sont rendus à plusieurs reprises et entre les visites, certains frères et sœurs, en particulier les loups, tentaient de les contacter à nouveau via l'usage de drogues psychotropes. Cela pouvait occasionnellement apporter des visions d'êtres supérieurs, bien qu'ils ne soient pas les parents, bien sûr—\""
n "\"- des êtres simplement imaginés évoqués par un cerveau chimiquement déséquilibré.\""
show nef unsure f with dis
n "\"C'est probablement ce que vous avez vécu.\""
n "\"Pour vraiment contacter les parents, vous devez le faire via la technologie parentale; des machines complexes capables de transcender les dimensions.\""
n "\"Il n'est généralement utilisable que par une seule personne, comme l'empereur pour les loups ou le pharaon pour mon peuple.\""
"Neferu arrête de parler à ce stade, me permettant de prendre toutes ces informations."
"Alors peut-être que j'avais tout imaginé ... même si cela avait semblé si réel."
show nef talking with dis
m "\"Ils m'ont dit qu'ils avaient un plan pour moi et tout.\""
n "\"Souvent, ces drogues caressent l'ego de l'utilisateur. Ils vous donnent l'impression d'être au centre de l'univers, comme si vous étiez important ... sans dire que vous ne l'êtes pas.\""
show nef smile eyes a with dis
m "\"L'avez-vous déjà essayé?\""
n "\"J'ai eu des brosses avec de telles substances dans ma jeunesse. Bon pour expérimenter la fragilité de la réalité et la façon dont nous la percevons ... mais guère plus.\""
show nef with dis
m "\"Je vois.\""
n "\"Pourtant, il semble que vous ayez attrapé Cassius dans un moment de vulnérabilité. Il pourrait vous faire plus confiance à cause de cela, si vous traitiez la situation avec délicatesse.\""
m "\"Eh, peut-être.\""
"Je repense au moment où je l'ai vu pleurer devant la statue, mais je ne veux pas en parler à Neferu, ne pensant pas vraiment que ce serait si utile ... ou approprié à partager."
"Mais cela me rappelle ce que les \"parents\" m'avaient dit."
show nef talking f with dis
m "\"Eh bien, ils m'ont aussi dit autre chose; pour regarder Alex.\""
n "\"Est-ce qu'ils l'ont fait maintenant?\""
show nef with dis
m "\"Ouais, et je l'ai fait. Il agit bizarrement depuis que je suis arrivé ici, alors je l'ai espionné aujourd'hui et il est parti pour l'île au milieu du lac tout à l'heure.\""
"Neferu a un étrange sourire entendu sur son visage."
m "\"Quoi?\""
n "\"Je trouve juste intéressant que vous ayez des soupçons similaires sur Alex que moi.\""
m "\"Que voulez-vous dire?\""
n "\"J'ai moi-même étudié le chat et j'ai remarqué quelques trucs bizarres, y compris ses voyages sur l'île.\""
"Je fronce les sourcils."
show nef talking f
m "\"Quoi? Et tu ne me l'as pas dit?\""
n "\"Eh bien, cette situation plutôt désespérée dans laquelle nous nous trouvons n'est apparue que très récemment, et je n'avais guère utilisé cette information jusqu'à présent.\""
m "\"Eh bien, que pensez-vous qu'il fait?\""
show nef a with dis
"Neferu hausse les épaules."
n "\"Je ne sais pas car je ne l'ai pas encore suivi sur l'île. Vous pouvez imaginer que je prévois maintenant que nous pourrions également utiliser Alex de notre côté.\""
show nef with dis
m "\"Tournez tout le monde contre Cato?\""
n "\"Oui.\""
m "\"Donc s'il fait quelque chose de ... mauvais, alors nous l'utiliserons comme chantage?\""
n "\"Essentiellement. Il est la personne la plus proche de Cassius et pourrait éventuellement nous donner accès à des informations classifiées.\""
"Je soupire, de plus en plus fatigué de tout ce coup de poignard dans le dos."
m "\"Si c'est le seul moyen d'aider Amicus, je suppose.\""
n "\"Oh, il y a plusieurs façons, et j'ai un plan de dernier recours en place.\""
"J'attends, mais Neferu ne continue pas."
show nef serious with dis
m "\"Quel est?\""
n "\"Eh bien, compte tenu du droit d'aînesse d'Amicus, il a toujours la capacité de défier quiconque est sur le trône, mais—\""
m "\"Vraiment?\""
"Pendant tout ce temps, Amicus aurait pu défier Cassius à nouveau?"
"Alors je me rends compte que Neferu était sur le point de continuer."
m "\"Mais quoi?\""
n "\"Un combat à mort, puisque les loups aiment leur violence, même si l'empereur devrait accepter le défi.\""
"Cette pensée me rend instantanément malade."
m "\"Pas question.\""
n "\"Encore une fois, dernier recours. Je doute qu'Amicus défie son propre frère, et je doute que Cassius accepterait ... du moins pour le moment.\""
show nef with dis
"Je ne peux même pas commencer à envisager une situation comme celle-là, et Neferu change rapidement de sujet."
n "\"Quoi qu'il en soit, je devrais être parti. J'aimerais attraper Alex en flagrant délit et sur la base des observations précédentes que j'ai faites, il me reste une heure pour le faire.\""
"Je cligne des yeux de surprise."
m "\"Maintenant? Ne devrions-nous pas attendre comme ... demain soir?\""
n "\"Il n'y va qu'une fois par semaine. Compte tenu de l'urgence de notre situation, je devrais le faire maintenant.\""
show nef serious with dis
m "\"Puis-je y aller aussi?\""
n "\"[mc], tu te souviens de ce que j'ai dit sur la nécessité de te protéger?\""
m "\"Ouais, et c'est Alex. Que va-t-il faire?\""
n "\"Nous devons être prêts à tout.\""
m "\"Eh bien, je pense que c'est mieux si nous partons tous les deux, au cas où quelque chose {i} se produirait {/ i} et que vous auriez besoin de mon aide.\""
show nef sad a with dis
"Neferu laisse échapper un léger soupir."
n "\"Très bien.\""
"Je suis surpris de la rapidité avec laquelle il cède."
show nef angry with dis
n "\"Je suppose que vous méritez d'être traité comme un égal dans ces plans que nous élaborons.\""
n "\"Mais si Amicus découvre que je vous emmène dans ces missions, il aura ma peau.\""
m "\"Je lui ferai savoir que je voulais en faire partie.\""
n "\"Mhm, comme si cela allait le convaincre. Bref, allons-y.\""
hide nef with dissolve
m "\"OK.\""
stop music fadeout 5.0
"Mon excitation s'accélère alors que je me lève et que je suis Neferu jusqu'à la porte."
n "\"Si nous rencontrons quelqu'un, en particulier Cato, nous leur disons simplement que nous sommes dehors pour une promenade du soir, compris?\""
m "\"Ouais!\""

scene bg lakenight with fade
play music "sfx/lakesounds.ogg" fadein 5.0
"Malgré la situation potentiellement dangereuse dans laquelle nous nous trouvons, mon humeur est remontée en sachant que les choses bougent enfin à nouveau."
"Heureusement, il y a un autre vaisseau Sightseer dans le belvédère, même s'il a l'air beaucoup plus vieux et que le sol de celui-ci n'est pas transparent, ce qui me convient."
"Je préfère ne pas regarder dans la noirceur d'encre de l'eau sous mes pieds en naviguant vers l'île."
"Neferu est calme la plupart du temps, l'air confiant dans tout ce qu'il fait pendant qu'il prépare le métier."
"Enfin, il tend la patte pour me tirer chevaleresque à bord."
"Le lac tourne tranquillement autour de nous alors que nous nous approchons de l'île; une masse noire parmi les ondulations du clair de lune réfléchi dans les vagues."
"J'ai immédiatement aperçu l'engin d'Alex assis sur la plage près de l'endroit où nous avions eu notre petit pique-nique il y a toutes ces semaines."
scene bg islandnight with dissolve
"Nous remontons un peu plus le rivage, hors de vue de l'engin avant de dériver sur la plage."
"Neferu me tend encore une patte pour m'aider à descendre, même si je n'en ai pas besoin."
show nef with dissolve
"Alors que je m'installe sur le sable, il se penche pour me chuchoter à l'oreille."
n "\"Attendez ici. Malheureusement, je crois que les bruits de pas simiens sont plus bruyants que ceux d'un chacal.\""
show nef smile eyes with dis
m "\"D'accord ... mais appelez-moi si quelque chose se produit ou si vous avez besoin d'aide.\""
"Je vois un sourire sur le visage de Neferu, et même si c'est amusé, ce n'est pas du tout condescendant."
hide nef with dissolve
n "\"Bien sûr, mon ami.\""
"Et avec ça, le chacal disparaît dans la nuit, me laissant avec seulement le petit engin et les doux sons des vagues pour me tenir compagnie."
"Je n'ai pas à attendre longtemps avant d'entendre des voix venant de plus haut sur la plage, et je sais tout de suite que c'est Neferu et Alex."
"J'attends quelques instants pour voir si Neferu appellera mon nom."
"Quand il ne le fait pas, je fronce les sourcils et regarde autour de moi avant de me diriger tranquillement vers les voix."
"Ce n'est pas comme si je pensais qu'il avait besoin de mon aide, mais je ne veux rien rater d'important, et j'ai le sentiment que le moment de la confrontation avec Alex devrait m'impliquer."
"Au fur et à mesure que je me rapproche, je suis capable de distinguer les mots, et je vois qu'ils sont tous les deux juste à l'orée du bois, à quelques mètres l'un de l'autre."
show nef at right with dissolve
"Je m'accroupis et me cache le long de la limite des arbres en écoutant de plus près ce qu'ils disent."
show ale at left with dissolve
n "\"- belle nuit. J'ai toujours voulu venir sur l'île pour contempler la lune et la planète, loin des lumières du palais.\""
al "\"Ohh, je vois. C'est incroyablement beau ici, n'est-ce pas?\""
show nef unsure f with dis
"Alors qu'il parle de son ton typique et agréable, je peux certainement dire qu'Alex semble un peu nerveux, sa voix serrée et un peu essoufflée."
show ale sad e with dis
n "\"Alors ...\""
al "\"Oui?\""
show nef talking f with dis
"Alex regarde autour de lui nerveusement."
show ale shocked e with dis
n "\"Je vous ai entendu parler juste avant que je ne vous tombe dessus. Y a-t-il quelqu'un d'autre avec vous?\""
show nef smile eyes with dis
al "\"Moi? Oh non, certainement pas! Tu sais, c'est plutôt embarrassant, mais parfois je me parle juste à moi-même.\""
show ale smile with dis
n "\"Ne soyez pas gêné, c'est quelque chose que je fais aussi.\""
al "\"O — oh, je vois.\""
show nef smile with dis
"Alex semble se détendre un peu sous le traitement de Neferu, mais se crispe à nouveau à la phrase suivante."
show ale flustered e with dis
n "\"Bien que je ne murmure généralement pas aux arbres. Maintenant CELA est un peu étrange.\""
al "\"...\""
"Je vois les oreilles d'Alex s'aplatir, même si je suis un peu confus à la déclaration."
"Chuchoter aux arbres?"
al "\"je - je ...\""
"Alex ne semble pas avoir de réponse prête et bégaye de la manière la plus coupable qu'on puisse imaginer."
show ale sad at center with moveinright
show nef with dis
"Assez bizarrement cependant, il se rapproche de Neferu."
al "\"N — Neferu, c'est toi qui agis un peu bizarrement en ce moment, tu sais.\""
"Le comportement du petit chat change soudainement en une approche plus ... sensuelle, relaxant ses épaules et faisant glisser une patte le long de son corps."
"Cela ne semble pas du tout naturel, contrairement au sourire de Neferu alors qu'il regarde le chat qui approche."
"Il sourit toujours quand Alex tend la main pour prendre ses joues et l'embrasse sur les lèvres."
"Je cligne des yeux, surpris de la tournure soudaine que ce scénario a prise."
"Neferu a l'air tout sauf surpris, souriant tout au long du baiser alors qu'Alex essaie de s'embrasser plus profondément."
show ale serious e at left with moveinleft
"Finalement, le chat semble remarquer le manque de réponse du chacal et il recule en fronçant les sourcils."
show nef talking with dis
"Neferu secoue la tête."
show ale shocked e with dis
n "\"Oh Alex, tu sais que c'est ma technique. Cela ne fonctionnera pas sur moi. Maintenant, pourquoi ne regardons-nous pas cet arbre?\""
stop music fadeout 5.0
"Alex se fige, regarde autour de lui, et c'est à ce moment-là que je pense qu'il me voit."
play loop "music/tensebackground.ogg" fadein 3.0
al "\"Qui - qui est-ce?\""
hide ale
hide nef
with dissolve
"Neferu tourne légèrement la tête dans ma direction, et c'est là qu'Alex fait son mouvement."
"Il envoie un coup de pied en naviguant entre les jambes du chacal, et juste au moment où je me prépare à intervenir, la patte de Neferu est là, stoppant solidement l'attaque."
"Il y a une pause, Neferu tenant la jambe d'Alex, le forçant à s'équilibrer sur un pied alors que le sourire du chacal devient suffisant."
n "\"Quel dommage que vous ne soyez pas le premier à tenter une telle démarche sur moi. J'ai appris que les gens sur cette lune se battent sale.\""
play sound "sfx/thud.ogg"
"Alex couine, mais il fait quand même un coup de poing, envoyant un coup de poing droit dans l'estomac de Neferu."
"Il se connecte avec un bruit sourd creux, rebondissant sur les abdos du chacal comme s'ils étaient faits de briques, Neferu ne grognant que légèrement en réponse."
play sound "sfx/thud5.ogg"
with vpunch
n "\"Oof! Maintenant c'est un peu plus comme ça!\""
"Soudainement, Neferu utilise une jambe pour balayer le seul pied d'Alex du sol, envoyant le chat sur le dos dans le sable."
show ale vshocked e at left with dissolve
"Neferu le suit, clouant le chat là-bas, engloutissant presque Alex avec son corps beaucoup plus grand."
stop loop fadeout 5.0
al "\" Ah! Lâchez-moi! Aider!\""
"Alex me voit alors que je sors à l'air libre, debout à côté d'eux."
al "\"[mc]! Aide-moi! Le chacal est devenu fou!\""
show ale angry e with dis
"Je crois les bras et me tiens au-dessus de lui, et Alex se rend vite compte que je ne suis définitivement pas là pour l'aider."
al "\"Que faites-vous tous les deux !? Je t'ai dit que je ne savais rien [mc], pourquoi dois-tu continuer à m'attaquer comme ça!?\""
show nef talking f with dis
n "\"Attack {i}you{/i}? Then why is it {i}my{/i} stomach that is sore?\"" 
"Alex continue de se débattre docilement sous le chacal, sans même avoir l'air d'essayer de s'échapper."
n "\"Attaquer {i} vous {/ i}? Alors pourquoi est-ce {i} mon {/ i} estomac qui me fait mal?\""
show nef with dis
"Alex ne semble pas écouter et les larmes commencent à couler dans ses yeux alors qu'il commence à sangloter."
"Maintenant, je suis pleinement convaincu que ses sanglots dans la salle de bain étaient tous un acte."
n "\"[mc].\""
"Je reporte mon attention sur Neferu qui sourit toujours comme toujours."
n "\" A une dizaine de pas directement devant moi se trouve un grand arbre, plus grand que les autres qui l'entourent. Est-ce que tu le vois?\""
"Je regarde devant moi et vois immédiatement de quoi parle Neferu, l'arbre sensiblement plus grand que les autres, ses branches s'étendant sur des dizaines de pieds dans les airs, les feuilles ressemblant à de l'argent au clair de lune."
m "\"Oui.\""
show ale embarrassed e with dis
n "\"Allez-y, encerclez-le, voyez si vous pouvez trouver un creux.\""
"Je fais ce qu'on me dit, me sentant un peu appréhendé alors que je pénètre juste à l'intérieur des bois sombres."
al "\"Attends ... Neferu, [mc], je ne comprends pas ... pourquoi tu fais ça?\""
"Je réalise à ce moment-là à quel point je fais confiance à Neferu ici."
"Je n'ai aucune idée de ce qui se passe."
"Le tronc de l'arbre est assez épais pour que je ne puisse pas toucher les mains si je le serrais dans mes bras."
"Je commence à chercher le creux décrit par Neferu, et en me promenant autour de l'arbre, j'en aperçois immédiatement un de l'autre côté."
play music "music/tension.ogg" fadein 3.0
"Je regarde dans le trou noir, me sentant un peu nerveux à l'idée de ce que je pourrais y trouver."
m "\"Je foun—\""
"Je m'arrête comme une minuscule lumière rouge dans les fusées éclairantes creuses à la vie avec ma voix avant de disparaître à nouveau."
show nef talking with dis
m "\"Qu'est-ce que ...\""
"Cela se produit encore, palpitant au son de ma voix."
n "\"Vous l'avez trouvé?\""
show nef talking f with dis
m "\"Ouais, et il y a une petite lumière rouge là-dedans qui s'allume avec ma voix.\""
"Je regarde le flux et le reflux hypnotiques de la lumière pendant que je parle."
show ale serious with dis
n "\"Merci, [mc], vous pouvez revenir maintenant.\""
show nef with dis
"Avec reconnaissance, je retourne du côté de mon ami khémien, remarquant que le comportement d'Alex a complètement changé maintenant."
"Il est maussade, bien que presque inexpressif alors qu'il se couche sous le chacal, ne faisant même pas semblant d'essayer de s'échapper à ce stade."
n "\"Eh bien ... c'est réglé, n'est-ce pas, Alex?\""
"Alex reste silencieux, regardant le ciel."
show nef a with dis
m "\"Qu'est-ce que c'est?\""
"Neferu lève les yeux vers moi."
n "\"Technologie classique Omorfan-parent. Ils combinent souvent vie végétale et machinerie pour créer leurs gadgets. Plutôt ingénieux, et ils ont récemment partagé leurs connaissances avec nous sur Khemia.\""
al "\"Quelle erreur c'était.\""
show nef unsure f with dis
m "\"Attendez, mais qu'est-ce que c'est?\""
show nef smile a with dis
n "\"Un périphérique de communication; il utilise les branches comme une antenne massive, capable de transmettre des informations sur de grandes distances, même si elle les transmet probablement à Adastra City.\""
n "\"Il y a probablement un deuxième espion là-bas qui transmet ensuite l'information à travers une machine beaucoup plus puissante ... directement à Omorfa.\""
"Neferu sourit au visage d'Alex."
show nef with dis
n "\"N'est-ce pas vrai, Alex?\""
show ale embarrassed with dis
"Encore une fois, Alex reste silencieux, semblant s'être arrêté."
n "\"Alors, voulez-vous être celui qui le dira à Cassius, [mc]?\""
show nef smile eyes a with dis
"Cela fait finalement réagir Alex, et il se raidit, la fourrure hérissée alors qu'il grogne à Neferu."
al "\"Et pour quelle raison, chacal? Nous sommes tous des espions ici, y compris vous ... {i} en particulier {/ i} vous.\""
n "\"Oh? Je n'ai aucune idée de ce dont tu parles, Alex.\""
show ale serious with dis
"Le ton de Neferu dit le contraire."
show nef with dis
"Alex continue de fixer le chacal, sa fourrure recommençant à se mettre à plat."
al "\"Oh, tu penses que je suis si stupide? Tu penses que je te laisse juste me baiser sans aucun égard pour tes intentions, sans t'étudier? Je sais pourquoi tu es là, chacal.\""
show nef serious with dis
n "\"Éclairez-moi, {i} chat {/ i}.\""
al "\"Vous pataugez ici, cherchez à vous faire un nom. Le Pharaon vous a pratiquement jeté hors de la planète pour tenter de cultiver une alliance sans espoir sur Adastra.\""
"Les yeux de Neferu se rétrécissent."
al "\"Combien il doit être insatisfaisant d'être le second-né; incapable d'échapper à l'ombre de ton frère, incapable de rendre son père fier, coincé sur cette lune se faisant botter les couilles par les loups bigots.\""
show nef angry with dis
"Alex sonne et semble presque méconnaissable."
al "\"Même vos sœurs; les troisième et quatrième nés, ont obtenu des postes de plus grand prestige que vous.\""
"Je vois que Neferu s'agrippe plus étroitement à Alex, mais le chat continue."
al "\"À une époque où la famille royale a déjà renoncé à tant de pouvoir, vous êtes désespéré derrière cette façade de confiance, terrifié à l'idée de sombrer dans l'insignifiance historique.\""
al "\"Vous serez moins qu'une note de bas de page dans les livres d'histoire khémienne.\""
"Neferu ne sourit plus, et je peux dire qu'il a été pris au dépourvu tout autant que moi par le changement complet de caractère du chat."
"Pourtant, il garde sa prise sur le chat, remarquant froidement:»"
n "\"Je choisirais mes mots avec plus de soin si j'étais vous, compte tenu de votre position actuelle. Comme je le disais, nous en informerons l'empereur dès notre retour au palais.\""
show nef serious with dis
"Alex semble à nouveau se dégonfler, apparemment satisfait des coups qu'il a reçus sur le chacal."
al "\"Que voulez-vous?\""
show nef a with dis
stop music fadeout 10.0
play loop "sfx/lakesounds.ogg" fadein 10.0
n "\"Hm?\""
al "\"Ne jouez pas stupide, que voulez-vous de moi? Vous savez que j'étais un espion depuis que vous êtes arrivé ici et vous ne le faites maintenant que parce que vous voulez quelque chose.\""
show nef sidesmile f with dis
n "\"Oh, comme vous êtes prévenant, eh bien ...\""
"Neferu lève les yeux vers moi."
n "\"Que pensez-vous que nous voulons, [mc]?\""
m "\"Accès complet aux archives.\""
show nef skeptic f with dis
"Alex renifle."
al "\"Je n'ai pas ça.\""
n "\"Alors récupérez-le. Nous savons à quel point vous êtes proche de Cassius. Imaginez pourquoi vous en avez besoin, puis accordez-nous l'accès.\""
al "\"Pour quelle raison?\""
show nef serious with dis
n "\"Pour aider Amicus. Cassius ne sera pas blessé par cela. Vous avez jusqu'à la semaine prochaine, sinon l'empereur connaîtra votre trahison.\""
"Alex reste silencieux, et Neferu semble satisfait de cela, repoussant le chat et se levant."
hide nef with dissolve
n "\"Allons-y.\""

scene bg lakenight with dissolve
"Le chacal me parle vivement avant de tourner les talons et de retourner à l'engin."
"Je regarde Alex, regardant le chat fixer simplement les lunes, sans même me reconnaître."
"Le chemin du retour est un peu gênant, Neferu calme, clairement bouleversé."
"Je ne l'ai jamais vraiment vu comme ça avant, et je dois me rappeler que je vois probablement rarement le vrai Neferu."
"Il joue un rôle tout comme Alex, comme ils doivent tous les deux le faire."
"Et bien que je sois curieux de connaître sa situation familiale, j'ai assez de bon sens pour ne pas forcer."
"Au lieu de cela, je demande ce qui m'inquiète le plus:"
m "\"Qu'est-ce qui empêche Alex de nous trahir? Il pourrait tout aussi bien parler à Cassius de notre complot.\""
"Le chacal regarde dans l'eau, ses coudes sur la balustrade du Sightseer alors qu'il se penche."
n "\"Il ne le fera pas. Il ne peut pas supporter l'idée que Cassius sache sa trahison.\""
stop loop fadeout 5.0
"La confiance habituelle et la suffisance naturelle qui sont habituellement dans la voix du chacal sont complètement absentes, son ton plat."
m "\"Vous êtes sûr?\""

scene bg palace1night with transition_fade
play loop "sfx/crickets.ogg" fadein 3.0
n "\"Oui. Son amour pour Cassius est presque égal à celui de sa loyauté envers Omorfa, c'est pourquoi je lui ai assuré que Cassius ne serait pas blessé par nos plans. Nous n'avons pas à nous inquiéter.\""
"L'humeur du chacal me décourage de poser d'autres questions, et nous naviguons le reste du chemin vers le palais en silence."
"Trois jours plus tard, Alex est en mesure d'avoir un accès complet aux archives."
"Il ne nous explique pas comment il l'a fait, au lieu de cela, il a simplement informé Neferu du moment précis où il ouvrirait les archives pour nous et pour être prêt."
"Je n'ai pas à discuter pour venir cette fois, au lieu de cela, Virginia me dit que je vais devoir y aller si nous voulons effacer mon profil de la base de données du palais."
show ale serious with dissolve
"Faire cela me permettra de quitter le palais sans être tué par Com; juste un autre dernier recours au cas où les choses tournent mal."
"Neferu reste derrière cette fois, décidant que ce sera le mieux étant donné qu'il n'est pas exactement nécessaire pour ce que nous sommes sur le point de faire."
"Alex marche devant nous avec raideur, ne parlant pas ou ne nous reconnaissant pas vraiment de quelque manière que ce soit."
stop loop fadeout 3.0
"Je trouve cela énervant après avoir connu le chat pendant si longtemps, même si Virginia ne semble pas du tout dérangée."
scene bg archivesnight with dissolve
play sound "sfx/dooropen.ogg"
play loop "sfx/archives.ogg" fadein 3.0
"Nous marchons vers une partie du palais où je ne suis pas allé très souvent, principalement parce qu'on ne m'a jamais montré la région."
"Alex arrive à une porte sur laquelle il presse la main, et contrairement aux autres panneaux noirs, celui-ci clignote en vert avant que la porte ne s'ouvre."
"Nous entrons dans la pièce et je regarde les archives pour la première fois.»"
"Je suppose que je m'attendais à des rangées d'étagères, pleines d'un certain type de stockage numérique, ou de tout ce que les loups pourraient utiliser."
"Au lieu de cela, je suis accueilli par la vue d'une sphère géante, bleue, brillante, avec un motif en nid d'abeille couvrant sa surface."
"Ce qui est le plus frappant, ce sont les personnages tourbillonnants qui apparaissent et disparaissent juste au-dessus de la surface."
show ale serious with dissolve
"Ce sont des symboles que je ne reconnais pas, pas n'importe lequel que j'ai vu sur Adastra auparavant."
"Assis devant la sphère flottante se trouvent deux dragons de pierre, la bouche ouverte en grognements silencieux."
"Alex semble être pressé alors qu'il s'approche du globe."
"Sans hésitation, il enfonce sa patte dans le bleu tourbillonnant et les personnages et les tourbillons semblent se rassembler autour de lui avant que tout ne batte."
hide ale with dissolve
"Cela semble satisfaire le chat alors qu'il se détourne."
al "\"Cela devrait vous donner un accès complet. Vous êtes seul à partir d’ici.\""
"Avec ça, le chat part."
scene archives1 with slow_dissolve
"Je le regarde disparaître à la porte, pour la première fois un peu triste de la façon dont notre relation a changé."
"Virginia reste indifférente, marchant vers la sphère bleue alors que je suis."
"Je reste là maladroitement pendant un moment avant de m'éclaircir la gorge."
m "\"Alors qu'est-ce que c'est que ce truc?\""
v "\"L'archive.\""
m "\"Ouais, mais il semble -\""
show archives3 with dis
v "\"C'est parental, oui, et non, je ne sais pas comment ça marche. Il a également été utilisé comme méthode de communication avec les parents avant qu'ils ne cessent le contact, d'où l'oreiller de méditation.\""
"Virginia fait un geste vers l'oreiller avant de se pencher légèrement en avant, une traînée de lumière bleue s'enroulant brièvement autour de sa tête avant de se pencher en arrière."
v "\"Il se connecte au cerveau de l'hôte, semblable au lingua et fonctionne sur le contrôle de l'esprit.\""
m "\"Wow.\""
v "\"Oui, je ne l'ai pas souvent utilisé, mais il est assez facile à contrôler. Vous le saurez bien assez tôt.\""
scene archives1 with dis
m "\"Oh.\""
"Je me sens un peu nerveuse, mais Virginia se concentre sur le globe bleu."
"Soudain, un petit écran apparaît au-dessus de la sphère, et je vois à quoi ressemble l'amphithéâtre."
v "\"Hmmm ... quel jour s'est déroulé le dernier essai?\""
"Je suis sur le point de répondre quand, soudain, Virginia me fait signe de me taire, se concentrant à nouveau sur l'écran."
"Je vois la scène changer en un coucher de soleil sanglant, et je ressens la même anxiété que j'avais ressentie ce jour-là en voyant Cato et Amicus apparaître à l'écran, suivis par moi et Cassius."
show archives2 with dis
"L'angle est élevé et la scène est un peu éloignée, probablement du palais, mais je peux distinguer tout le monde clairement."
"Cassius se déshabille et descend les marches de l'amphithéâtre, et je veux détourner le regard, mais ne le fais pas alors que Cato se retourne contre Amicus et lui donne un coup de poing au visage."
"La réaction de Virginia est petite mais perceptible, clairement surprise par la brutalité de Cato."
"Ce qui suit est la pose maladroite et mise en scène, et l'épingle."
"Ensuite, les images de moi utilisant le nerf sur Cassius."
"Ceci est suivi par Amicus arrachant la visière de Cato."
"Après cela, je cours hors de l'écran, et je peux regarder les drones descendre sur Amicus et il devient soudainement mou alors qu'ils, je suppose, l'étourdissent."
"Virginia regarde tout cela la bouche ouverte jusqu'à ce qu'Amicus soit escorté et Cato soit pris en charge par un petit navire qui atterrit au milieu de l'amphithéâtre."
"Puis elle secoue la tête."
v "\"Hommes ...\""
show archives4 with dis
"Virginia soupire de frustration alors que l'écran s'estompe."
m "\"Alors vous avez les images?\""
v "\"Je l'ai classé dans un domaine accessible à la fois par moi et par Neferu. Nous trouverons un moyen de l'utiliser délicatement.\""
m "\"Et l'enquête sur le crash?\""
show archives1 with dis
"C'est quelque chose que j'avais soulevé à Virginia et Neferu avant notre arrivée ici, même si les deux semblaient sceptiques quant au fait que cela pourrait être utile de quelque manière que ce soit."
"Que même Caton ne serait pas assez sournois pour tuer son propre ami, un ami qui se trouvait être l'empereur."
"Même maintenant, Virginia soupire comme si c'était un inconvénient ennuyeux, mais se concentre pendant un moment jusqu'à ce qu'elle semble satisfaite."
v "\"Terminé, tous les documents liés à l'enquête se trouvent désormais au même endroit. Nous y reviendrons plus tard ... eh bien, au moins vous et Neferu pouvez.\""
show archives4 with dis
"Il y a une pause momentanée."
m "\"Eh bien, c'était facile.\""
v "\"A quoi vous attendiez-vous? La technologie parentale rend tout rapide et facile.\""
m "\"Ouais, je suppose.\""
v "\"Alors ... êtes-vous prêt à l'utiliser?\""
m "\"Je - je pense que oui.\""
"Virginia me sourit."
v "\"Ne vous inquiétez pas, c'est facile. Gardez simplement votre esprit à l'écart de tout sauf de votre objectif; votre profil et comment l'effacer de l'archive.\""
m "\"Mon profil ...\""
show archives1 with dis
"J'essaie de trouver comment je devrais imaginer un profil, mais Virginia m'arrête."
v "\"Vous pensez déjà trop. Juste ça; votre profil, effacez-le des archives.\""
"J'avale fort, mais permets à Virginia de me pousser doucement en avant jusqu'à ce qu'une des vrilles touche ma tête."
stop loop fadeout 5.0
"C'est une sensation de fraîcheur au début, puis soudain mon corps se saisit involontairement alors que j'ai l'impression que tout mon cerveau se contracte."

scene bg black with slow_dissolve
play music "music/between dimensions.ogg"
v "\"Restez concentré sur votre objectif.\""
"Mon profil, parti ... mon profil, efface-le ... mon profil ... supprime des archives ..."
"Un poignard, des cris, de la douleur, du sang, un souffle sifflant, des giclées rouges, une angoisse absolue -"
a "\"[mc]! Non je t'en prie! Ne me laisse pas ici! S'il te plaît, reviens moi! Tu ne peux pas me laisser seul comme ça!\""
"Amicus hurle droit dans mon oreille, et je ne l'ai jamais entendu sonner comme ça avant."
"C'est horrible, et je sais que j'ai besoin de le réconforter, de lui dire que je ne pars pas, mais ma voix est partie et l'air siffle de ma gorge."
a "\"Non, non, non ... parlez-moi!\""
"La voix d'Amicus monte en intensité, paniquant, devenant désespérée."
"Alors tout s'arrête."
"..."
mon "\"Vous pouvez empêcher cela ...\""
"..."
mon "\" Mais seulement si vous vous soumettez à la volonté bienveillante des parents ... "

menu:
    "Oui":
        $ end_game1 += 1
        $ fate = True
        "..."
    "Non":
        $ end_game3 += 1
        "..."

scene bg archivesnight
"..."
mon "\"Veux-tu?\""
show vir serious with dissolve
"Je halète et me recule, la tête bouleversée."
"Je sens des pattes douces mais fortes me serrer autour des épaules."
v "\"Ça va?\""
"Je regarde autour de moi, les yeux écarquillés, me sentant presque malade alors que cette étrange sensation de contrôle dans le cerveau disparaît soudainement."
m "\"Je—\""
"Je ne sais pas quoi dire, et Virginia jette un coup d'œil à la sphère."
v "\"Peut ne pas convenir à un cerveau simien. Com?\""
com "\"Oui Virginie?\""
v "\"Localisez le profil de [mc].\""
scene bg palace1night with dissolve
com "\"Il n'y a pas de profil archivé.\""
v "\"Eh bien, vous l'avez fait au moins. Retournons dans la chambre de Neferu.\""
"Nous traversons les couloirs, Virginia devant aider à cause de mes pieds instables."
"Je suis abasourdi, j'ai l'impression que je reviens juste d'un autre voyage de drogue."
"Mais ce n'est pas ce que j'ai ressenti, ni même les visions de violence qui m'ont secoué."
"Ce sont les cris de désespoir d'Amicus qui persistent dans ma tête ..."
stop music fadeout 5.0

scene bg dungeons with transition_fade
show ami u with dissolve
"Je dois le voir le plus tôt possible."
play music "music/dawn.ogg" fadein 3.0
"Je dois m'assurer qu'il va bien."
a "\"Mmmh, tu sens si bon ...\""
"Amicus m'a épinglé au sol sur la petite couverture que j'ai apportée avec moi."
"Il m'étouffe avec son grand corps, se frottant contre moi alors qu'il me lèche et mordille le cou."
"Je ne suis même pas venu plus d'une minute."
m "\"W - attendez, que se passe-t-il si ... et si Com voit ...\""
show ami eyes u with dis
"Je halète autour des coups de langue et Amicus répond en tenant ma tête dans ses pattes géantes, me gardant stable alors qu'il commence à pousser ses hanches contre moi, ses cuisses forçant mes jambes vers le haut."
"Amicus marmonne dans ma gorge."
a "\"Alors laissez-le regarder.\""
"Com ne regarde pas, pour autant que je sache."
"D'une manière ou d'une autre, j'ai réussi à convaincre Cassius de nous donner plus d'intimité."
"En fait, je pense que je l'avais juste dégoûté quand je lui avais demandé, plissant le nez alors qu'il demandait à Com de garder le drone en haut de l'échelle cette fois."
"À ce moment-là, je sens la longueur dure du loup presser mon cul, et même si je suis en sous-vêtements et en robe, je me retire."
m "\"Whoa, pas maintenant, Amicus!\""
"Amicus continue de me blottir contre moi, de se déplacer vers mon visage et de verrouiller les lèvres avec moi pendant plusieurs secondes pendant qu'il continue de pousser ses hanches contre moi."
"Il recule enfin un peu."
a "\"Je sais, je joue juste un peu. Je suis ici depuis trop longtemps. Je t'aime, tout de toi.\""
m "\"Clairement.\""
"C'est tout ce que je peux dire avant qu'il ne recommence à m'embrasser, à me lécher et à sucer et je suis au moins content que ça ait le goût de lui donner ce rince-bouche ici."
"Je n'ai jamais vu Amicus aussi excité auparavant, qui dit quelque chose, ses pattes me serrant et me caressant presque désespérément alors que son museau embrasse chaque centimètre carré de mon cou et de mon visage."
"Il pousse son corps contre le mien, sa poitrine et son ventre considérables m'écrasant à plat contre le sol."
show ami surprised u with dis
"Mais quand son museau commence à descendre plus bas, reniflant contre ma poitrine et sous mes robes, je décide que j'en ai assez."
show ami embarrassed u with dis
"Je tends la main pour attraper son derrière surélevé, obtenant une poignée de cul épais et poilu alors que mes doigts se serrent dangereusement près de l'endroit sous sa queue."
"Comme on pouvait s'y attendre, Amicus halète de surprise et recule, s'asseyant rapidement pour que son dos soit bien appuyé contre la couverture et que j'aie enfin de la place pour m'asseoir moi-même."
show ami disappointed blush u with dis
a "\"A quoi cela servait-il?\""
m "\"Pour ne pas me laisser reprendre mon souffle. Et je sais que tu n'aimes pas les choses près de tes fesses.\""
show ami eyes u with dis
a "\"Eh bien, les empereurs ne devraient pas avoir d'objets près de leurs fesses.\""
"Je lève les yeux au ciel face à son insécurité stupide mais compréhensible, et je rampe vers Amicus pour m'asseoir sur ses genoux, le loup m'attirant avec impatience."
"Je t'aime.\""
m "\"Je t'aime aussi.\""
"Amicus frotte ses pattes de haut en bas sur mes bras et mes épaules, me sentant toujours dehors."
a "\"J'ai hâte de sortir d'ici. Plus besoin de me cacher quand je suis empereur. Je vais vous montrer le vrai Adastra. Être coincé derrière ces murs n'est pas la façon dont le bel amant de l'empereur devrait être traité.\""
"Je touche en arrière, pressant mes mains sur ses pattes et posant ma tête contre sa poitrine, écoutant le grondement de sa voix."
m "\"Oh? Et quel est le vrai Adastra?\""
"Amicus retire sa patte pendant un instant pour l'agiter dédaigneusement avant de la retourner pour la presser contre ma poitrine."
a "\"Ces politiques ... ça ne représente pas le vrai visage de la lune. J'ai besoin de vous emmener dans d'autres villes et paysages. Les gens sont également très différents d'une région à l'autre.\""
m "\"Mmmh.\""
"Je l'écoute avec satisfaction pendant quelques minutes, heureux de l'entendre parler à nouveau, rappelé à quel point il est facile pour nous de nous parler."
"Et nous avons en fait le temps de parler."
"Caton est dans une ville différente pour des affaires officielles, donc Cassius nous avait accordé au moins un peu plus de temps que la dernière visite."
"Amicus se balance d'avant en arrière alors que je caresse la fourrure sur sa poitrine, écoutant son rythme cardiaque."
"Il est clair qu'ils lui permettent de se baigner ici, mais l'absence de tout parfum ne laisse que la légère odeur de son musc naturel."
"Bien que l'odeur de lavande à laquelle je suis habitué me manque, je me fiche de l'odeur masculine qu'il dégage, surtout après nos petites retrouvailles tout à l'heure."
"Je veux rester ici pour toujours, me sentir complètement calme et en sécurité pour la première fois cette semaine."
show ami u with dis
"Je sais que ça doit finir cependant, et il y a tellement de choses à dire au loup, alors je me recule, levant les yeux vers le visage d'Amicus."
m "\"Amicus?\""
a "\"Oui?\""
m "\"J'ai besoin de vous parler de quelque chose.\""
a "\"Continuez.\""

jump a3s1