label a3s2:
scene bg lakewater with dissolve
play sound "sfx/splash.ogg"
"Je plonge dans l'eau en éclaboussant, le froid me coupe le souffle en un instant."
"Immédiatement, je me rends compte de l'erreur de sauter dans le lac avec une lourde robe."
"Je suis capable de sortir du vêtement ample en quelques secondes, et je commence à nager sur le bord du balcon, vers le rivage."
"Ce n'est pas si loin, mais je commence à m'inquiéter lorsque je sens mes bras et mes jambes brûler à cause de la tension, et même si la plage est juste devant moi, il semble que mes pieds mettent plus de temps à toucher le sol."
"Au moment où je sens que mes membres commencent à céder, je sens le fond sablonneux du lac contre mes orteils."
"Je halète de soulagement, luttant à travers l'extrémité la plus profonde des bas-fonds avant de trébucher sur mes mains et mes genoux, me forçant à avancer jusqu'à ce que j'atteigne la plage."
scene bg lakeside with dissolve
stop loop fadeout 5.0
"Même maintenant, dans ce moment de désespoir, je dois m'allonger dans le sable pendant un moment, à bout de souffle alors que je sens mes membres engourdis revenir lentement à la vie."
"Je suppose que toute l'anxiété et l'absence de nourriture de toute la journée m'ont laissé un sentiment de faiblesse."
"Je réalise enfin à quel point je suis exposé ici, à quel point il serait facile pour quelqu'un de me voir depuis les jardins, ou même depuis les fenêtres du palais."
"Avec un grognement, je me force à me retourner et à ramper vers la limite des arbres dans le jardin pour que je puisse au moins avoir un abri."
scene bg garden1 with dissolve
"Alors que je m'accroupis là, juste en sous-vêtements, essayant toujours de reprendre mon souffle, je réalise à quel point c'est calme ici."
"Encore une fois, c'est un contraste frappant avec la violence avec laquelle les choses avaient changé il y a quelques heures à peine."
"Finalement, après une profonde inspiration, je commence à me frayer un chemin à travers les jardins, en marchant à travers le feuillage plutôt qu'en empruntant les sentiers."
"Je doute que quiconque se promène dans le jardin compte tenu de ce qui s'est passé, mais la seule chose que j'ai apprise est que personne n'est prévisible ici."
"J'essaie donc de rester caché, en utilisant les grandes plantes d'apparence exotique comme couverture avant de sauter à travers les chemins et de me replonger dans la vie végétale."
"En me rapprochant du palais, j'essaye de réfléchir à la façon dont je vais faire ça."
"Avec un peu de chance, personne n'est réellement dans le palais."
"Cela aurait du sens après ce qui s'est passé."
"Si quelqu'un EST dans le palais, je dois juste espérer qu'il ne s'agit pas de Caton."
"Il y a aussi le problème de faire sortir Amicus des donjons."
"Bien que je puisse être aveugle à Com, Amicus ne l'est certainement pas."
"J'ai besoin d'arriver à Neferu."
"Il saurait certainement ce qui s'est passé maintenant."
"Peut-être que nous pourrions trouver un plan s'il n'en a pas déjà un."
"Il semble toujours savoir quoi faire ... enfin, d'habitude."
"Je dois juste espérer que quelque chose ne lui est pas arrivé."
"Alors, alors que je m'approche de l'entrée du palais, je regarde autour de moi, le calme commence à devenir énervant."
"Je ne vois personne donc, déglutissant durement, je fais du jogging à l'entrée du palais."
scene bg palace1 with dissolve
"L'air frais des couloirs frappe ma peau humide et me fait frissonner, à la fois du froid et de la tension."
"Je suis sûr de rester près des murs, regardant toujours devant une porte ou un pilier derrière lequel je peux me cacher au cas où je verrais quelqu'un."
"Heureusement, cela n'arrive pas, et je suis de plus en plus convaincu que personne n'est vraiment ici."
"Avant que je le sache, je monte dans le hall qui contient la chambre de Neferu."
"Ma respiration s'accélère à mesure que je me rapproche de la porte, sachant que je me sentirai beaucoup mieux si je peux juste avoir des conseils."
"Je suis ici depuis un moment et je me suis habitué à la façon dont les choses se passent, mais je suis complètement hors de mon élément maintenant."
"Je me dirige vers la porte et je tends la main, en appuyant sur le panneau pour le faire coulisser."
play sound "sfx/dooropen.ogg"
scene bg emperorbedroom with dissolve
"La salle est vide."
"Je regarde pendant un moment, comme si cela ferait apparaître le chacal comme par magie dans son lit où je l'ai vu pour la dernière fois."
"Alors je vois quelque chose sur le sol:"
"Des éclats verts de verre brisé; des bouteilles de vin sont tombées de la table au sol."
"Une sensation inquiétante commence à fleurir dans ma poitrine alors que je remarque les taches rouge violacé parmi le verre, le vin renversé a séché depuis combien de temps il est là."
"J'avale à nouveau pour mouiller ma gorge, regardant le plafond, sur le point d'appeler Com et de demander où se trouve Neferu avant de m'arrêter."
"Je ne sais pas si alerter Com de ma position est une bonne idée."
"Je suis à peu près sûr que la partie sécurité de l'IA est distincte du reste de Com, mais je ne veux pas le risquer."
"Je reste là pendant un moment, ne sachant pas quoi faire maintenant."
"Je pourrais faire le tour du palais à la recherche du chacal."
"Il pourrait être n'importe où, vraiment."
"Mais voir le verre, savoir ce qui s'est passé ..."
"... Je nie juste ce qui est évident ici."
"Je dois juste espérer qu'il va bien, peu importe où il a été emmené."
"Je m'appuie contre le cadre de la porte pendant un moment, essayant de penser à ce que je dois faire ensuite."
"Je pourrais chercher Virginia, mais je n'ai aucune idée de l'endroit où sa chambre pourrait être."
"De plus, si l'état de la chambre de Neferu est quelque chose à dire, je ne serais pas surpris si elle a également été emmenée quelque part contre sa volonté."
"Cato sait probablement tout sur ce que nous avions prévu."
"Il n'y a vraiment pas d'autre choix que d'aller dans les donjons, raconter à Amicus ce qui s'est passé, alors peut-être qu'il saura quoi faire."
"Juste au moment où je me retourne pour retourner dans le couloir, j'entends des pas."
"Je rentre rapidement dans la pièce, atteignant le panneau pour refermer la porte."
"Avant de le faire, j'entends autre chose."
"Le son de marmonner dans une voix très familière."
"Je m'attarde juste à l'intérieur de la pièce, écoutant la voix se rapprocher."
al "\"Oh mon Dieu, oh Galen, c'est trop ... trop!\""
"Je serre les dents, écoutant le chat se rapprocher, comme s'il était seul."
"Je me décide soudainement à ce que je vais faire ensuite."
al "\"Je vais être tué ... Je vais être tué ... à quoi pensais-je!?\""
"À ce moment-là, le chat passe la porte."
"Il a ses pattes sur les côtés de son visage, trop occupé à regarder le sol pour même me remarquer."
"Il est assez proche pour que tout ce que je dois faire est de tendre la main et de l'attraper par les bretelles de sa robe avant de le tirer dans la pièce aussi fort que possible."
"Immédiatement, le chat hurle, le son se pliant comiquement avec la force de mon remorqueur."
"Je le balance vers le milieu de la pièce avant de me retourner pour fermer rapidement la porte."
play sound "sfx/doorclose.ogg"
"Alex hurle toujours alors qu'il tombe au sol, roulant plusieurs fois avant de s'arrêter à côté des bouteilles brisées."
"Il se recroqueville là-haut, couvrant son visage alors qu'il se recroqueville sur le sol."
show ale vshocked e with dissolve
al "\"Attendez! Attendez! Je suis désolé pour tout ce que j'ai fait!\""
"Le chat continue de ramper avant de finalement jeter un coup d'œil à travers ses pattes pour me regarder."
"Il se tait, bien qu'il reste foetal, comme s'il décidait s'il devait encore avoir peur ou non."
"Soudainement, il semble se décider et se lève rapidement, balayant la poussière imaginaire alors qu'il fixe son visage dans un visage de désintérêt fade."
show ale serious with dis
al "\" Oh [mc], je pensais que vous pourriez être quelqu'un d'autre. Mes excuses.\""
"Je regarde."
al "\"Quelle raison avez-vous de m'attraper si brutalement?\""
m "\" Non, plus de conneries de votre part. Que diable se passe-t-il?\""
"Le chat arrête finalement de s'agiter et me fait face, bien qu'il ne fasse pas de contact visuel, fixant la porte derrière moi à la place."
show ale tilt with dis
al "\"Eh bien, je suis sûr que vous le savez déjà, n'est-ce pas? Je suis surpris que Cato vous ait laissé sortir, pour être honnête.\""
"Quelque chose dans le comportement d'Alex, non seulement la façon dont il agit maintenant, mais la façon dont il agit depuis un mois, me touche à ce moment-là."
"Je fais un pas en avant soudainement, et bien que je veuille le frapper, je me contente de lui donner une forte poussée dans la poitrine qui le fait trébucher avec un claquement bruyant de ses sandales sur le sol de pierre."
show ale vshocked e with dis
m "\"Qu'est-ce que c'est putain, Alex!?\""
play music "music/tension.ogg" fadein 3.0
"Il mouline ses bras, essayant de retrouver son équilibre, et quand il le fait enfin, il ramène ses pattes contre sa poitrine, ses oreilles épinglées en arrière et ses griffes dégainées."
show ale angry e with dis
"Je ne sais pas si Alex est doué pour se battre, mais je préfère ne pas me faire prendre par ces choses, alors je me retiens de lui donner une autre poussée."
"De plus, il a de nouveau l'air effrayé, me regardant les yeux écarquillés."
al "\"D - ne me touchez pas!\""
"Je serre les dents, me forçant à ne plus recommencer."
m "\" Alors dites-moi ce que vous faites. Pourquoi as-tu fait cela?\""
al "\"Quoi?\""
"Cette fois, je fais un pas en avant et lève le poing de manière menaçante, et immédiatement le chat se couvre le visage, se recroquevillant."
show ale vshocked with dis
"Je me rends compte alors qu'Alex n'a probablement aucune compétence de combat."
"Qu'il pourrait en fait être un lâche plutôt que de simplement prétendre l'être."
"Cette prise de conscience refroidit mon désir de vraiment blesser le chat."
"Au lieu de cela, j'attends de nouveau qu'Alex abaisse sa patte, me regardant avec peur."
show ale sad e with dis
"Je suppose que c'est une bonne chose."
"Amicus m'avait dit dans le passé que les quelques primates intelligents des {i} Galaxias {/ i} ne sont vraiment connus que pour quelques petites choses, l'une étant qu'ils ne savent pas nager et l'autre étant leur incroyable force."
"Je suppose que c'est une bonne réputation d'avoir, même si ce n'est pas vrai pour les humains, mais Alex ne le saurait pas."
"Je fais un autre pas menaçant en avant."
m "\"DITES-MOI.\""
show ale vshocked e with dis
al "\"Très bien!\""
"Je suis surpris par l'exclamation soudaine du chat, ses yeux fermés alors qu'il lève ses pattes jusqu'à sa fourrure de tête, tirant dessus avec détresse."
al "\"Je vais vous dire ce que vous voulez si vous me laissez tranquille! Je suis fatigué de ce putain de palais et des loups psychopathes et des enfants à moitié développés!\""
"J'ignore ce coup sur moi, regardant le chat, attendant."
show ale sad with dis
al "\"Je serai probablement expulsé bientôt de toute façon ... s'il n'est pas exécuté.\""
"La voix du chat se coince dans sa gorge, et il lève une patte à sa bouche, apparemment sur le point de pleurer à nouveau."
"Il a vraiment peur, et cela me donne une idée."
m "\"Ecoute ... j'essaye d'aider Amicus à occuper sa place légitime sur le trône ... peut-être que si tu m'aides, et qu'Amicus devient empereur, je peux trouver quelque chose pour toi. Vous savez à quel point nous sommes proches.\""
"J'attends pendant qu'il essaie de se ressaisir, joignant ses pattes ensemble avant de simplement regarder le sol."
"Il ne dit rien cependant, alors je soupire."
m "\"Pourquoi avez-vous parlé de notre plan à Cato?\""
"Alex fait écho à mon soupir, détournant les yeux sur le côté."
al "\"Je - il y a beaucoup de politiques {i} Galaxias {/ i} que vous ne comprendriez pas [mc] -\""
m "\"Eh bien, simplifiez-le pour moi, alors. Je suis peut-être à moitié développé, mais je pense que je commence à comprendre comment les choses fonctionnent ici.\""
al "\"R - Et si je te le dis, tu m'aideras à quitter cette lune maudite?\""
"Je serre les dents."
m "\"... Oui.\""
"Alex me regarde de côté avant de secouer la tête."
al "\" J'étais ... Je suis devenu un animal de compagnie pour une seule raison, pas pour des relations d'ambassadeur, ni pour des relations Adastra-Omorfa ... même pas pour recueillir des renseignements ...\""
al "\"Je veux dire, à l'origine que {i} était {/ i} mon but, mais je suis devenu proche de Cassius au cours de plusieurs réunions et dîners officiels.\""
al "\"Mon service a pris note et ... et a modifié mon affectation.\""
"Le chat redevient silencieux."
m "\"Très bien, alors qu'est-ce que tu es là maintenant?\""
"Alex prend une profonde inspiration et me regarde dans les yeux."
show ale serious with dis
al "\"Chaos.\""
"J'attends, mais c'est tout ce que dit le chat."
"Je lui fronce les sourcils."
m "\"Vous êtes ... ici pour créer le chaos?\""
"La voix d'Alex devient soudainement monotone."
al "\"Un gouvernement instable crée une société instable.\""
al "\"Le progrès est au point mort et les efforts extérieurs se tournent vers l'intérieur. La société s'inquiète moins de ce qui se passe en dehors de ses frontières tout en se préoccupant davantage de ses propres problèmes.\""
"C'est comme s'il récitait quelque chose qu'il avait entendu plusieurs fois auparavant."
"En y réfléchissant, l'explication semble avoir une raison."
"Les décisions apparemment insensées d'Alex, les alliances changeantes et le comportement étrange général pourraient être expliqués par cela."
"Il n'est là que pour rendre les choses plus difficiles pour que les loups s'intègrent de nouveau dans les {i} Galaxias {/ i}."
"Pour les empêcher de sortir du marasme technologique et économique dans lequel ils se trouvent actuellement."
"Il n'est pas seulement contre moi, Amicus, Cassius ou même Cato, mais plutôt contre nous tous à la fois."
"Je pense à la fumée qui s'échappe d'Adastra City, à ce qui arrive probablement à des dizaines de villes en ce moment, et je ressens soudain un sentiment de dégoût accablant pour le chat en face de moi."
"Il s'est passé beaucoup de choses sur cette lune qui m'ont dérangé, mais cet acte de sabotage particulier est probablement le pire."
"Juste quelque chose sur la façon dont c'est insouciant; ne pas savoir ce qui va même se passer, juste que ça va blesser l'empire, le peuple ..."
"Alex voit l'expression sur mon visage et prend rapidement du recul, détournant les yeux."
show ale shocked with dis
al "\"Je comprends que cela peut sembler dur, mais il est de mon devoir envers Omorfa et les {i} Galaxias {/ i} dans leur ensemble de nous protéger d'Adastra. Toi ... si tu connaissais l'histoire—\""
m "\"Je suppose que vous avez lancé les rumeurs sur les triumvirates, puis que vous les avez épinglées sur moi?\""
al "\"Je - je ... J'ai peut-être lancé les rumeurs, mais je ne vous ai jamais impliqué.\""
m "\"Mais vous saviez que cela arriverait.\""
show ale sad e with dis
"Alex ouvre la bouche, puis la ferme, détournant les yeux à nouveau."
m "\"Et après que je me sois réveillé dans les jardins, je t'ai parlé du médecin ... tu as probablement parlé à Cato de notre relation alors aussi.\""
"Alex fronce les sourcils profondément, prenant un autre pas en arrière, ressemblant presque à un enfant qui s'est fait prendre en train de faire quelque chose de mal."
"Je sens mon visage devenir chaud, je ne suis plus vraiment sûr de pouvoir me retenir de céder le visage de ce chat."
"Peut-être plus tard ... mais ce n'est pas important pour le moment, même si cette créature en face de moi est responsable de la moitié de mes problèmes ... sinon de tous."
m "\"Où est Neferu ou Virginie?\""
"Alex a l'air surpris pendant un moment du changement soudain de conversation."
show ale shocked with dis
al "\"Eh bien ... Virginie doit épouser Cato plus tard dans la journée—\""
"Mon estomac vacille à cela, mais avant même que je puisse commencer à comprendre ce que cela signifie, Alex continue."
al "\"Quant à Neferu, eh bien ... vous ne savez pas?\""
m "\"J'ai été enfermé dans la chambre d'Amicus toute la journée. Je ne sais rien.\""
show ale sad e with dis
al "\"Ah bien ... Neferu doit être exécuté, je pense ...\""
"Je regarde."
m "\"Quoi, quand!?\""
al "\"Je - je ne suis pas tout à fait sûr, je me suis réveillé seul dans la salle à manger et je l'ai vu sur les chaînes d'information.\""
m "\"Non, quand est-il exécuté?\""
al "\"Je ne sais pas ... ça allait se passer aujourd'hui.\""
m "\"Mais ce n'est pas encore arrivé, non!?\""
al "\"je - je - je ne sais pas -\""
m "\"COM!\""
"J'ai interrompu Alex, ne me souciant plus d'alerter Com de ma position."
com "\"Oui, [mc]?\""
m "\"Neferu a-t-il été exécuté?\""
"Il y a une pause."
"Pendant un moment, tout ce que je peux entendre, c'est mon battement de cœur qui bat dans mes oreilles, et pendant un moment surréaliste, j'ai l'impression que je vais m'évanouir et je dois rectifier ma position pour m'assurer de ne pas tomber ."
"La pause semble plus longue que la normale, comme si Com avait du mal à trouver les informations que j'ai demandées, alors—"
com "\"Voici ce que j'ai trouvé: l'exécution de Neferu, le deuxième fils du pharaon, doit avoir lieu dans l'amphithéâtre royal à la quatorzième heure pour crimes d'espionnage et de complot en vue d'assassiner l'empereur Cassius.\""
com "\"L'exécution sera diffusée en direct sur tous les publics—\""
m "\"Combien de temps avant les quatorze heures!?\""
com "\"Quatorze minutes et trente et une secondes.\""
m "\"MERDE!\""
"Qu'est-ce que je suis censé faire?"
"Ce n'est pas du tout assez de temps."
"Même si je peux rejoindre Amicus, je ne peux pas le faire sortir à temps avant… \""
mon "\"{cps=20} {i} ... le chat ... {/ i}\""
"Je tourne les yeux sur Alex, et il recule immédiatement, tremblant."
show ale shocked with dis
m "\"Pouvez-vous faire sortir Amicus des donjons?\""
al "\"je — je—\""
"À ce moment-là, je l'ai presque giflé, mais je force obstinément mes mains tremblantes à rester à mes côtés."
m "\"Pouvez-vous le faire sortir, putain, ou pas?\""
show ale flustered e with dis
al "\"Je ... pense que oui. Cassius m'a donné un accès presque illimité à la sécurité de Com—\""
"Mon cœur bondit dans ma poitrine."
m "\"Alors allons là-bas et sortons-le.\""
"Je me tourne vers la porte, mais remarque qu'Alex est toujours figé au même endroit."
"Le regard sur mon visage le fait reculer à nouveau."
al "\"O - oui, mais ... vous ne le laisserez pas emprisonner ou m'exécuter si je le fais?\""
m "\"Alex ... {i} Je {/ i} te tuerai tout de suite si tu ne fais pas ce que je te dis!\""
show ale vshocked e with dis
"Le chat sursaute et hurle alors que je lui crie dessus, se précipitant pour sortir par la porte avec moi sur ses talons."
hide ale with dis
"Le chat avait au moins raison sur une chose:"
"Je ne pourrais jamais être un \"diplomate\" si c'est vraiment ce qu'il est."

scene bg palace1 with fade
"Je suis le plus près possible du chat, en marchant pratiquement sur ses talons."
"Alex en est clairement conscient alors que ses oreilles se tordent nerveusement, essayant de me jeter un regard discret de temps en temps."
"A mi-chemin des donjons, le système PSA crépite au-dessus de nos têtes."
com "\"Citoyens d'Adastra; veuillez vous préparer à une adresse impériale de l’empereur Caton.\""
"Alex regarde en arrière, mais je le force à continuer avec quelques insinuations dans son dos, priant que peut-être que cela n'ait pas à voir avec l'exécution, ou que Cato annule tout ça ensemble."
"Bien sûr, ce n'est pas le cas."
ca "\"Citoyens, c'est un jour mémorable dans la longue histoire de notre glorieuse lune.\""
"J'ai encore poussé le dos d'Alex."
m "\"Exécutez simplement.\""
"Alex fait ce qu'il a dit, même si ce n'est toujours pas aussi rapide que j'aimerais y aller."
ca "\"Après 10 000 ans, nous choisissons enfin notre propre chemin, nous prenons le contrôle de notre destin.\""
"Je commence à réaliser qu'après avoir attendu si longtemps, incertain de ce que pourrait être mon propre destin…»"
"... Cela va être décidé aujourd'hui, quel que soit le résultat."
ca "\"Et cela commence par montrer à nos frères et sœurs que nous ne tolérerons plus leur dépréciation, leur faux sentiment de supériorité, leur arrogance ...\""
"Alex et moi montons sur la porte qui mène au donjon et le chat commence maladroitement à descendre l'échelle, ayant beaucoup de problèmes avec ses robes."
ca "\"... et nous ne tolérerons surtout pas les espions, que j'ai agenouillés devant moi pendant que je parle.\""
m "\"Dépêchez-vous!\""
"Je crie après le chat alors que je commence à glisser moi-même sur l'échelle, le faisant presque tomber alors que nous atteignons le sol presque en même temps."
ca "\"L'offrant de fausses alliances, la putain de chacals, la fleur de Khemia ...\""
scene bg dungeons with dissolve
"Je suis le chat qui trébuche à travers la salle moisie du donjon, n'ayant jamais été dans cette profondeur avant de considérer que mes rencontres avec Amicus devaient avoir lieu près de l'entrée."
"Nous atteignons une porte de cellule, et Alex presse une patte sur un panneau sur le mur; une dalle de marbre beige plutôt que les panneaux noirs plus brillants ci-dessus."
play sound "sfx/dooropen.ogg"
stop music fadeout 10.0
"Il s'ouvre sur une petite cellule exiguë; un lit dans un coin, un lavabo, des toilettes et une petite douche dans un autre, et ce qui ressemble à un bureau près de la porte."
"Amicus est dans le lit, recroquevillé sur le côté, face à nous."
m "\"Amicus!\""
"J'ai poussé à peu près Alex, l'envoyant frapper face la première contre l'encadrement de la porte avec un hurlement."
"Le gros loup commence à bouger avant que je ne l'atteigne et que je lui jette mes bras."
"Je le sens sauter sous moi, et je sais que je viens de le réveiller."
"Il tourne la tête pour me regarder."
show ami surprised u with dis
a "\"[mc]?\""
"Il s'assoit contre mes étreintes, enroulant automatiquement ses bras autour de moi."
a "\"Attendez, comment avez-vous -\""
"Il regarde par-dessus mon épaule."
a "\"Alex?\""
m "\"Amicus! Caton est empereur, il est sur le point d'exécuter Neferu, vous devez…\""
"Je m'étouffe avec mes mots, sentant seulement maintenant le poids des informations que je viens de laisser tomber sur Amicus en ce moment."
m "\"- vous devez le défier pour combattre.\""
"Je me surprends quand je commence soudainement à pleurer, réalisant mes propres mots en les disant."
"À ce moment-là, je peux voir toute la confusion, la perplexité et le choc dans le visage de mon loup, sa bouche légèrement ouverte."
"Il veut probablement me poser un million de questions, mais dans cet espace de quelques secondes, je vois son expression se transformer en une sérieuse détermination."
show ami serious u with dis
a "\" Très bien. Où est-il?\""
"Le passage soudain de la confusion au sens du devoir et de la confiance m'arrête en fait de pleurer, alors même que les premières larmes coulent."
m "\" Le - l'amphithéâtre, ça se passe en ce moment. "
show ami u with dis
"Pendant juste un instant, le loup continue de me tenir, essuie une larme avec son pouce, puis me déplace doucement sur le côté alors qu'il balance ses jambes sur le bord du lit."
show ami serious u with dis
a "\"Alex, puis-je quitter le donjon?\""
show ale tilt at right with dissolve
al "\"Euh ... Com ... laisser Amicus quitter les donjons ... s'il te plait?\""
"Alex regarde le plafond, clairement incertain de ce qu'il fait."
com "\"Dois-je retirer Amicus de la liste des prisonniers, Alex?\""
al "\"Euh ... oui.\""
com "\"C'est fait.\""
"À ce moment-là, je réalise soudain que Cato n'est pas diffusé ici."
"Je ne sais même pas si l'exécution a été effectuée ou non."
"Amicus saute du lit."
a "\"D'accord, il faut bouger!\""
hide ami
hide ale
with dis
"Cette fois, Alex est frappé au cul alors qu'Amicus le roule pratiquement à la vapeur en sortant de la porte."
"Je saute par-dessus le chat en suivant le loup."
"Bien que beaucoup plus grand, Amicus est encore un peu plus rapide que moi alors que je sprinte après lui, ses pas tonitruants résonnant dans les couloirs."
"Il me crie en retour pendant que je le suis."
a "\"Et Cassius!?\""
m "\"Empoisonné! Il est ... je ne sais pas quel est son état en ce moment!\""
"Je souffle la réponse et je ne peux pas voir son visage alors qu'Amicus est silencieux, continuant à courir."
"Nous atteignons l'échelle et Amicus grimpe en quelque sorte la chose avec trois fentes gigantesques, sautant plusieurs échelons à la fois."
"Au moment où j'atteins le sommet, il est déjà hors de vue."
scene bg palace1 with dissolve
ca "\"Alors maintenant, que ce soit un avertissement à Khemia, ou à toute autre race de frères et soeurs ...\""
scene bg garden2 with dissolve
"Je cours dans les jardins, en direction de l'amphithéâtre."
"Je viens d'apercevoir la queue d'Amicus alors qu'elle disparaît autour de quelques arbres, sur le sentier qui mène à l'endroit où Cato devrait être."
ca "\"Nous n'hésiterons pas à vous éliminer si vous vous mêlez de nos affaires!\""
"Il y a un sentiment de finalité dans ces mots, et je sais que nous n'avons plus de temps."
"Je suis sur le chemin de l'amphithéâtre, et bien que cela ne prenne que quelques secondes pour arriver à la fin, cela ressemble à une éternité."
mon "\"{cps=20} {i} Vous êtes sur le bon chemin ... {/ i}\""
scene bg amphitheaterevening with dis
"J'ai fait irruption dans la clairière de l'amphithéâtre au moment où j'entends hurler Amicus."
a "\"arrêt!\""
play loop "sfx/forest.ogg" fadein 5.0
"Je regarde en bas des marches pour voir mon loup debout à la base de l'escalier, ses pattes écartées, debout devant Neferu et Cato."
"Le chacal est agenouillé sur le sol, ses pattes retenues derrière son dos d'une manière ou d'une autre, un air étourdi et incrédule sur son visage."
"Son visage est obligé de lever les yeux parce que Cato tient la fourrure de sa tête, inclinant la tête du chacal vers le haut pour que son cou soit complètement exposé."
"Dans l'autre patte massive de Cato se trouve une dague décorative brillante, dorée, à quelques centimètres du cou de Neferu."
"Pendant ce temps, juste en face de moi, assise devant la statue de Drusus se trouve Virginie, une tresse de fleurs sur la tête, l'air choquée alors qu'elle regarde son frère."
show ami angry u at left with dis
a "\"je vous défie Cato! Je vous défie à un procès par combat pour le trône, comme c'est mon droit d'aînesse!\""
show cat frown v at right with dissolve
"Il est toujours difficile de juger les expressions faciales de Cato, mais je peux voir la tension dans sa mâchoire depuis le haut."
ca "\"Qui ...\""
"Cato regarde vers le haut, et pendant un moment je me demande s'il sait d'une manière ou d'une autre que je suis là, qu'il peut me voir."
"Mais ensuite j'ai remarqué les drones de caméra planant au-dessus de ma tête, diffusant ceci à tout Adastra."
"L'empire tout entier voit cela."
show cat bow v with dis
ca "\"Pourquoi ... n'attendons-nous pas que ce soit fini, Amicus?\""
show ami crossed serious u with dis
a "\"Il serait sage de rester votre patte, Cato ... à moins que vous n'ayez peur de perdre l'épreuve?\""
show cat frown v with dis
"Le coin de l'œil cicatrisé de Cato se contracte."
"Je peux dire alors qu'Amicus joue tout cela aux caméras, et cela semble régler le problème pour Cato."
"Avec un grognement, il remet Neferu sur ses pieds par la fourrure de sa tête, faisant grimacer le chacal avant de le pousser vers le siège avant où Neferu s'effondre."
"Ensuite, le vieux loup passe devant Amicus, posant également le poignard sur le long banc incurvé, de l'autre côté de l'allée de Neferu."
show cat smile v with dis
ca "\"Tu sais quoi, Amicus? Je pense que tu as raison. C'est quelque chose que nous devrions faire immédiatement. Nous ne voulons plus laisser l'empire dans les limbes, n'est-ce pas?\""
"Amicus regarde l'autre loup avec lassitude alors qu'il marche autour de lui pour se tenir au centre de l'amphithéâtre."
ca "\"Il vaut mieux régler ... tout, le plus tôt possible.\""
"Je sais que Cato fait référence à nous tous ... Cassius, Virginia, Neferu, moi ... et je suis sûr qu'Amicus le fait aussi, parce qu'il me regarde juste un instant."
show ami serious u with dis
a "\"Alors réglons-le!\""
"Lentement, je commence à descendre les marches, jetant un coup d'œil à Virginia pour voir qu'elle est assise complètement droite, fixant Cato et Amicus, les pattes serrées sur ses genoux."
"Je me dirige vers Neferu qui est assis sur le banc avant, un peu penché, et je peux voir du métal scintiller là où ses bras sont retenus."
ca "\"Très bien, essai par combat, simple {i} pugnu {/ i} sans armes ... juste des dents et des griffes.\""
"Cato s'étire."
ca "\"Je vais vous donner l'avantage de la vue, Amicus. Cela ne devrait pas vous poser de problème, hein?\""
"Même si c'est vrai, Cato semble toujours très, très confiant."
"Et il a tout à fait le droit de considérer son habileté à se battre avec le fait qu'Amicus a été enfermé pendant plusieurs jours dans une cellule exiguë."
"Il a probablement dit ça seulement pour augmenter l'humiliation si Amicus perd ... s'il meurt."
"C'est alors que je commence à sentir la peur et la terreur commencer à traverser le choc engourdi que j'ai ressenti."
"Mais d'une manière ou d'une autre, Amicus a l'air complètement calme, et j'y trouve une sorte de réconfort."
hide ami
hide cat
with dissolve
"Tranquillement, je m'assois à côté de Neferu et il me regarde."
show nef unsure f with dissolve
n "\"Oh, [mc], qu'est-ce qui vous amène ici?\""
"Bien que ses paroles soient désinvoltes, son comportement suffisant habituel a disparu, pratiquement masqué alors qu'il est assis là, légèrement voûté."
m "\"Ça va?\""
"Je lui chuchote, et Neferu prend cela comme son signal pour le faire aussi."
"Le chacal hausse les épaules."
n "\"Pas exactement, non, mais je suis en vie pour le moment, donc je suppose que je ne peux pas demander beaucoup plus.\""
hide nef with dis
"Je regarde en arrière dans l'amphithéâtre, souhaitant pouvoir faire quelque chose de plus."
"J'essaye d'attirer l'attention d'Amicus, mais il reste concentré sur Cato, ses propres yeux plissés."
"Il a l'air confiant, préparé, prêt à tout ce que Cato lui lance."
"Mais je ne suis pas prêt."
"Je ne suis pas du tout prêt."
"Cette brève interaction dans le donjon, ces quelques secondes à s'accrocher l'un à l'autre."
"Cela pourrait être la dernière fois que nous ayons jamais…»"
"Je clignote à nouveau des larmes, sachant que cela ne me fera aucun bien pour le moment."
ca "\"Êtes-vous prêt, Amicus?\""
a "\"Oui.\""
ca "\"Alors commençons.\""
stop loop fadeout 3.0
play music "music/the fight.ogg" fadein 3.0
"Immédiatement, les deux loups commencent à se tourner autour de l'autre, les pattes relevées jusqu'à leur poitrine, ouvertes et prêtes."
"La seule différence par rapport aux combats passés avec {i} pugnu {/ i} que j'ai vus est qu'ils ont tous les deux montré les dents."
"Amicus le fait d'une manière que je n'ai jamais vue auparavant, même pas quand il était furieux."
"C'est vicieux, sauvage, comme j'ai vu des loups faire dans des documentaires sur la nature."
"Ensuite, ils s'affrontent."
"C'est tellement rapide que je ne suis pas capable de dire qui a bougé en premier, mais un moment ils sont séparés de plusieurs mètres et le suivant, leurs pattes sont jointes l'une à l'autre tandis que leurs mâchoires se brisent en l'air, toutes deux allant vers la gorge de l'autre."
"Des brins de salive scintillants s'envolent alors qu'ils mordent et se bloquent tous les deux avec leurs dents, les oreilles épinglées en arrière, faisant des aboiements et des grognements rauques et furieux."
"C'est quelque chose que je n'ai jamais vu un loup Adastran faire, même pas dans leurs faux drames."
"Cela semble brut et instinctif, comme si cela faisait partie d'eux, quelque chose qu'ils essaient de cacher, pour remonter à la surface quand ils essaient de tuer."
"Je me surprends à serrer ma poitrine, j'ai l'impression que mon cœur pourrait exploser alors que je regarde Amicus, essayant de voir s'il est blessé, grimaçant à chaque fois que j'entends le solide {i} claquement {/ i} de dents sur les dents."
"Cela n'a peut-être duré que quelques secondes, je ne peux pas le dire, mais finalement Amicus recule et Cato se précipite soudainement vers le cou de l'autre loup."
"Le temps semble ralentir, et pendant un moment je commence à penser à ce que je vais faire si je le perds ..."
"... mais alors la gueule ouverte et remplie de crocs de Cato tombe, tout comme le reste de lui alors qu'Amicus lui balaie les jambes d'un puissant coup de pied."
"Cato se couche durement sur le côté juste en face de moi, sifflant avant qu'Amicus ne saute sur lui, atterrissant sur le loup plus âgé avec ses genoux et un poing sur le visage."
"Cato ne semble même pas le remarquer, bien qu'il s'agrippe immédiatement à Amicus, leurs pattes se grattent alors qu'ils essaient tous les deux de trouver une prise."
"Ils sont dans une impasse pendant un certain temps, chacun ne parvenant pas à trouver une bonne prise alors qu'ils se tordent et se retournent, faisant des sons grondants tout le temps."
"À certains moments, j'ai du mal à discerner les deux, leurs jambes et leurs bras semblant se fondre ensemble alors qu'ils s'agrippent autour du corps de l'autre."
"On ne m'a jamais beaucoup parlé du combat à mort, même quand j'ai demandé à Neferu."
"Tout ce que je sais, c'est qu'ils ont tendance à être très courts, mais c'est déjà ressenti comme une éternité."
"Soudainement, je suis capable de les distinguer alors que Cato verrouille le bras droit d'Amicus dans une épaule."
"Bien que je l'ai déjà vu faire avant, généralement pour faire sortir l'autre adversaire, Cato va immédiatement jusqu'au bout et le calme du début de soirée est brisé par un pop massif et un son crunching."
"Amicus hurle, et je me retrouve debout sans même m'en rendre compte."
"Il faut tout ce que je n'ai pas pour sauter en ce moment, même si Cato se penche dans la cale, provoquant des convulsions d'Amicus à cause de la douleur."
"Alors Cato lâche prise et mon loup se recroqueville sur le côté, tremblant violemment, tenant son bras avec son autre patte."
"Je veux aller vers lui, mais Cato est déjà là, poussant le plus jeune loup sur son dos."
ca "\"J'aurais dû faire ça il y a longtemps, chiot.\""
"Je savais que ça arriverait."
"Amicus essaie de se battre avec son bon bras, même ses jambes, essayant de verrouiller ses chevilles autour du cou de Cato, mais le vieux loup chevauche la taille d'Amicus avant de lui claquer un poing dans le nez."
"Il y a un son de craquement plus doux cette fois, et Amicus devient immédiatement mou, les yeux vides, la patte tombant à ses côtés."
"Je savais que Cato était trop doué pour Amicus, mais pour une raison quelconque, j'ai pensé ..."
stop music fadeout 10.0
mon "\"{i} Ce sont les événements qui se produiront. Vous êtes sur la bonne voie. {/ I}\""
"Mais suis-je?"
n "\"[mc].\""
"Neferu me chuchote précipitamment."
"Cato frappe à nouveau Amicus, même si l'autre loup a arrêté de bouger, et Amicus se branle sous le poids du loup légèrement plus grand."
n "\"[mc], vous devez courir, Cato ne sait probablement pas que vous êtes ici.\""
"Les yeux d'Amicus sont mi-clos, inconscients de ses derniers instants alors que Cato pousse ses fesses le long des cuisses de l'autre loup, se donnant de la place pour atteindre le cou d'Amicus."
n "\"Courez vers la ville, vers les bois ... n'importe où ...\""
"Je secoue la tête en silence."
"Est-ce que c'était vraiment censé arriver?"
"Pourquoi ai-je été mis sur ce chemin si cela s'est terminé par la mort de mon loup?"
"Pourquoi les parents ne m'aident-ils pas?"
play music "music/between dimensions.ogg" fadein 3.0
scene bg white with dissolve
scene bg amphitheaterevening with slow_dissolve
"À ce moment-là, la lumière du soleil couchant attrape quelque chose de brillant à ma gauche."
"Je regarde par-dessus, et je suis presque aveuglé par le brillant reflet de la lumière de Vita sur la lame du poignard."
"Celui que Cato avait mis de côté après avoir presque exécuté Neferu."
"Des bijoux rouges et bleus ornent le manche tandis que la lame dorée brille plus que tout métal que j'ai vu auparavant."
"{i} Les règles n'ont pas d'importance. {/ i}"
"Robotiquement, je me penche au-dessus de l'allée et attrape le poignard par la poignée."
n "\"[mc]?\""
"J'ignore Neferu, et en même temps je vois Virginie juste en face de moi."
"Ses yeux sont écarquillés, et elle est debout aussi, mais au lieu de regarder le combat, les mâchoires de Cato se rapprochant de plus en plus du cou d'Amicus, elle me regarde et me montre du doigt."
"Elle pointe droit vers Cato, m'encourageant silencieusement à faire ce que je suis sur le point de faire."
"Mais je n'ai pas besoin d'encouragement."
"Les règles n'ont pas d'importance."
"Je saute de mon siège, la distance est si petite que je redescends pratiquement au-dessus des loups."
"En même temps, je lève le poignard à deux mains au-dessus de ma tête et je l'abaisse aussi fort que possible dans le dos de Cato."
play sound "sfx/stab1.ogg"
"Comme au ralenti, je sens la lame glisser dans ma cible, très facilement au début, comme si on coupait du beurre ..."
"... puis soudainement je ressens quelque chose de dur, et il y a un bruit étrange, étouffé et bégayé de friction alors que la lame ralentit considérablement."
"Il continue à s'enfoncer cependant, par rafales soudaines de quelques centimètres à la fois, et ce n'est que lorsque la poignée atteint la fourrure de Cato que je me rends compte que j'ai profondément creusé dans l'os ... une côte peut-être."
"Cato hurle, se cambrant soudainement en arrière, et je ne peux qu'espérer que j'ai été assez rapide pour qu'il n'ait pas pu enfoncer ses dents dans le cou d'Amicus."
"Je n'ai pas fini cependant, et je tire une, puis deux fois, avant de pouvoir enfin arracher la lame de l'os."
"Pendant cette fraction de seconde, Cato commence à tendre la main maladroitement, incapable de trouver mon arme avant que je ne la ramène à nouveau, au-dessus de ma tête avant de l'abaisser aussi fort que possible dans le côté droit du cou de Cato, juste à la base . "
play sound "sfx/stab2.ogg"
"Cette fois, la lame s'enfonce facilement, encore une fois jusqu'à la garde."
"Je l'ai tiré en arrière une fois de plus, avec l'intention de le replonger à nouveau, mais finalement, Cato se retourne contre moi, balançant aveuglément sa patte."
"Ses doigts trouvent mon avant-bras droit alors que je soulève la lame une fois de plus, et il le tient fermement."
ca "\"[mc]!\""
"Son exclamation est en partie étonnement, en partie fureur."
"Son autre patte trouve le poignard, et même si j'essaye de le retenir, il le fait glisser facilement hors de mes mains, même s'il tient l'extrémité de la lame."
"Le sang est partout à ce stade, et je ne peux qu'espérer que ce n'est que celui de Cato."
"Je commence à reculer, essayant de regarder Amicus pour voir ce qui lui est arrivé, mais c'est à ce moment-là que Cato me frappe à nouveau."
play sound "sfx/cut.ogg"
stop music fadeout 5.0
"Je sens l'air me chatouiller le cou et le menton, et pendant un moment je pense que j'ai esquivé son swing ..."
"... mais ensuite je vois qu'il tend la lame, à sa droite après l'avoir balancée vers moi."
"{cps=10} ..."
"Quelque-chose ne va pas."
"Quelque chose ne va vraiment pas."
"Je baisse les yeux et vois une soudaine giclée de sang, éclaboussant les pierres en dessous de moi, puis une autre giclée, puis une autre."
"Je recule et halète, et quand je le fais, j'ai l'impression que l'air entre de deux endroits à la fois, et je tousse alors que quelque chose de liquide descend dans ma gorge dans le mauvais sens."
"Encore une fois, je halète, et cette fois j'entends un son bouillonnant de ma gorge, et je comprends enfin ce qui s'est passé alors que je lève mes mains à mon cou, trébuchant puis tombant."
"Je m'attends à me claquer contre les sièges en pierre, mais à la place, c'est contre quelque chose de velu et de chaud."
"Je lève les yeux et vois Neferu assis au-dessus de moi alors qu'il s'était déplacé pour me rattraper avec ses genoux."
show nef shocked with dissolve
"Il me regarde avec un air d'horreur sur son visage."
n "\"[mc] ...\""
"Il lève les yeux."
n "\"Amicus ... Amicus, réveille-toi et aide-le!\""
"Je fronce les sourcils, toujours inquiet pour Caton, et bien sûr, alors que je regarde en avant, je vois le faux empereur sur un genou, serrant son cou, saignant autant que moi."
hide nef with dissolve
"Ses oreilles sont tournées vers l'avant, vers la voix de Neferu, et je le vois commencer à se diriger vers nous."
ca "\"K — Khemian ...\""
"Les yeux du loup sont sauvages, furieux, concentrés en direction de Neferu."
"Il semble m'avoir déjà oublié, alors même qu'il semble se rendre compte qu'il est en train de mourir."
ca "\"Vous ... vous ... avez causé ceci ...\""
"J'ai le sentiment que ces mots \"vous\" et \"ceci\"ont beaucoup plus de sens pour Cato que je ne pourrais jamais espérer en savoir."
"C'est un moment étrange alors que je suis allongé sur les genoux de Neferu, en train de saigner."
"Je suppose que je savais que Cato blâmait les Khemians pour la plupart de ses problèmes, pour la plupart des problèmes de l'empire."
"Il a essayé de le cacher en faisant semblant de donner à Amicus une bonne chance contre l'empereur."
"Au fur et à mesure que cela se dissipait, ses intentions sont devenues claires, tout comme sa folie."
"Il a l'intention de tuer Neferu pour tuer complètement toute chance d'alliance, même si cela signifie la destruction complète de l'empire des loups."
"D'une certaine manière, c'est un risque qui vaut la peine d'être pris pour Cato."
"Le vieux loup se rapproche, rampant pratiquement maintenant, laissant de lourdes éclaboussures de sang sur le sol."
"Il lève faiblement le poignard, et je sens Neferu se crisper derrière moi, se préparant probablement à rouler hors du chemin, mais ensuite quelque chose s'enroule autour du cou de Cato."
"Avec un étranglement gargarisé, Cato est tiré en arrière par Amicus avant d'être claqué au sol."
"Alors, Amicus est sur le vieux loup, le museau contre son cou, le déchirant."
"Je regarde en état de choc, puis regarde en bas, loin de l'horreur de ce que je vois."
"Et c'est là que je me vois couvert de sang ... alors, tellement de sang."
"Tout mon torse nu est peint en rouge, et une plus grande partie continue de se déverser sur ma poitrine par vagues, bien que ce soit moins que les giclées initiales que j'avais vues quand j'étais debout."
"Je lève mes mains vers mon cou, toujours ressentant cette étrange sensation de froid qui pénètre profondément dans ma gorge, comme si tout était ouvert et exposé à l'air."
"J'essaye de parler, de dire à Neferu que j'ai besoin d'aide, mais seul un sifflement râpeux et bouillonnant sort de mon cou."
"Je lève les yeux, voyant Neferu me regarder, son expression à nouveau incrédule."
"Je suppose que ce serait assez choquant de voir votre ami avec son cou ouvert, mourir sur vos genoux."
"Suis-je en train de mourir?"
"J'essaye à nouveau de me couvrir le cou, mais l'entaille est si profonde ... j'ai l'impression que si je me penche trop en arrière, ma tête va juste ... tomber sur mon dos."
"Vaguement, j'entends les sons grondants d'Amicus, ainsi que les cris rauques de Cato, sonnant comme moi quand j'essayais de parler."
"Les bords de ma vision commencent à devenir flous et noirs et le visage de Neferu commence à s'estomper ..."
scene bg black with transition_fade
"... puis soudain il y a un grand changement et je me réveille, cette fois-ci, trouvant Amicus qui me regarde."
scene lastmoment with slow_dissolve
play music "music/light years apart.ogg" fadein 3.0 noloop
"Un sentiment de soulagement écrasant m'envahit."
"J'ai la chance de voir mon loup après tout."
"Je lui souris, alors même qu'il me regarde avec un air de dévastation totale et totale."
a "\"Non, non, non, non, non, s'il vous plaît! Récupère Felix ... Virginie, dis à Alex de récupérer Felix!\""
"Ses larmes commencent à couler sur mon visage, et je tends la main, essayant de les brosser comme il l'a fait pour moi plusieurs fois."
"Il attrape ma main avant que je puisse cependant, la pressant contre mon cou."
a "\"Tout ira bien! Vous allez bien! Ce n'est pas mal ... Ce n'est pas mal ...\""
"En fait, je rigole un peu à ça parce que c'est {i} très {/ i} mauvais."
"Je peux dire sans même pouvoir le voir."
"Je vois les bords de ma vision se brouiller à nouveau, et mes yeux semblent essayer de rouler d'eux-mêmes, mais Amicus me secoue un peu et cela me ramène un instant."
a "\"Hé! Hé, reste ici, d'accord? Tu resteras avec moi, oui?\""
"Je hoche la tête en délire, le sentiment accablant de calme et de chaleur me gardant heureux et plein d'amour, même si je sais ce qui se passe, ce qui va m'arriver."
"\"Je suis ici.\""
"J'essaye de parler, mais je n'envoie que plus de sang bouillonnant de mon cou."
a "\" Non, non! Tu n'as pas besoin de parler. Je t'ai.\""
"Comme c'est injuste."
"Mes derniers moments et je ne peux même pas dire à mon loup que je l'aime."
"Je tends ma main libre, la posant doucement contre le visage d'Amicus."
"Je caresse sa joue doucement, sciemment, et bien qu'il la tienne contre son visage avec sa propre patte libre, il secoue la tête vers moi."
a "\" Arrêtez ça, tout ira bien. Félix va vous guérir, nous nous reposerons dans ma chambre, je vous emmènerai sur l'île ... je vous emmènerai en ville ... nous serons heureux ... nous vieillirons ... .ensemble.\""
"Les larmes recommencent à couler, et j'essaye juste de garder le sourire sur mon visage, de montrer à Amicus que je vais bien, que je suis heureux, que tout va bien."
"Et bien que son chagrin soit difficile à regarder, il n'y a rien que je préfère voir à la fin; le visage de mon loup, encadré par les rouges rosés du coucher de soleil."
"Et puis, alors que mes yeux recommencent à rouler, je ne peux pas les arrêter, peu importe à quel point Amicus me secoue."
scene bg black with slow_dissolve
stop music fadeout 10.0
a "\"[mc]! Non je t'en prie! Ne me laisse pas ici! S'il te plaît, reviens moi! Tu ne peux pas me laisser seul comme ça!\""
"\"Je suis ici.\""
a "\"Non, non, non ... parlez-moi!\""
"\"Je reste avec vous ...\""
$ renpy.pause(delay=5.0, hard=False)
"..."
"..."
"..."
play music "music/beyondthestars1.ogg" fadein 5.0
if fate == False:
    "I drift through the blackness, feeling a sense of peace like I've never known before."
    "Even though the space is empty, I feel it crowded with others, so many others...or is it one other?"
    "I sense so many different minds and thoughts, melded together as one."
    "\"Hello...\""
    "\"We must apologize for what has happened to you.\""
    "\"It was not our intention for it to end this way.\""
    "\"While not ideal, you have still moved the work of Meera forward.\""
    "\"Though we intended for you to complete it, this can be done at a later stage, by a latter sapient.\""
    "\"Thank you, [mc], for doing your part for humankind, for wolves, for the {i}Galaxias{/i} as a whole.\""
    "\"Now go, be at peace, be one with the amalgamation of intelligence from whence you came.\""
    "\"Thank you...\""
    "I begin to dissolve."
    "I'm nowhere and everywhere."
    "I'm never and always."
    "I'm nothing..."
    "...and everything."
    stop music fadeout 7.0
    "{cps=10}...all at once..."
    $ renpy.pause(delay=5.0, hard=True)
    return
else:
    "I drift through the blackness, feeling a sense of peace like I've never known before."
    "Even though the space is empty, I feel it crowded with others, so many others...or is it one other?"
    "I sense so many different minds and thoughts, melded together as one."
    "\"Hello...\""
    "\"We apologize for what has happened to you.\""
    "\"We know that you are confused.\""
    "\"We told you that this could be prevented...\""
    "\"...and it will be.\""
    "\"You will not leave him to be alone.\""
    stop music fadeout 5.0
    "\"Be at peace for now, for he will come for you.\""
    "\"Wait for him...\""
    "..."

scene bg amphitheaterevening with slow_dissolve
play loop "sfx/forest.ogg" fadein 3.0
com "\"Amicus est le vainqueur. Tous saluent l'empereur Amicus.\""
"Les mots sonnent creux dans les oreilles d'Amicus, tout comme le faible rugissement de la foule à Adastra City tout au long du lac."
"Le loup ne peut que regarder l'humain dans ses bras, réalisant soudain à quel point il est léger et fragile."
"Et le sang ..."
"... tellement de sang qui peint le devant de son humain qui il y a quelques instants avait été si plein de vie."
"Une larme tombe du bout du nez d'Amicus et sur le cou de [mc], se mélangeant au sang qui a maintenant cessé de couler de l'entaille profonde."
"L'air ne bouillonne plus à travers le liquide rouge non plus."
"Un son étrange et étouffant sort des lèvres d'Amicus, un son qu'il ne s'est jamais entendu faire auparavant."
"La tristesse débordante dans son cœur a apparemment disparu pour être remplacée par quelque chose de vide, de froid ..."
"... comme s'il n'y avait plus rien là-bas."
"Pourtant, Amicus veut que l'humain vive, utilise ces capacités de guérison spéciales qu'il semble posséder, respire à nouveau."
"Mais alors même que Virginia se déplace pour trouver Félix, Amicus sait que rien ne peut être fait pour quelque chose comme ça."
"Cato avait failli décapiter l'humain, coupant à travers tout ce qui était important."
"Bercant la tête de [mc] avec précaution, Amicus soulève le jeune humain jusqu'à sa poitrine, le serrant étroitement dans ses bras, fermant les yeux et sentant les larmes couler sur ses joues, son menton et ses cheveux.»"
"C'est calme, et Amicus ouvre les yeux pour voir Neferu toujours assis là devant lui, le regardant sous le choc."
show nef shocked with dissolve
"Quand le chacal rencontre ses yeux, il plonge rapidement la tête, baissant les oreilles."
show nef sad with dis
n "\"Amicus, je - je suis vraiment désolé ...\""
hide nef with dissolve
"Le loup lève les yeux pour voir un drone juste au-dessus de la tête de Neferu, planant alors que son objectif se concentre de manière voyeuriste sur lui, transmettant son chagrin à Adastra."
"Mais cela n'a rien à voir avec ces drames, les tragédies de la mort romantique qu'il avait vu jouer sur les écrans tant de fois auparavant."
"Il n'y a {i} rien {/ i} de romantique à ce sujet, car Amicus est sûr que son public le trouve en ce moment."
"C'est la vraie mort, et le sentiment est familier."
"C'est creux, vide, étouffant, comme être entraîné dans un océan noir, froid et sans fond."
"C'est comme quand sa mère est morte et que Cassius a crié sur son corps comme un animal blessé."
"C'est comme quand il a appris la nouvelle que son père était mort et comment il était tombé à genoux, se cramponnant à sa poitrine et haletant comme s'il avait été abattu."
"Mais c'est pire d'une manière ou d'une autre, et Amicus ne peut même pas le comprendre."
"Cela le frappe plus fort que tout ce qu'il a ressenti dans sa vie."
"Tout devient gris, la couleur étant aspirée de sa vision, de sa vie ..."
"Et même s'il ne sanglote pas maintenant, les larmes coulent librement sur ses joues."
"Il ne sait pas du tout comment il peut s'en remettre ... il sait qu'il ne le fera probablement jamais."
"C'est sa faute."
"Il avait forcé l'humain ici."
"Il s'était senti mieux en disant que [mc] avait le choix en la matière, qu'il était libre de faire ce qu'il voulait."
"Mais ce n'était pas du tout vrai."
"Il avait pris la vie de l'humain, tout comme Cato l'avait fait maintenant."
"Amicus réalise alors qu'il n'est pas différent des loups qu'il pensait être au-dessus."
"Qu'il était plus éclairé d'une manière ou d'une autre en essayant de tenir toute vie consciente comme égale."
"Il est encore pire."
"Et même si cela lui briserait le cœur de ne jamais avoir rencontré [mc], Amicus souhaite seulement qu'il ne l'ait jamais amené ici en premier lieu."
"Jusqu'à sa mort."
"Cette pensée amène une autre vague de chagrin déchirant à traverser sa poitrine creuse, et pendant un moment, il ne peut presque plus respirer."
a "\"S'il vous plaît, [mc] ...\""
"Le jeune loup chuchote dans les cheveux de l'homme, sa voix n'est plus qu'un doux gémissement alors que des larmes fraîches brouillent sa vision."
"Ses enseignements depuis qu'il était un chiot commencent à me venir à l'esprit;"
"L'âme de [mc], comme l'âme de tous les sapients, monte vers la Grande Intelligence, se mêlant à la vie de milliards d'autres; avec son père, sa mère, peut-être Cassius, aussi."
"Un endroit qu'il rejoindrait aussi un jour ..."
"...mais..."
"... mais l'âme de l'homme appartenait {i} ici {/ i}, dans ses bras, pour ne pas être mélangée et consommée par les parents, pas encore."
"Cet être mélangé et singulier n'est pas [mc]."
"C'est comme une belle peinture murale brisée, puis reconstruite en autre chose."
"[mc] existe toujours, en ce moment même, il existe, mais ce n'est plus {i} lui {/ i}."
"Amicus serre les dents, sentant la colère commencer à surmonter le chagrin accablant."
"Non..."
"...Non..."
stop loop fadeout 3.0
play music "music/daydreamer.ogg" fadein 3.0
a "\"... Non\""
"Comment osent-ils."
"Ce n'est pas juste."
"Les parents avaient parlé à [mc], lui avaient dit quoi faire, l'avaient conduit à ce point."
"Quand l'humain avait dit à Amicus qu'il était inquiet à l'idée que quelque chose de terrible se produise ..."
"Amicus serre les dents, se souvenant de la façon dont il l'avait brossé, même s'il avait dit à [mc] qu'il le croyait, qu'il n'aurait pas à s'inquiéter s'il suivait leurs conseils."
a "\"Non ...\""
"Amicus secoue la tête, toujours fermement agrippé à l'humain."
show nef sad with dissolve
n "\"Amicus?\""
"La voix de Neferu est hésitante, presque effrayante, comme s'il s'inquiétait de ce qu'Amicus pourrait faire."
"Amicus n'en est même pas sûr lui-même alors qu'il se lève, berçant l'humain dans son seul bon bras, facilement capable de le faire à cause de leur différence de taille."
hide nef with dissolve
"Il se retourne et marche rapidement vers le palais, faisant presque du jogging, ignorant les diverses secousses de douleur dans tout son corps."
"Il ne regarde même pas le corps immobile de Cato en passant."
"L'expression du loup est stoïque maintenant, une étrange rage bouillonnant juste sous la surface."
n "\"Amicus!\""
"Neferu l'appelle, mais Amicus ignore le chacal, mis sur une chose, et une seule chose:"
"Les parents ont peut-être pris ses parents, peut-être même son frère, mais ils ne vont pas prendre son humain."
"Il ne le permettra pas."
scene bg palace1 with dissolve
"Alors que le loup entre dans le palais, il remarque Alex arpentant le couloir."
"Il s'arrête en voyant le loup s'approcher."
show ale shocked with dissolve
al "\"Amicus! J'ai entendu dire que tu es maintenant empereur et ...\""
"Il s'éloigne en voyant [mc] bercé dans le bras du loup."
show ale vshocked with dis
"Le sang recouvrant le corps, coulant le long d'un bras mollement suspendu pour s'égoutter doucement du bout des doigts."
"Amicus passe devant le chat, les yeux fixés droit devant, sans expression."
hide ale with dissolve
"Rien ne semble exister en dehors de la vision tunnel du loup."
"Bientôt, il arrive à la porte qu'il cherche et se penche en avant, pressant son épaule blessée contre le panneau pour l'ouvrir, ignorant la flambée de douleur qui le traverse comme il le fait."
scene bg archivesday with dissolve
"Amicus s'approche des archives, fixant l'orbe, comme si la machine elle-même était les parents."
"Le grand loup s'arrête devant lui, regardant la structure bleue brillante pendant un moment avant de regarder [mc]."
"La couleur cendrée de la peau est déconcertante, si différente des tons profonds qu'elle avait autrefois."
"[mc] est mort, Amicus le sait, mais il ne l'acceptera pas."
"Le loup presse son visage contre celui de l'humain pendant un moment, sentant la chaleur s'estomper avant de l'embrasser doucement sur le dessus de sa tête."
stop music fadeout 7.0
"Sur ce, Amicus se penche en avant, les pressant tous les deux contre la sphère."
"Puis il se connecte, et il fusionne avec l'univers."

scene bg black with slow_dissolve
"Nous continuons à dériver à travers un espace infini, le contenu."
play music "music/beyondthestars1.ogg" fadein 3.0
"Malgré tout, nous faisons confiance aux êtres qui nous entourent, à nous tous et aux autres ... aux parents."
"Les parents."
"Tout cela était censé arriver."
"Et même si c'était dur et terrible ..."
"... le pire est maintenant passé."
"Et cette seule pensée suffit pour nous garder complètement détendus, des vagues et des vagues de soulagement nous submergeant."
"Mais dans la cacophonie des pensées et des émotions, quelque chose ressort ..."
"Bien que les êtres se mélangent, l'un semble se séparer pendant un moment, uniquement pour se concentrer directement sur nous ... sur ... moi ..."
"Cela me sort un peu de ma transe et je tourne mon attention sur eux."
"Amicus?"
"Mais alors, à mesure que je me concentre davantage sur cet être, j'éprouve un sentiment différent; pas {i} lui {/ i}, mais {i} elle {/ i}."
"On dirait qu'elle veut me parler."
"Elle n'est pas familière, pas quelqu'un à qui j'ai parlé avant ..."
"Mais l'intensité avec laquelle elle se concentre sur moi ..."
"\"Bonjour?\""
stop music fadeout 10.0
"Je tends la main, mais soudain, l'amalgame d'intelligence commence à s'éloigner, et je me sens extrait de sa masse."
"Le sentiment est bizarre et je manque presque la foule de pensées et de sentiments, d'être un avec plusieurs."
"Mais ensuite je me sens à nouveau ... mon corps ... commence à se matérialiser à partir de rien."
"Le néant autour de moi devient lentement quelque chose ..."
scene finalspace with slow_dissolve
"Pendant un moment, je flotte dans les airs ... puis je suis tenu par quelque chose de fort et de solide."
show ami crossed serious c with slow_dissolve
"La première chose que je vois est le visage d'Amicus."
"Il me regarde, sombre et déterminé."
"Tout comme je me concentre sur lui, son expression change."
show ami surprised c with dis
a "\"[mc]?\""
"Je bouge un peu, essayant de mieux me concentrer sur mon loup."
a "\"[mc]!\""
play music "music/Romance.ogg" fadein 2.0
hide ami c with dissolve
"Soudain, je suis entouré de fourrure, je me serre contre Amicus, mon visage pressé contre son cou."
"Instinctivement, j'enroule mes bras autour de lui."
a "\"Oh dieux, êtes-vous réel? Dites-moi que vous êtes réel, [mc] ... s'il vous plaît ...\""
"Il halète les mots, comme s'il venait prendre l'air après avoir plongé au fond du lac."
"J'ai du mal à me souvenir des choses, pourquoi il semble si bouleversé."
"Mais je sais que quelque chose de grave est arrivé, et maintenant c'est fini, alors j'essaye de le réconforter."
m "\"Je suis réel ... Je suis ici.\""
"Ma voix est étrange, comme si je ne l'ai pas utilisée depuis un moment."
"Au début, je pense que je suis de retour dans la chambre d'Amicus après m'être réveillé du coma, essayant toujours de le convaincre que tout va bien."
"Comme si nous nous étions endormis et nous nous étions réveillés et il voulait être rassuré à nouveau que je ne vais pas disparaître."
"Mais ensuite je me souviens que Cato est venu ce matin-là ..."
"Les choses se mettent en place comme une longue rangée de dominos géants et lourds."
"Je me suis soudainement assis un peu, contre la poitrine d'Amicus, en me repoussant pour que je puisse lever les yeux vers lui."
m "\"Attendez! Le combat ... Cato ... Amicus, ça va?\""
show ami embarrassed c with dissolve
"Je le regarde, essayant de vérifier ses blessures."
"Le sang et le gonflement que j'avais vu dans l'amphithéâtre ont disparu."
"Il est propre et bien soigné, et son bras semble bien à en juger par sa solidité sous moi."
"Mon bref regard sur lui est terminé alors qu'Amicus me tire soudainement contre sa poitrine, sanglotant contre moi."
hide ami c with dissolve
"J'ai déjà vu Amicus pleurer, de retour dans le donjon, mais pas ces sanglots déchirants que je peux ressentir dans mon propre corps."
"Cela me choque encore plus pour mes sens."
"Fermement, je repousse sa poitrine, créant un espace entre nous pour que je puisse tenir son visage dans mes mains."
show ami tears c with dissolve
"Il me regarde simplement en pleurant ouvertement, et je regarde les larmes sortir de ses yeux et semblent disparaître dans la fourrure de ses joues."
"Je suis sûr que nous voulons tous les deux dire beaucoup de choses en ce moment."
"Que s'est-il passé, que se passe-t-il maintenant, que {i} va-t-il {/ i} se passer, mais à ce moment précis dans le temps et dans l'espace, nous sommes de retour ensemble."
"C'est impossible, mais ça arrive, alors je m'accroche à lui à nouveau, et il me tient juste pendant que je presse mon visage contre sa poitrine, écoutant son cœur martelé, fermant les yeux."
hide ami c with dissolve
"Si c'est l'éternité, alors ça me va tout à fait."
"Je ne sais pas combien de temps passe, mais comme cette pensée me traverse l'esprit à plusieurs reprises, mes yeux s'ouvrent soudainement."
"Je recule à nouveau, levant les yeux vers le loup, tenant à nouveau son visage."
m "\"Attendez ... si vous êtes ici, avez-vous ...\""
"Je me demande soudain si Amicus a peut-être été sérieusement blessé dans le combat, qu'il n'a pas réussi après tout."
"Mais Amicus secoue doucement la tête, ses sanglots s'étant calmés en reniflements et hoquet modérés."
show ami embarrassed c with dissolve
a "\"Non ... non, je vais bien. J'ai gagné. Caton est mort.\""
"Je suis inondé de soulagement."
"Il me caresse les cheveux doucement, lentement, et je me demande pourquoi il a toujours l'air si triste."
m "\"Mais comment vas-tu ici, n'est-ce pas ...\""
"Je regarde autour de moi l'espace infini qui nous entoure."
"Les étoiles et les planètes sont inhabituellement proches, incroyablement brillantes et incroyablement vives."
"Les bleus, les violets et les noirs sont profonds et monolithiques, signalant l'espace sans fin qui s'étend au-delà."
m "\"Suis-je mort?\""
"Amicus me ramène contre lui, me forçant à détourner le regard de l'univers qui bouillonne."
show ami serious c with dis
a "\"Non, vous êtes ici.\""
"On dirait plus qu'il se convainc plutôt que moi."
m "\"Mais où est 'ici'?\""
"Amicus est silencieux pendant un moment, et je me sens content de m'appuyer contre lui pendant un moment, voulant juste être proche de lui."
"À un moment donné, Amicus s'était assis, et je suis bercé sur ses genoux."
"Étant donné que nous ne flottons pas simplement en apesanteur, je dois supposer qu'il y a quelque chose de solide sous nous d'une manière ou d'une autre."
"Amicus renifle à nouveau."
show ami sad c with dis
a "\"J'ai fusionné mon esprit avec les archives pour parler aux parents ... c'est tout ce que je sais.\""
"Je pense."
m "\"Ai-je fait la même chose, alors?\""
a "\"Je te tenais quand je l'ai fait ...\""
"Mon cou ... le sang ..."
"Je le regarde à nouveau."
m "\"Amicus ... suis-je en vie?\""
"Amicus me regarde pendant un moment avant que son visage ne se fige et ne pleure à nouveau."
show ami embarrassed c with dis
a "\"Je ... ne sais pas.\""
show ami tears c with dis
"Il gémit les mots et je le serre immédiatement dans mes bras."
hide ami c with dissolve
m "\" Hé, je vais bien, tu vois? Je suis ici.\""
"Une autre crise de sanglots commence."
"Et maintenant je sais pourquoi."
"J'ai dû mourir, et maintenant, pour une raison ou une autre, les parents nous ont permis de nous réunir d'une manière ou d'une autre."
"Et je sais qu'Amicus doit se demander la même chose que moi:"
"Combien de temps cela va-t-il durer?"
"J'essaye de penser à quoi dire, au cas où ce serait notre dernier moment ensemble, au cas où je serais à nouveau ... absorbé."
"Mais mon esprit est à court de la plus étrange des manières, capable de penser seulement à des choses qui n'ont pas d'importance."
"Alors, je m'arrange sur ce qui venait de se passer."
m "\"Vous êtes empereur maintenant, Amicus.\""
"Amicus hoche la tête contre moi, ne faisant pas confiance à sa voix pour le moment, apparemment."
m "\"Je suis si heureux pour toi.\""
"Maintenant, il secoue la tête, répandant des larmes sur ma joue."
"Je déteste le voir comme ça."
"Je déteste que ce soit la dernière façon dont je le verrai."
m "\"S'il vous plaît, ne pleure pas. Soyons juste ... ensemble maintenant.\""
"Je m'assois droit et tire sa tête contre {i} ma {/ i} poitrine pour une fois, berçant sa forme massive contre moi, caressant ses oreilles et son cou."
m "\"Je vais bien, je te le promets. Je suis allé quelque part quand je ... suis mort.\""
"Le mot est si étrange à dire."
m "\"C'était vraiment sympa, plein de monde. Je n'étais pas seul. C'était paisible.\""
"Amicus prend une profonde inspiration tremblante, se retirant finalement de mon étreinte."
show ami eyes c with dissolve
a "\"C'est merveilleux, [mc] ... Mais je suis désolé, car je ne vous laisse pas y retourner.\""
"Amicus a soudainement l'air résolu alors qu'il sourit à travers les larmes."
show ami c with dis
a "\"Vous revenez avec moi.\""
"Sa voix se brise plusieurs fois, et je peux dire qu'il le pense vraiment."
"Il est vraiment certain qu'il va me ramener de la dimension des morts."
"Je ne sais pas quoi dire."
"Je ne sais pas grand-chose des parents ou de l'au-delà, mais Amicus doit le faire, alors je lui fais confiance."
"Je lui souris."
m "\"OK.\""
show ami eyes c with dissolve
stop music fadeout 10.0
"Il me sourit en retour, puis m'embrasse très soudainement."
hide ami c with dissolve
"C'est rugueux et humide, et mes lèvres lui manquent un peu, mais je l'embrasse en le tenant fermement."
show ami c with dissolve
"Une fois qu'il a finalement reculé, je suis heureux de voir mon loup retrouver sa confiance habituelle ... même s'il doit continuer à renifler avec son nez qui coule."
"Je regarde à nouveau le cosmos tourbillonnant."
play music "music/atmosphere.ogg" fadein 5.0
m "\"Euh, pouvez-vous juste ... nous faire sortir?\""
"Amicus fronce les sourcils, regardant autour de lui."
show ami embarrassed c with dis
a "\"Euh ... c'est en fait la première fois que je fais ça, alors ... je ne suis pas sûr.\""
"Amicus regarde derrière nous, puis de haut en bas, puis s'éclaircit la gorge."
a "\"Euh, Com? Com, êtes-vous là?\""
"Silence."
show ami serious c with dis
a "\"Hmmm.\""
"Je peux dire qu'Amicus est déjà à court d'idées."
m "\"Les parents font ça, non?\""
a "\"Je pense que oui, même si je ne leur ai jamais parlé. Vous avez en fait plus d’expérience dans ce domaine.\""
show ami c with dis
"Amicus me sourit, puis lève les yeux."
show ami crossed serious c with dis
a "\"Peut-être si nous marchons ... en arrière.\""
"Je lance un regard étrange à Amicus et juste au moment où je suis sur le point de souligner l'absurdité de retourner à Adastra à travers un espace infini, une présence en plein essor se fait connaître."
mon "\"Je suppose que vous avez terminé?\""
stop music fadeout 10.0
"Amicus et moi sautons tous les deux et le loup bondit sur ses pieds, me tenant dans ses bras."
show ami angry teeth c with dis
a "\"Qui est là!?\""
"Amicus crie dans le vide, grognant."
m "\"C'est bon Amicus, c'est juste le moniteur.\""
"Je le dis comme s'il n'était qu'un vieil ami à moi."
"Amicus ne baisse pas sa garde cependant, et continue de grogner dans l'espace."
"Le moniteur exprime son amusement de sa manière silencieuse, mais je peux comprendre pourquoi Amicus ne baisse pas sa garde."
"C'est évident dans la façon dont il me tient, me serrant fermement contre sa poitrine."
"Il a peur que je vais lui être enlevé."
"Je suis trop."
mon "\"Si vous l'êtes, je vais ouvrir le canal de communication maintenant.\""
"Amicus lève un sourcil."
a "\"De quoi diable parlez-vous?\""
mon "\"Vous souhaitez parler aux parents, n'est-ce pas? Ils souhaitent vous parler directement ... au moins aussi directement que possible.\""
"Il y a une pause, et je vois les engrenages tourner dans la tête d'Amicus alors que ses oreilles bougent."
show ami angry c with dis
a "\"... Oui.\""
mon "\"Alors c'est fait.\""
"La présence du moniteur disparaît et tout à coup, il y en a une autre."
"Pas un, mais beaucoup, semblable à ce que j'avais ressenti plus tôt."
"C'est encore différent."
"Au lieu de fusionner, ces entités sont distinctes et séparées les unes des autres."
"Mais ils sont si similaires qu'ils pourraient être des copies d'une seule personne."
"Leurs intentions sont étrangement uniformes, comme s'ils étaient tous exactement sur le même chemin."
"Contrairement au moniteur, qui au moins se sentait au même niveau que n'importe quel autre intelligent, ces entités se sentent ... étrangères."
"Ce qui est une chose étrange à ressentir après tout ce que j'ai vécu, mais ces choses sont si différentes."
"...donc..."
"...différent..."
scene finalspace2 with slow_dissolve
a "\"puits? Montre toi.\""
"Amicus aboie au vide, restant courageux face à toutes ces présences titanesques."
m "\"Vous ne pouvez pas nous voir.\""
play music "music/between dimensions.ogg" fadein 5.0
"Sa bouche bouge d'elle-même, son esprit devient soudainement vide, semblant se fondre dans l'espace autour d'eux."
"Amicus regarde l'humain avec confusion."
a "\"quoi?\""
"Il regarde en retour."
m "\"Nous ne pouvons pas vous parler directement.\""
a "\"[mc]?\""
m "\"Mais nous avons d'autres méthodes ...\""
"Le visage d'Amicus passe de la confusion ... à l'horreur."
a "\"Dieux ... [mc]?\""
"Il secoue un peu l'humain."
a "\"Hé ...\""
m "\"Il peut vous entendre ... il est simplement occupé en ce moment.\""
"Amicus montre les dents et il commence à trembler."
"Il n'est pas sûr que ce soit à cause de la colère ou de la peur."
"Probablement les deux."
a "\"Si ... vous ne vous arrêtez pas—\""
m "\"Il n'est pas nécessaire de menacer. Tout est comme il se doit.\""
"Amicus est resté là, regardant son amant bouche bée."
"Quelque chose de sinistre et de sombre se déverse dans son ventre."
"Ce n'est pas comme ça qu'il avait envisagé ... rien de tout ça."
"Ce sont les parents?"
a "\"Qu'est-ce que vous êtes?\""
m "\"Nous sommes votre guide, votre leader bienveillant, votre parent ...\""
"Amicus frotte doucement une patte sur le front de l'humain, regardant dans ces yeux vides et fixes."
a "\"Laissez-le tranquille ... s'il vous plaît.\""
m "\"Il n'est pas blessé. Il doit revenir à un état normal une fois la canalisation terminée.\""
a "\"Mais comment?\""
m "\"En termes simples, nous manipulons son comportement en utilisant le Lingua.\""
"Amicus secoue la tête, ne voulant clairement pas du tout ça, mais l'impuissance totale qu'il ressent en ce moment ... c'est accablant."
"Le discours qu'il avait prévu pour ce moment, son intention de déchirer l'arrogance insouciante des parents, ça se dissipe."
"Voir [mc] juste pris par eux comme ça ... c'est assez pour vider complètement le courage qu'il avait autrefois."
"Et alors qu'il regarde les yeux froids de l'humain, il commence à se demander si c'est un cauchemar."
"Pendant un bref instant, Amicus se demande si tout cela est réel, quelle est la réalité même en ce moment ..."
m "\"Ce n'est pas à vous de vous demander, Amicus. Tout ce qui compte, c'est que vous soyez le seul vrai empereur.\""
a "\"Que voulez-vous?\""
"Amicus regarde son humain, se sentant repoussé par ce qui se passe."
m "\"Pour que le travail de Drusus se poursuive ... pour qu'Adastra atteigne enfin son plein potentiel. Pour que les {i} Galaxias {/ i} montent.\""
"Amicus secoue la tête, essayant de se concentrer, essayant de ne pas se concentrer sur le ton robotique de la voix de [mc], sur l'étrange façon dont sa mâchoire bouge, obligé de parler dans la langue du loup."
a "\"Je - j'ai l'intention de le faire ... mais s'il vous plaît, laissez partir l'humain, et - et guérissez-le ... s'il vous plaît. Il n'a rien demandé de tout ça.\""
m "\"L'humain est également impliqué, Amicus.\""
a "\"Mais {i} je {/ i} l'a impliqué.\""
m "\"C'était censé être.\""
a "\"quoi-\""
"Amicus n'est pas sûr que ce soit son propre esprit, ou l'esprit d'un autre qui ramène le souvenir de quand il avait ouvert les archives, comment la Terre avait été près du haut de la liste des planètes profilées."
"Comment cela n'avait aucun sens qu'un monde isolé soit sur cette liste du tout."
"Mais maintenant, cela a du sens ... mais en même temps encore moins de sens."
"Amicus secoue la tête, toujours sous le choc de la situation dans laquelle il se trouve, sentant qu'il est au bord de la folie."
m "\"Fixe. Il y a beaucoup de choses que vous ne comprenez pas, des choses que vous ne comprendrez jamais, et c'est très bien. Toutes les choses ne sont pas censées être comprises par tous les sapients.\""
m "\"Mais vous comprenez au moins que les humains ne sont pas isolés, n'est-ce pas?\""
"Amicus ne dit rien, sachant que son esprit est lu."
m "\"D'une manière ou d'une autre, la culture du loup est là, tout comme la culture khémienne, la culture hindoue ... toutes les cultures de frères et sœurs.\""
"Les parents se taisent et Amicus doit regarder la marionnette en laquelle son amant a été transformé."
"Amicus serre les dents."
a "\"Pourquoi?\""
m "\"Parce qu'ils étaient un microcosme expérimental ... maintenant réussi, et il est temps pour eux d'être intégrés dans les {i} Galaxias {/ i}.\""
"Un autre moment de silence."
a "\"Et ... vous voulez que je vous aide à faire ça?\""
m "\"Non, votre mission est d'aider à unir les frères et sœurs. La première étape est Khemia.\""
a "\"C'était déjà mon intention.\""
m "\"C'est discutable. La situation est périlleuse, Khemia est furieuse après ce qui s'est passé. Vous avez besoin de plus de conseils, donc pourquoi vous êtes ici.\""
"Amicus grogne."
a "\"Je suis ici pour LUI.\""
"Amicus fait un signe de tête à [mc], à la créature intelligente utilisée comme porte-parole."
m "\" Vous êtes ici pour les {i} Galaxias {/ i}, et en tant qu'empereur, vous avez maintenant le fardeau de connaître toutes ces informations, comme votre père le savait, comme son père le savait, et ainsi de suite. \" "
"Amicus serre à nouveau les dents, essayant de comprendre ce qui lui est dit bien qu'il soit complètement dérangé par ce qui arrive à [mc]."
a "\"Si vous vouliez une intégration galactique, alors pourquoi avons-nous été en concurrence les uns avec les autres?\""
m "\"Ceci a été assumé par les frères et sœurs eux-mêmes; la compétition n’a jamais été le but.\""
a "\"Alors pourquoi ne pas nous dire ça? Vous êtes censé être notre guide.\""
m "\"Le processus est lent et prudent; l'interférence est un dernier recours.\""
m "\"Cette communication même est un dernier recours car les frères et sœurs et les enfants s'éloignent de plus en plus du chemin chaque jour, et pas seulement les loups.\""
m "\"Il a fallu 20 000 ans pour atteindre ce stade, et ce temps ne peut pas être perdu.\""
a "\"Alors pourquoi est-ce que vous ne me dites cela qu'à moi et pas à tous les sapients des {i} Galaxias {/ i}?\""
"Amicus regarde à nouveau le visage de l'humain, caressant doucement le visage, détestant le regard vide qu'il reçoit."
m "\"Comme indiqué, une interférence minimale donnera le meilleur résultat. Seules certaines personnalités sont informées à ce stade. Un {i} Galaxias {/ i} développé indépendamment des interférences servira mieux la cause principale dans son ensemble.\""
a "\"La plus grande cause?\""
"Les étoiles et les planètes se déplacent autour d'elles, zoomant vers l'avant, et pendant un moment Amicus a l'impression qu'il pourrait être malade."
"Quelque chose de sombre se profile au bord de l'univers, grandissant lentement, arrachant les parties qu'il touche."
m "\"L'Autre approche, et il doit être confronté.\""
"À ce stade, Amicus se sent mal à l'aise traverser son brouillard de confusion et de colère."
a "\"Quels autres ... sommes-nous en train de préparer la guerre contre quelque chose?\""
m "\"Nous devons nous préparer à un événement dans plusieurs millénaires à partir de maintenant. C'est une étape parmi tant d'autres.\""
"Amicus laisse échapper un faible grognement de frustration, l'imprécision de toute cette situation lui faisant mal à la tête."
a "\"Mais qu'est-ce que cela a à voir avec [mc]?\""
"Amicus change son emprise sur l'humain, voulant juste qu'il revienne à la conscience."
m "\"Il doit jouer un rôle ... et vous devez prendre une décision, Amicus ...\""
if end_game1 >= 3:
    "Everything seems to come together all at once for Amicus."
    jump end_game1
else:
    "Everything seems to come together all at once for Amicus."
    jump end_game2